### ISSUE TITLE
Loot History blank.

### ISSUE THREAD

**Issue by Gombolface** [Roeshambo/MonolithDKP#1]
As it says in the title.

Me and some guildies got together, made a guild to test. We did bidding with a random item, but the "Loot History" is blank, even after we traded the item.

**Comment by Roeshambo** [comment]
Try a /reload and see if it shows up and let me know

**Comment by Roeshambo** [comment]
This issue should be resolved. Please let me know if you have additional problems with it.

**Comment by Gombolface** [comment]
Downloading the update, will post here again if sorted. :)

**Comment by Gombolface** [comment]
Now the /dkp works again, I shall inform you if I'm having an issue once guild members are online.
