### ISSUE TITLE
Min Bid / Max Bid

### ISSUE THREAD

**Issue by krisis6** [Roeshambo/MonolithDKP#10]
Is there anyway you could implement a maximum bid .. the same as you have for minimum bid..

??

**Comment by krisis6** [comment]
or a way to set an exact price, across slots

**Comment by Roeshambo** [comment]
Minimum / Maximum price range would be a bit more involved. But setting a set price would be pretty easy to implement.

**Comment by krisis6** [comment]
What i was looking at exactly was basically turning it into hybrid version of EPGP dkp mashup

I just watched you video after i posted this.. 

So instead of Minimum value, it would be exact value. (in the bid screen & your options)

So people should just !bid and it'll show the exact value.. and it would sort those who bidded out by there total DKP (as it would be most of the time beawarded to whoever had most dkp) which you could still use your custom implementation price aswell to change the price also on indivudual items..

So maybe this could be an option that you enable or disable.. for people who want Bidding or hybrid  dkp

hope i'm not asking for much, i respect everything you've done with this addon, it's well done.

**Comment by Roeshambo** [comment]
I will certainly look into it. Thanks for the suggestion

**Comment by krisis6** [comment]
I been playing with it this afternoon, so the problems i have.

1."!bid"  would need to bid the minimum(or exact) if you implement that.

2. Cant !bid when they have -dkp, need an option to allow that (even if they start in -'s)

3. and ability to sort out list by total dkp as winner would be highest total dkp. instead of bid.

**Comment by Roeshambo** [comment]
Already underway :) Made a completely separate window to select multiple DKP modes.
Bids are submitted with "!bid" and it's ordered by total DKP. Negative DKP gets denied.
Can probably expect it by the end of the week as the request load is rather heavy at the moment and I'd like to get it out with most or all of the requested features rather than pushing out 5 new versions in one week.

**Comment by krisis6** [comment]
Much appreicated :)
