### ISSUE TITLE
Custom Bid /rw message

### ISSUE THREAD

**Issue by Sando999** [Roeshambo/MonolithDKP#100]
Amazing addon, our guild has been using it for weeks and loves it!  Thanks for all your hard work!

Question:  Is there a way to edit the "/rw" messages that happen when initiating an auction using silent bidding?  The default tells people to type in raid or whisper and we want to encourage silent bidding...

Thanks!

:)

**Comment by Roeshambo** [comment]
The message is based off what channels you have selected to be open. In the DKP Modes window you'll see the "Command Channels" dropdown. Uncheck any channel you want to close. If you only have whisper selected, it will only say to whisper in the /rw message.

**Comment by Roeshambo** [comment]
Please reopen if you continue to have issues with this.
