### ISSUE TITLE
is it possible to select all raid members?

### ISSUE THREAD

**Issue by jacobneill1994** [Roeshambo/MonolithDKP#101]
in short our guild <Sleeping Forest> of Arugal has been using your addon and have been happy with its functionality! however we feel that it lacks a "select all" feature to apply dkp points to only those in your current raid, as it currently stands selections must be manually applied to each raid mmber

**Comment by Roeshambo** [comment]
There's a right click context menu on the DKP table that adds a ton of convenience. Can right click and select "Table Views" > "View Raid". Then right click and "Select All" to apply dkp to everyone in your raid. Also an option for "Core Raiders" so you can invite everyone to a raid at once and an option to create a standby list. Among other things.
