### ISSUE TITLE
Auto Standby DKP Issue

### ISSUE THREAD

**Issue by Milkymage** [Roeshambo/MonolithDKP#102]
Just finished our weekly MC + Onyxia raid and tried the Auto Standby function for my team on the bench. 

It would only distribute DKP to one person per boss even though multiple players would enter the 
" !standby " command following a boss kill.

Any reasons why this is happening? Any help would be appreciated.

@Roeshambo

**Comment by Roeshambo** [comment]
Did they all do the command after each boss? It clears the standby list after each kill. Beyond that, I've no idea as it's been working fine for me.

**Comment by Milkymage** [comment]
Is the command case sensitive?

On 17 Nov 2019, at 10:28 pm, Roeshambo <notifications@github.com> wrote:

﻿

Did they all do the command after each boss? It clears the standby list after each kill. Beyond that, I've no idea as it's been working fine for me.

**Comment by Roeshambo** [comment]
No

**Comment by Roeshambo** [comment]
I was wrong. It is case sensitive. It needs to be all lower case. I apparently left out the toupper conversion. I'll get that fixed.

**Comment by Roeshambo** [comment]
This is resolved in 2.0
