### ISSUE TITLE
separated player table

### ISSUE THREAD

**Issue by fifiand1** [Roeshambo/MonolithDKP#103]
Our guild have two raid groups: raid1,raid2. Seeking if there is a solution: raid1 dkp changes broadcast to raid1 officers only.

**Comment by Roeshambo** [comment]
There is no way to do this and ensure it's handled with any level of consistency. Only option would to only broadcast to raid, which would raise all kinds of new issues. Unfortunately, broadcasting scope is limited to very select options. You give players in your guild a rank that corresponds to their raid team, and then add just those ranks to your "Core Raider" list. Then just filter to that list on your raids.
