### ISSUE TITLE
Suggestion: last minute bids add time

### ISSUE THREAD

**Issue by ArgonautCaptain** [Roeshambo/MonolithDKP#104]
I am currently raid leader in a guild that utilizes your DKP addon and our officers have come to the consensus that we would like to request the option to make bids that come in within the last 10 seconds of the auction reset the timer to 10 seconds. This would allow more outbidding rather than everyone just fighting to get their bid in at the very last second. We've had several issues where, due to latency or human error, a raid member attempted to put in a bid with about 1 second left, but it did not hit chat in time to be recognized or would have a typo causing a similar problem. We've agreed that this feature would produce a more friendly bidding experience for guild members.  
Thank you in advance! We really appreciate the hard work you've put into this addon!

**Comment by Roeshambo** [comment]
It's already been written and implemented. It's coming in the next update as an "Anti Snipe" option. The update is just taking a bit longer to get right than I anticipated.
