### ISSUE TITLE
Only GM can edit dkp

### ISSUE THREAD

**Issue by Twinkle-Toesz** [Roeshambo/MonolithDKP#105]
After i installed addon as officer, i have edit dkp and all options enabled, but after restarting game i have only read(view) permissions until i delete MonolithDKP.lua. Even when i have options to edit it will say that im not whitelisted officer. Every officer in our guild have same problem, only GM can edit dkp. Where i can edit whitelist or disable it as GM ? (and yes i can edit officers note)

**Comment by Roeshambo** [comment]
Tell your GM to clear the Whitelist by selecting no one on the list and click "Set Whitelist". And make sure he broadcasts it while all officers are online. That or they can remove the "MonDKP_Whitelist" table at the bottom of the savedvariables file. There's a warning to avoid using it unless they know exactly how it works as it was kind of niche for select people. It's kinda hit or miss unless used properly. (ALL users and officers must have the whitelist data broadcasted to them or it won't work properly)

**Comment by Twinkle-Toesz** [comment]
Thanks, removed "MonDKP_Whitelist" table and is working now :)
