### ISSUE TITLE
Loot History Filter system

### ISSUE THREAD

**Issue by andovcr** [Roeshambo/MonolithDKP#109]
On the DKP History tab, the filter lets you sort by raiders alphabetically in chunks of 40.  This is great for very large DKP tables.  One the Loot History tab, there is no chunking system, just a very long list that cannot be scrolled through.  This means for larger guilds, there is no way to easily and consistently select players on that tab.  Could this Loot History tab be chunked out into groups of 40 like the DKP History tab?

![image](https://user-images.githubusercontent.com/58115742/69482195-b68f4e80-0ddd-11ea-9962-b5014d678741.png)

**Comment by Roeshambo** [comment]
All dropdown lists containing player names will be broken into groups of 20 in 2.0
