### ISSUE TITLE
Standby

### ISSUE THREAD

**Issue by krisis6** [Roeshambo/MonolithDKP#11]
Also is there a way standby list could be implemented, that would add to the raid so you could award the same way normally for the raid but it would also check the standby list and award those two as part of the raid.

So that could be done by getting on the standby list for the raid via a whisper 

and also removes them from the list once they go offline.

similar standby options to Alumian's standby setup on CEPEP
https://github.com/Alumian

**Comment by Roeshambo** [comment]
I'll put it on the list :)

**Comment by Roeshambo** [comment]
This has been added along with multiple "Views" of the DKP table. Including a "standby" view, "standby and raid" view to see them all in one window, as well as a "core raider" view that allows you to assign ranks as core leaders to allow you to auto invite all of them to raid at once. New version should be pushed this weekend provided I can get sufficient testing and bug tracking done.
