### ISSUE TITLE
Lifetime Spent calculation

### ISSUE THREAD

**Issue by andovcr** [Roeshambo/MonolithDKP#110]
When hovering over any player entry in the DKP Table, you can see their recent DKP History, the Lifetime Earned, and Lifetime Spent.  The Lifetime Earned value takes into account all reason codes, as long as the DKP value is positive.  The Lifetime Spent value only takes bid amounts into consideration.  It does not include any reason codes when the DKP value is negative.  This means that if there are adjustments made to a user, those DKP amounts will not show up in the Lifetime Spent value, and then that math loses its helpfulness to the raid.  Could this be changed to include all negative values associated with the raider, so that the Lifetime Earned - Lifetime Spent will equal the Total DKP value shown on the table?

![image](https://user-images.githubusercontent.com/58115742/69482260-81373080-0dde-11ea-8ace-b18704992c40.png)

**Comment by Roeshambo** [comment]
This will also be fixed in 2.0 when it's released as all numbers are recalculated at login/reload based off history.

**Comment by andovcr** [comment]
@Roeshambo is it possible to look at this one again?  The new version doesn't seem to take DKP amounts from Other into consideration.

![image](https://user-images.githubusercontent.com/58115742/70403440-6f6ba500-19fc-11ea-8067-66fa6f9cda91.png)

**Comment by Roeshambo** [comment]
Have you run the table validation? Right click on the DKP window and use "Validate Tables". Also please note that there is an automatic hidden entry created when you do the migration that is not accounted for in the lifetime gained. If all of your history entries did not add up to the DKP value the players actually had at the time, a new entry was created to compensate for it (this was assuming DKP tables were correct and history somehow got screwy).
