### ISSUE TITLE
Multiple DKP Broadcasts in close proximity

### ISSUE THREAD

**Issue by andovcr** [Roeshambo/MonolithDKP#112]
When multiple raid teams are using Monolith, they have to be extremely careful about broadcasting DKP updates in close proximity, lest they not actually push through.  Would it be possible to add a popup box (similar to how a popup box confirms that the Broadcast DKP Table function is complete) so that DKP Managers would have a strong and obvious visual cue of when it is okay to broadcast the next piece of loot or not?

**Comment by Roeshambo** [comment]
Version being released within the next few days will resolve this completely. You'll even be able to broadcast at the exact same second if you like. Just wait for 2.0
