### ISSUE TITLE
Question about the new migration

### ISSUE THREAD

**Issue by Warchas** [Roeshambo/MonolithDKP#113]
Since it was prior saved in the guildnote it wasnt an issue if I use two different computer and play with cause if I logon my gm character on Computer 1. and my tables are up to date and then we raid and it's updating etc. Then lets say I change computer and my tables are not up to date since it checked my GM Note I would request update from an other officer.

I am going to assume it saves the Up to date in savedvariables now if its no longer in the notes. So if I change computer how will it detect if my tables are up to date or not?

Raids on Comp 1. updates tables
Changes to Comp 2. logs on same character without updated tables. 

What happens?

Sincerely, 
Warchas

**Comment by Roeshambo** [comment]
When you request a sync with the guild, you receive everyone's information with what they have. You'll know you're out of date if anyone says they have information newer than you. If an officer is online that has that information, they'll send it to you

**Comment by Roeshambo** [comment]
To be more specific, you'll receive a table that tells you what indexes for each officer each player has. If anyone has a higher index than you, your table status icon will turn red and say "Missing Entries: OfficerA: 3". So you'll know you're missing 3 entries created by OfficerA. If that officer is not in your raid party, you pretty much don't have to worry about it. If he is, you just have to wait until that officer or another officer that has those entries logs in.

**Comment by DanSheps** [comment]
How are you tracking the highest index in the new version?

**Comment by Roeshambo** [comment]
Depends, which highest index? The individuals or the highest known in the guild? During the sync process, everyone broadcasts their meta table that tracks their current highest index for each officer. Each person also sees all other tables as they're broadcasted and determines who has the highest index. If it's higher than yours, that's stored locally for comparison. "Missing" indexes is essentially determined by taking that highest known minus your current highest for that officer. And then adds any errant indexes you find in your own tables (IE: You have Roeshambo-10 and Roeshambo-12, but 11 is missing)

**Comment by DanSheps** [comment]
Highest in guild, or is it tied to user like you demonstrated here (dansheps-10)

**Comment by Roeshambo** [comment]
You simply look at everyones meta tables. If someone has an index that is higher than you, you have an idea of what you're missing.
