### ISSUE TITLE
DKP Migration

### ISSUE THREAD

**Issue by Sorterx** [Roeshambo/MonolithDKP#115]
Hello, 

I just tried the dkp migration -> A window appears "Are you certain you wish to be the officer conducting the migration? This is a non-reversable process."
I press the "yes" button, but nothing happens.

Instructions unclear :P

Any advise on that?

Greets,
Patrick

**Comment by Sorterx** [comment]
Message: Interface\AddOns\MonolithDKP\Modules\Migration.lua:44: attempt to compare number with string
Time: Mon Nov 25 12:15:05 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\Modules\Migration.lua:44: attempt to compare number with string
Interface\AddOns\MonolithDKP\Modules\Migration.lua:44: in function `MigrateTables'
Interface\AddOns\MonolithDKP\Modules\Migration.lua:236: in function `OnAccept'
Interface\FrameXML\StaticPopup.lua:5003: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals: self = <table> {
 CurrentIndex_Set = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:784
 DKPHistory_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:261
 StartTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:497
 GetDKPSettings = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:351
 StartBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:696
 ValidateDKPTable_DKP = <function> defined @Interface\AddOns\MonolithDKP\Modules\Validate.lua:92
 PurgeDKPHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:381
 RaidTimerPopout = MonDKP_RaidTimerPopout {
 }
 SortLootTable = <function> defined @Interface\AddOns\MonolithDKP\Modules\LootHistory.lua:11
 ConfigTab3 = <unnamed> {
 }
 UIConfig = MonDKPConfig {
 }
 GetGuildRankGroup = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:246
 BroadcastTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:458
 ConfigTab6 = <unnamed> {
 }
 RequestSync = <function> defined @Interface\AddOns\MonolithDKP\Modules\comm.lua:193
 ClassGraph = <function> defined @Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:7
 BroadcastStopBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:620
 ValidateSender = <function> defined @Interface\AddOns\MonolithDKP\Modules\comm.lua:23
 CreateBidWindow = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:1057
 reset_prev_dkp = <function> defined @Interface\AddOns\MonolithDKP\Modules\ManageEntries.lua:253
 UpdateQuery = <function> defined @Interface\AddOns\MonolithDKP\Modules\comm.lua:251
 CheckOfficer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:218
 DKPHistory_Reset = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:48
 AdjustDKP = <function> defined @Interface\AddOns\MonolithDKP\Modules\AdjustDKP.lua:8
 Options = <function> defined @Interface\AddOns\MonolithDKP\Modules\Options.lua:59
 AdjustDKPTab_Create = <function> defined @Interface\AddOns\MonolithDKP\Modules\AdjustDKP.lua:205
 ConfigTab1 = <unnamed> {
 }
 AutoAward = <function> defined @Interface\AddOns\MonolithDKP\Modules\AutoAward.lua:6
 ChangeLogDisplay = MonDKP_ChangeLogDisplay {
 }
 ConfigMenuTabs = <function> defined @Interface\AddOns\MonolithDKP\ConfigMenuTabs.lua:115
 LootHistory_Reset = <function> defined @Interface\AddOns\MonolithDKP\Modules\LootHistory.lua:201
 DKPModes_Misc = <function> defined @Interface\AddOns\MonolithDKP\Modules\Modes\DKPModesMisc.lua:7
 DKPTable_Headers = MonDKPDKPTableHeaders {
 }
 DKPTable = MonDKPDisplayScrollFrame {
 }
 SetTabs = <function> defined @Interface\AddOns\MonolithDKP\ConfigMenuTabs.lua:80
 LootTable_Set = <function> defined @Interface\AddOns\MonolithDKP\Modules\BidInterface.lua:21
 SyncOfficers = <function> defined @Interface\AddOns\MonolithDKP\Modules\comm.lua:168
 StartRaidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\RaidTimer.lua:142
 BidInterface_Toggle = <function> defined @Interface\AddOns\MonolithDKP\Modules\BidInterface.lua:190
 OnInitialize = <function> defined @Interface\AddOns\MonolithDKP\init.lua:462
 AwardConfirm = <function> defined @Interface\AddOns\MonolithDKP\Modules\Award.lua:301
 Table_Search = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:823
 ConfigTab2 = <unnamed> {
 }
 ConfigTab4 = <unnamed> {
 }
 GetThemeColor = <function> defined @Interface\AddOns\MonolithDKP\Core

**Comment by Roeshambo** [comment]
That is unusual. It looks like you may have a string value in your table that is only supposed to have numeric values. Close your game and go to Modules\Migration.lua. On line 44, look for:

```
if MonDKP_Loot[i].cost > 0 then
	MonDKP_Loot[i].cost = MonDKP_Loot[i].cost * -1
end
```

Change it to:
```
if tonumber(MonDKP_Loot[i].cost) > 0 then
	MonDKP_Loot[i].cost = tonumber(MonDKP_Loot[i].cost) * -1
end
```

And run again.

**Comment by Sorterx** [comment]
Hello,

that worked. I migrated the tables.

But there are some informations in the table incorrect.

I have at least 10 players in the list with an impossible amount of "Lifetime" earned. 

Also, when i do "/dkp export", and check the file -> the view is broken for the dkp history.

**Comment by Roeshambo** [comment]
It may have duplicated entries because it got halfway through the migration and then migrated again. I would recommend reloading a backed up copy of the saved variables file and do the migration again.

**Comment by Sorterx** [comment]
Date: 2019-11-25 18:37:21
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\MonolithDKP\Modules\Validate.lua line 116:
   attempt to compare number with nil
Debug:
   [C]: ?
   MonolithDKP\Modules\Validate.lua:116: ValidateDKPTable_DKP()
   MonolithDKP\init.lua:562: OnInitialize()
   MonolithDKP\init.lua:179:
      MonolithDKP\init.lua:161
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  AtlasLootClassic, vv1.3.4
  AtlasLootClassicData, vv1.3.4
  AtlasLootClassicDungeonsAndRaids, vv1.3.4
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  Bartender4, v4.8.8
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v2.6.1
  ClassicAuraDurations, v
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.21
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DFontChatSizes, v3.4
  ElvUI, v1.16
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  Flexi, vFlexi 1.5
  GatherLite, v1.3.3-classic
  GuildRosterManager, v1.831
  HealBot, v1.13.2.10
  LeatrixPlus, v1.13.38
  MonolithDKP, v2.0.0
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_deDE v1.13.2.11302 <none>
  (ck=52c)

**Comment by Roeshambo** [comment]
That is after rolling back to a backed up saved variables file and migrating again?

**Comment by Sorterx** [comment]
I found out why the lifetime earned dkp where incorrect. At the beginning, of using this addon, we tested a little bit. I gave some players 100 dkp -> I corrected these values by giving a 100% dkp decay.

I deleted these old entries -> lifetime earned is correct.

I try to update my guild members, but sometimes the client crashes. 

Regarding the last postet error, I just ran the migration 1 time?

**Comment by Sorterx** [comment]
These old data I deleted, have been already broadcasted -> I deleted these 100 DKP changes but the change has not been transported.

Where is the place, where the new tables are saved?

**Comment by Sorterx** [comment]
The last thing I need for successfully making this migration, is to know where the new tables are saved.

Help pls

**Comment by Roeshambo** [comment]
They are saved in the saved variables file located at WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua

**Comment by Sorterx** [comment]
Okay I solved the migration, by providing all members the recent "monolithdkp.lua".

When I go online in the game I always get the error below -> After the migration I deleted the public note of the GM. Does this error appear, because of the missing note? Or is it an addon conflict?

Date: 2019-11-25 21:52:44
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\MonolithDKP\Modules\Validate.lua line 116:
   attempt to compare number with nil
Debug:
   [C]: ?
   MonolithDKP\Modules\Validate.lua:116: ValidateDKPTable_DKP()
   MonolithDKP\init.lua:564: OnInitialize()
   MonolithDKP\init.lua:179:
      MonolithDKP\init.lua:161
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.3
  AtlasLootClassic, vv1.3.4
  AtlasLootClassicData, vv1.3.4
  AtlasLootClassicDungeonsAndRaids, vv1.3.4
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  Bartender4, v4.8.8
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v2.6.1
  ClassicAuraDurations, v
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.21
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DFontChatSizes, v3.4
  ElvUI, v1.16
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  Flexi, vFlexi 1.5
  GatherLite, v1.3.3-classic
  GuildRosterManager, v1.831
  HealBot, v1.13.2.10
  LeatrixPlus, v1.13.38
  MonolithDKP, v2.0.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_deDE v1.13.2.11302 <none>
  (ck=52c)

**Comment by Roeshambo** [comment]
Nope. The validation, for whatever reason, is not reading your file properly. I'm guessing when your first migration crashed, it didn't complete an entry properly and you have an entry that doesn't have a "dkp" variable in one of the DKPHistory table entries. The best approach is to delete your saved variables file all together and use a backed up file from before the migration and either remigrate or stick with 1.6.2 until I can get all the kinks worked out of 2.0. I apologize for the inconvenience. It was stress tested at length at least 100 times by me in every scenario I could think of with zero issues.

**Comment by Sorterx** [comment]
Hello I made the migration again, but the same error afterwards -> I think that happens, because I deleted these old entries with 100 dkp and -100% decay? 

I upload you the monolithdkp.lua, before and after the migration. Maybe you can figure out why the validation is broke.



[MonolithDKPluas.zip](https://github.com/Roeshambo/MonolithDKP/files/3890547/MonolithDKPluas.zip)
[old.zip](https://github.com/Roeshambo/MonolithDKP/files/3890652/old.zip)

**Comment by Roeshambo** [comment]
I'll look at this later. I have a feeling something decided to write a dkp value in string form which can't be used in a math equation.

**Comment by Sorterx** [comment]
Thx for helping!

We already made a new raid using the 2.0.1. The only data that is complete, is running on the new version. In the backup files, before the migration, this last raid is missing.
I noticed and read your comments regarding the new version and that you retracted it. 

So it would be quite helpful if we can still use this version 2.0.1, till the moment you have fixed it completely. I would transmit the monolithdkp.lua to all members, after every coming raid. Is that possible? Or do I have to restore the old backups and try to restore the last raid data manually?

**Comment by Roeshambo** [comment]
If it's working for you, you certainly can keep using it. If you roll back to the backed up saved variables file and use the older version, you can simply broadcast that to everyone. But in 2.0.1, you should be able to broadcast normally for now.

**Comment by Sorterx** [comment]
I provided the same .lua to everyone, they have correct data. But when I come online the broadcast system overwrites some values. All lists are then incorrect, except mine.

Can you write me a short guide, how to insert the last raidinformations, that were logged with the 2.0.1 version, into my backup monolithdkp.lua. I will use your guide to manually update the .lua for the 1.6 version.

Greets,
Patrick

**Comment by Roeshambo** [comment]
Sorry, completely overlooked this. You can search for the MonDKP_DKPHistory table in the saved variables file. There you'll see all your past raids. That's the template. For each entry you create, you need to increment the index by 1 and increase the number in your MonDKP_Meta table under the "current" value to the highest value you create.
