### ISSUE TITLE
New version - all DKP values deleted

### ISSUE THREAD

**Issue by sugrobovp** [Roeshambo/MonolithDKP#116]
I have intalled new version - 2.0. And all of my DKP values are empty now. How can i restore DKP? Can my officer send me his old dkp table? And how to evade this problem in future

**Comment by Roeshambo** [comment]
If you're not an officer, it's supposed to delete everything. Your officers will send you the migrated tables.

**Comment by sugrobovp** [comment]
Im Guild Master

**Comment by Roeshambo** [comment]
Nothing should have been deleted for you then, unless someone else did the migration and you selected to wipe tables. Best option would be to restore a backed up saved variables file and use 1.6.2 until the kinks in 2.0 are worked out. Or another officer that still has 1.6 can broadcast those to you
