### ISSUE TITLE
DKP Bidding Window Errors

### ISSUE THREAD

**Issue by Milkymage** [Roeshambo/MonolithDKP#117]
Downloaded the new 2.0 update and migrated our dkp values over all went perfect.

Was doing a couple tests with the new DKP Bidding Window and everytime one of my raiders tries to bid we get the following errors check screenshot please. 

The person it is questioning is my class leader Lerto he is not an officer and doesn't have any officer rank permissions such as notes ect.

![unknown](https://user-images.githubusercontent.com/57876972/69541807-fb53ea80-0f81-11ea-9b40-89c9ccc83ae4.png)

**Comment by Roeshambo** [comment]
Do you have a bid in progress when they submit the bid in the bid window? I seemingly overlooked that message handling and will get it fixed. It should only accept the bid if there's a bid in progress. Otherwise it should ignore it entirely.

**Comment by Roeshambo** [comment]
Think I found the issue here. Minor oversight being the only person developing and testing it, I'm always one of the people hosting the bid.. 0_o.. It should be fixed in this next patch I put up shortly

**Comment by DanSheps** [comment]
> Minor oversight being the only person developing and testing it

Once this major release is stabilized I might be interested in helping out.

**Comment by Milkymage** [comment]
Thanks Roeshambo for you rapid reply.

These errors occurred whilst I was testing the new bidding window with a group of my guildies.
The errors wouldn't appear if they bid using the chat !bid [amount] it was only when using the new bidding window.

Also I couldn't seem to get the new Anti Snipe feature to save in settings everytime I set for example 10seconds extension and saved settings I would go back into /dkp window and it would reset back to 0seconds. I don't think I'll need to use this feature but just wanted to make you aware if there is an issue with it.

Thanks for all your hard work without this I'll be up 24 hours playing with spreadsheets!

**Comment by Roeshambo** [comment]
Someone has mentioned this and I'm not 100% certain yet why it isn't saving that information. Thank you. I'm doing everything I can to get all issues resolved as soon as possible.

**Comment by Roeshambo** [comment]
All issues noted here have been resolved in the beta version.
