### ISSUE TITLE
Major issues while migrating

### ISSUE THREAD

**Issue by Lycaria** [Roeshambo/MonolithDKP#118]
Hey, 

whenever we try migrating our tables from one of the officers (following your video-guide you uploaded a day ago) the whole game freezes after the loading screen).
We had some success migrating the tables to one of the officers but when another officer deleted his own tables to be able to get the migrated tables, every DKP-entry got mixed up for him and some auctions from the raids before were withdrawn multiple times, ending in a lot of negative entries.

I read there's a new version out there, we had the issues with 2.0.0. Is it already fixed in the new version?

Greetings

**Comment by Roeshambo** [comment]
If one officer did the migration and logged in after another did it, they may have mixed duplicate data.

**Comment by Lycaria** [comment]
We did the migration according to your guide and only one officer migrated his data. The other officers deleted their tables.
And it still doesn't explain the game crashing

**Comment by Roeshambo** [comment]
The game crashing appears to be an issue with a select few who have massive amounts of data (I was only able to test this with approx. 200 of each loot an dkp history entries). I'm looking into a means to correct this as soon as possible.

**Comment by Lycaria** [comment]
We don't really have massive amounts of data. There are just under 200 entries in our tables according to the stats it showed while migrating. We have 79 members in our list of participants.

**Comment by Roeshambo** [comment]
As soon as I get home today I'll be working on optimizations for it to get that issue corrected.

**Comment by Lycaria** [comment]
That'd be helpful, thank you for all of your work.

**Comment by Lycaria** [comment]
Just a little update from our side: 
For those officers, where Monolith doesn't end up crashing the game, the addon now deletes part of our members and their DKP while sychronizing the tables. 
Hope, it helps troubleshooting from your side. (:

**Comment by Warchas** [comment]
Crashes us as soon as we entered Onyxia's Lair.
I also noticed MASSIVE lagg while zoning from different zones
But whole game crashes as soon as we step into Ony with the addon active.

**Comment by Lycaria** [comment]
Yeah. Some of us can't even log in, while the addon is active because the game crashes instantly.

**Comment by DanSheps** [comment]
@Lycaria @Warchas It looks like @Roeshambo pulled the addon from Curse, I would recommend reverting for now

**Comment by Roeshambo** [comment]
I would recommend rolling your saved variables file back to it's pre migrated state and use 1.6.2 for now. There were a lot of unforseen issues despite 50+ hours on testing the system and doing the migration dozens of times. It will be put back up as soon as I'm confident this won't be an issue.

**Comment by Roeshambo** [comment]
2.0.3 Beta 2 is available here while it's being beta tested by a few guilds. It is not compatible with earlier 2.0 iterations. Planned release later this week.
