### ISSUE TITLE
Feature-suggestion: extend bidding automatically if players keep on bidding

### ISSUE THREAD

**Issue by Djfe** [Roeshambo/MonolithDKP#119]
My idea explained by an example:
time for auction(!bid to beplaced) 30 seconds, the time is extended by 15 seconds if there is a new !bid within the last 15 seconds of the auction. (default duration, and the other two time values can be customized in the settings then)
max. duration for an auction could be a possible variable, too. (0 = infinite)

it could also be done the other way around (inverse):
max. duration of auction: 2min
if there is no !bid for 15 seconds, close the auction automatically.

**Comment by Roeshambo** [comment]
This is already written and in the next version. With an exception on the auto close. That can be done manually at the auction holders discretion.

**Comment by Djfe** [comment]
very nice, thank you, we used it today :) (2.0.1)
love it, also love the new bidding window
