### ISSUE TITLE
Out of date 

### ISSUE THREAD

**Issue by Aegean89** [Roeshambo/MonolithDKP#12]
Hello :D
Me and a guildy tryed out the DKP addon on BFA, just to test it alittle.
We are getting Out of date etc and cant find a way to Update anything we have done.
Should there be only 1 person who runs it, with adding dkp, or can a Guild master and Officer do this in the same group??
Also Im guessing this is not ment for BFA so might be why this happend :P

**Comment by Roeshambo** [comment]
Is your out of date error with the addon? (it has the build number for classic so you check the "Load out of date AddOns" tickbox in the addons menu). If you're referring to your DKP tables being out of date, check the guild leaders Public Note. It must be blank to start (if there's something in it, you'll need to disable the addon before you can alter it.). The guild leaders public note is where officers store the time stamp when they update the tables so others know if they're out of date.

**Comment by Roeshambo** [comment]
And yes, anyone that has "Write to officer note" permission within the guild can alter information or submit new information (bids, dkp awards, etc)

**Comment by Aegean89** [comment]
it was the DKP status that said Out of date. happend after I used the Whitelist on that Officer.
in your YT vid you say that with whitelisting, the ones that are on the list will be able to bypass some stuff, but it says the opposite ingame. But Im just gonna leave that alone to be honest xD

**Comment by Aegean89** [comment]
also, the time stamp in the guild note that changed when you do something. its alot of numbers, what do they all mean?? like the one I have now: 1566347875. just so I know what it means when someone asks :)

**Comment by Roeshambo** [comment]
It's called an epoch timestamp. You can google "Epoch Timestamp converter" to see what date/time it is. It's basically just a stamp of when the last change/entry was made so others know if they do or do not have the most recent data. If you're not online when those changes occur you wouldn't have them. As far as the whitelist goes, It can only be applied to officers. It can't give permissions to someone that didn't have it before. it can only limit permissions from officers you don't want to have it. If you can turn on lua errors with /console scriptErrors 1. And if there are errors occurring with the whitelist please let me know.

**Comment by Aegean89** [comment]
ooh okay, so its abit more advanced time stamp hehe. We will only have 3 in the guild that have permission to guild, so not gonna mess with Whitelist then.
So the total DKP will show up in the guild notes, but only if they are online and have the addon??
watched your YT vid and you made it seem so easy, wich is prob is, so sorry for asking stupid questions, hehe

**Comment by Roeshambo** [comment]
Nope. Total DKP just shows up in the addon. No other notes are altered except for Guild Leaders public note with that timestamp. The addon simply uses Write to Officer Notes permission to validate a player as an "officer" in the addon. If someone doesn't have the addon, they can find out their dkp by whispering an officer that DOES have the addon with "!dkp" and you'll auto respond to them. Both of those whispers will be hidden from you though. So you won't get spammed.

**Comment by Roeshambo** [comment]
What I meant by online is lets say you have a raid. And you add a bunch of stuff to the tables through the course of the raid. If someone was offline, they wouldn't have received those updates. So when they login they'll have "out of date" tables. You'll have to broadcast the up to date tables to them (manage tab on the bottom) so they are then up to date.

**Comment by Aegean89** [comment]
ooh okay well that made it even easyer then to keep track :D 
So to be honest, only the leaders in a guild would need the addon. But thouse who have, will then see the total DKP window that shows what evryone has, so that they can see what a fellow Rogue have to bid with ?

**Comment by Roeshambo** [comment]
Correct. If a player has the addon and they are not an officer, the only tabs that will be available to them within the addon is Filters, Options, Loot History, and DKP History. And their "Options" tab will be dramatically reduced. This is what a non officer looks like with the addon:

![image](https://user-images.githubusercontent.com/6285297/63395143-5fb24d00-c388-11e9-98a6-00d1e294e934.png)

They get all the information they'll ever need. And can't alter any of the information. If they attempted to alter the addon to get that permission and then attempted to alter something like give themselves dkp, you would be notified that they did so when they attempt to broadcast it and it will block the broadcast. So it's definitely encouraged most or all have the addon just so they can see all that information in real time or review who got what loot etc. But yes, the only person that "needs" the addon is whoever will be hosting the auctions in raid.

**Comment by Aegean89** [comment]
this helped alot to clear away some stuff, thank you :)
This seem like a really good DKP addon you have made! cant wait to get into WoW Classic and use it :D
