### ISSUE TITLE
Could you perhaps provide some insight in how to fix the issues caused by the migration?

### ISSUE THREAD

**Issue by hansendevdk** [Roeshambo/MonolithDKP#120]
Hey man, thanks for a great addon. We were victims of the migration yesterday, even though only one officer migrated, and it seemed to work as planned until every officer started losing their whitelisted/officer status for the addon, and now no one has access anymore. We have all reverted to 1.6.3 and I have the database from yesterday. How do we proceed to make sure everyone gets the correct database, and why did we lose whitelist?

**Comment by Roeshambo** [comment]
Whitelist got wiped in the migration to avoid issues. The GM can rebroadcast the whitelist from his GUI to officers and then have those officers log off and back on. If you are back on 1.6.3 you can simply have an officer broadcast the tables and they should be all set.

**Comment by hansendevdk** [comment]
Thank you ^^ But we still have a persisting issue of some of the guild members(Like 5%) not being able to receive the broadcasts we send out. They got the same version we do, they are in our tables, but they don't recieve broadcasts. Any ideas?

**Comment by Roeshambo** [comment]
Have them delete their saved variables file entirely if they're ever encountering sync issues. Then push a broadcast to them. If your tables are somewhat large (100+ entries) it can often take a bit of time to push all of the tables out.

**Comment by Mukus91** [comment]
That helped for some people, but now another issue is that it's not auto-awarding DKP on some boss kills. Like it awarded on Lucifron, but not on the bosses after. It's very odd.
