### ISSUE TITLE
!dkp whispers

### ISSUE THREAD

**Issue by Milkymage** [Roeshambo/MonolithDKP#122]
Hey, 

Is there any way to stop all my officers whispering someone when a raider does the !dkp command.
Everytime someone wants to check he gets whispered from myself and like 4 other people.

Many thanks Roe !

**Comment by Roeshambo** [comment]
If they send the command to a specific officer in a whisper rather than in guild/raid only that officer will respond. No reliable/easy way to get the officers to talk to see who should respond unfortunately without putting an unnecessary load on the client.
