### ISSUE TITLE
2.0.1 Anti snipe feature not working

### ISSUE THREAD

**Issue by bradders39** [Roeshambo/MonolithDKP#124]
Hey there, 
                 I know it has been taken off curse forge at this moment but i have not had problems with 2.0.1 and have continued to use it with my guild. Seems to be all working fine, the only issue i have had is that the anti snipe feature wont add more time on to the bid no matter what i type in the selection for anti snipe. Just thought id point it out as i have not seen others having problems with it. I do not have any image of it as no error actually popped up just the bid timer did not extend. Sorry if this is a waste of your time since i cant provide any more information but thought it better to be mentioned than not mentioned :) 

Thanks very much for your hard work the addon is great and very useful for our guild!

**Comment by Roeshambo** [comment]
It seems there are some issues that are cascading to the DKP Modes window and it's not saving anything set. When you set a time for the anti snipe, and reload, does it revert back to 0?

**Comment by bradders39** [comment]
hey bud yes it changes back to 0 again after reload same with max bid :)

**Comment by Roeshambo** [comment]
Try hitting enter after you put in a value, then reload and tell me if it saved or reverted.

**Comment by bradders39** [comment]
Using enter the value stays in the input field, and i tested it and all seems to be working fine if i use enter after putting value in.

**Comment by Roeshambo** [comment]
Ok. I've modified it to accept values on keypress. Had it set to only save on enter
