### ISSUE TITLE
[1.6.3] Can't get boss kills to be auto awarded

### ISSUE THREAD

**Issue by c0mm0n** [Roeshambo/MonolithDKP#125]
Hey,

I can't get the boss auto DKP reward to work.
I tried as Raid Assistant first time, then was Raid Leader, but in both case nothing happens when a boss is killed. On time and raid end bonus work as intended. We have no interval DKP so i tried with 60 mins and 5 mins interval but still no boss auto DKP (btw if the interval DKP given is 0, maybe avoid creating a DKP record for 0)

I have indeed checked the options, where a 5 DKP value is granted for each boss kill.

Am I missing something ?

Great addon, thx

**Comment by Roeshambo** [comment]
The auto award for boss works separately from the raid timer. The raid timer only awards dkp when the intervals are met. If you have "Auto Award DKP" on, it auto awards the DKP set in the options tab as "Boss Kill Bonus" when you kill a raid encounter. And you must be raid leader to distribute the DKP. On the raid timer, "Interval" is how often to give time dkp set in the "Bonus" box next to it. So if you set an interval of 60 with a bonus of 5, you will award 5 DKP to the raid (and standby, if selected) every 60 minutes. That's the only function the raid timer serves.

**Comment by c0mm0n** [comment]
Ok got it, thx a lot.
