### ISSUE TITLE
Request: Option to turn off "Other" prefix for "other" awards.

### ISSUE THREAD

**Issue by Cephel** [Roeshambo/MonolithDKP#126]
In our guild, the built in award types are all pretty much not suited for our case. For example, we do multiple Onyxias per reset, we do multiple MCs per reset. So we want a way to differentiate the individual awards.

The "other" award type suits this, however it's pretty ugly that it's always prefixed with the word "Other".

Example: 
![image](https://user-images.githubusercontent.com/6716857/69903216-131eda80-1397-11ea-8c4c-fe4d1371bd64.png)

This just doesn't look clean. A simple way to fix this would be a checkbox to allow us to disable the "Other -" prefix for the award, allowing us to customize the award label entirely.

**Comment by Roeshambo** [comment]
Will handle that in the next version.

Line 292 in your DKPHistory.lua file.
Replace:
`reason = DKPHistory[i].reason;`
With:
```
if strfind(DKPHistory[i].reason, L["OTHER"].." - ") == 1 then
	reason = DKPHistory[i].reason:gsub(L["OTHER"].." -- ", "");
else
	reason = DKPHistory[i].reason
end
```

**Comment by Cephel** [comment]
This needs to be reopened, because of the 2.0 relaunch, this feature was undone somehow. @Roeshambo

**Comment by Roeshambo** [comment]
2.1.2 should still be hiding the "Other".
