### ISSUE TITLE
Cant start a bid in raid

### ISSUE THREAD

**Issue by joheri85** [Roeshambo/MonolithDKP#129]
If i start a bid while by myself it all works, but as soon as i am in a raid group i get a window saying:
"WARNING: Your DKP Modes settings have changed and can not run that until your UI is reloaded. Can we reload to complete that?".

Also this is printed in chat:
...nterface\Addons\MonolithDKP\Modules\BidInteface.lua:128 attempt to get length of value 'Bid_Submitted' (a nil value)

If i click yes and reload the same thing happens next time. If i manually reload, the same thing happens. As far as i can see all settings i have changed saves even if i restart the game. 

EDIT: Also when this happens the bid window closes automatically and nothing gets announced in raid chat.

**Comment by Roeshambo** [comment]
What DKP Modes settings are you using?

**Comment by joheri85** [comment]
![monolith_settings_misc](https://user-images.githubusercontent.com/58121029/69917268-788ccd00-1464-11ea-8f16-6d5a546d117c.png)
![monolith_settings_modes](https://user-images.githubusercontent.com/58121029/69917269-788ccd00-1464-11ea-8c51-28f2ddc9e987.png)

Also i noticed now that the value for "Anti snipe" does not seem to save when restarting the game, so maybe it has something to do with that?

**Comment by Roeshambo** [comment]
Thank you. Identified the problem. Soon as next version is out it'll be taken care of.
