### ISSUE TITLE
bidding window - two icons framed for bidding

### ISSUE THREAD

**Issue by Djfe** [Roeshambo/MonolithDKP#130]
We lootet two different pants with the same icon from Magmadar:
https://classic.wowhead.com/item=16822/nightslayer-pants
https://classic.wowhead.com/item=16835/cenarion-leggings

While Nightslayer Pants was being bid on, both pants icons were framed. (new bidding window)
The text was correct though, so no big problem arose :)

![](https://i.imgur.com/A99HRlK.png)
Version 2.0.1

**Comment by Roeshambo** [comment]
Just fixed this. Highlight will terminate when a bid is no longer in progress.

**Comment by Djfe** [comment]
I'm pretty sure, Nightslayer Pants was the first item that was bid on.
And the other one noone wanted (no bid)

**Comment by Roeshambo** [comment]
It'll remove all glow frames when either the timer runs out or when you hit end bidding. It's supposed to remove all glow frames when a new auction is opened but it appears to ignore it occasionally
