### ISSUE TITLE
bidding window - cache of the firelord/majordomo executus

### ISSUE THREAD

**Issue by Djfe** [Roeshambo/MonolithDKP#131]
The bidding window doesn't show icons of any loot of the cache of the firelord
https://classic.wowhead.com/object=179703/cache-of-the-firelord
it also doesn't show "Majordomo Executus" as the boss name (or the cache).

![](https://i.imgur.com/rB6jAp9.png)

also: it still showed the icon of the last loot item that wasn't up for bidding (just looted, I think)
Felheart Robes (https://classic.wowhead.com/item=16809/felheart-robes) dropped by Golemagg the Incinerator
Though I'm not sure whether this is a bug or not.

**Comment by Roeshambo** [comment]
I set the script to terminate if a loot slot is found empty during the loop (this is often caused by autoloot and caused errors). It appears that since the game doesn't consider currency an "item", it's seeing that in slot 1 and terminating. I'll get that fixed. ty

**Comment by Djfe** [comment]
wait that's the reason?
that's definitely different from what I expected :D

**Comment by Roeshambo** [comment]
If you loot the coin, then close the loot window, and reopen it, I'm betting it'll work.

**Comment by Milkymage** [comment]
I thought this new bidding window was a 2.0.0 version? I thought we were all back to 1.6 until issues had been fixed?

**Comment by Roeshambo** [comment]
Some people weren't having issues with 2.0. It appears to only have been really affecting very large guilds.

**Comment by Milkymage** [comment]
How is that even possible? My guild isn't massive but we had numerous bugs

**Comment by Roeshambo** [comment]
Please report them if you had them. I've fixed almost all of the one's I've received a report about so the new iteration of it should be out in a few days.

**Comment by Milkymage** [comment]
I reported all of ours Thanks

**Comment by Roeshambo** [comment]
Corrected in newest Beta version. Not compatible with 2.0.0 or 2.0.1. If you're on one of those 2 versions, recommended you wait until release later this week so we can get all the bugs out.
