### ISSUE TITLE
bidding window - auto close window x minutes after last bid closed

### ISSUE THREAD

**Issue by Djfe** [Roeshambo/MonolithDKP#132]
just a feature suggestion:
the new bidding window could close itself if there was no new bid for 1 minute (or if the last item from the loot list was just up for bidding)

If there is a new bid after that, then it will be opened again automatically anyway.

**Comment by Roeshambo** [comment]
Bid window will now auto close 2 seconds after an auction is closed unless a new auction is started within that window
