### ISSUE TITLE
/dkp help

### ISSUE THREAD

**Issue by Djfe** [Roeshambo/MonolithDKP#133]
The help command says, that /dkp bid is for officers only, which it isn't.
https://github.com/Roeshambo/MonolithDKP/blob/master/Localization/Localization.en.lua#L418

**Comment by Roeshambo** [comment]
Corrected in newest beta. This is not compatible with 2.0.0 or 2.0.1. Recommended to wait for release once the bugs are worked out if you are on one of those 2 versions.
