### ISSUE TITLE
Only accepting first bid

### ISSUE THREAD

**Issue by joheri85** [Roeshambo/MonolithDKP#134]
Since the 2.0.2 update bidding only seam to work for the very first bid on every auction. No matter who bids first.

EDIT: there is no error or anything, it just seems as the function that listens to the chat just stops working. (i use whispers only)

EDIT2: same thing in raidchat. if the first bidder cancels his bid it works for the next bid again. But as soon as there is one registerd bid it dont work no more

**Comment by Roeshambo** [comment]
For that bidder? Or any bidders? What DKP mode are you using?

**Comment by Roeshambo** [comment]
And are the bids submitted with the UI or !bid command?

**Comment by joheri85** [comment]
i have tried both the addon and the chat. same problem. I get the whispers but nothing happends as long as there is one active bid. if that bidder does "!bid cancel", anyone can place a bid since there is no "current bid". But ass soon ass another player bids no one else can after that unless he then cancels his bid.

![image](https://user-images.githubusercontent.com/58121029/70079949-ff2ce000-1605-11ea-8932-c71f03f30129.png)

![image](https://user-images.githubusercontent.com/58121029/70079968-0522c100-1606-11ea-8cdd-1d2c31f0fb3d.png)

**Comment by Roeshambo** [comment]
Ok I'll test this as soon as I get home. The subsequent bids are higher than the first correct? Since you have decline low bids on. Just making sure.

**Comment by joheri85** [comment]
i have tried with lower bids, bidding 0, bid the same, trying to raise my own bid (if i have the active bid). Nothing works besides "!bid cancel".

and also, thank you very much for all your work and effort. It is greatly appreciated!

**Comment by joheri85** [comment]
And higher bids ofc

**Comment by Roeshambo** [comment]
Thank you. 2.0.2 is first round beta so I expected some issues getting those testing it.

**Comment by joheri85** [comment]
oh yeah, and also. there is no reaction at all from the addon. even if i bid lower i dont get a "declined" message

**Comment by joheri85** [comment]
I also noticed now that nothing on the main "Options"-tab saves, so mabe it has something to do with that. DKP modes saves tho.

**Comment by Roeshambo** [comment]
Did you click the save settings button at the bottom?

**Comment by joheri85** [comment]
yes, i even get the "Defult settings saved" message in chat

**Comment by joheri85** [comment]
We are not using this live yet so i can delete any file if you want me to test something

**Comment by Roeshambo** [comment]
When i get a new beta ready fixing the identified issues it'll go up here as 2.0.3

**Comment by Roeshambo** [comment]
Ok I identified the issue. You can fix it yourself if you like.

In the Bidding.lua, line 163, you'll see:
```
else
    return
end
```
Delete the:
```
else
     return
```
Will have this in the next beta. My head must have been somewhere else when i put that in 0_o.

**Comment by joheri85** [comment]
oh yeah that worked indeed. 
Now its just the saving issue but i guess that is what you meant by "identified issues" above.

Thx for the fast response

**Comment by joheri85** [comment]
I checked the file in saved variables btw and it seems data is indeed saved. it appears that the options tab does not read the file.
File looks like this:
![image](https://user-images.githubusercontent.com/58121029/70087876-5e462100-1615-11ea-8b3a-38ed6c108b66.png)

but interface ingame still shows 70 in all slots:
![image](https://user-images.githubusercontent.com/58121029/70087909-74ec7800-1615-11ea-99fd-a0bfb49f7e75.png)

**Comment by Roeshambo** [comment]
Ok. I see why it's doing that. I'll have a new beta version up this afternoon fixing all known issues so far.

**Comment by Roeshambo** [comment]
All issues appear to be corrected and uploaded to Git here. Can download and disseminate as needed.
