### ISSUE TITLE
weird sync issue

### ISSUE THREAD

**Issue by dc1509** [Roeshambo/MonolithDKP#135]
Hey Roeshambo,

We have stay on 2.0.0 version since it didn't cause any issues to us.

Though recently one of our officers added a couple of entries and gone offline.

The GM wasn't online and once logged in he also made a couple of adjustments in the table.

This (most probably) caused the mentioned sync issue.

Me (as an officer) is unable to receive any data from GM or anyone else, clicking on the red button bring the dialog the GM has 6 entries to sync (it's in Russian so I'm not sure on the correct statement) but nothing happens, the sync finishes and we are all end up with the red button.

GM tried removing his database in order to get the latest DB from me (before the mentioned edits) but it doesn't sync anything. The message regarding "GM nickname has 6 entries to sync" stays forever.

Could you please help me to get my DKP database distributed across the guild?
How can we achieve that?

P.S. The guild officer note for the GM was set to "0" in an attempt to reset the sync but it didn't help or change anything. Now I don't remember how it should be set that my database would be considered the main one for syncing to everyone else (Just like the moment after migration)
it was probably set to something like {id=GM nickname} but I do not remember the exact syntax.
Anyway, let me know if there is a way to sync my database and if it has something to do with the correct officer note for the GM.

Thanks

EDIT: corrected the "GM nickname" that wasn't visible in a couple of places.

**Comment by Roeshambo** [comment]
The number of "Missing entries" doesn't reflect what is actually missing. It's a reference of compared data. So you likely have all entries if syncs were done with all related parties online (specifically, the individual it says the entries are missing from). There was most likely a mix up, somewhere, that caused your "known entries" table to get inflated. This should be resolved in the next version that we're beta testing at the moment and hopefully will be out later this week. If you compare actual DKP values for each player, I believe it should all still match up. Additionally, the officer note no longer has any bearing on the addon as it's not used for anything but the migration. Once all officers are migrated, you can use it normally.

**Comment by dc1509** [comment]
Can we join you guys for the test? We have 3 statics in the waiting state anyway :)

**Comment by Roeshambo** [comment]
Latest beta is up on Git here. Not compatible with earlier 2.0 versions.

**Comment by shershenator** [comment]
Just downloaded the beta and stuck in endless reloadui loop (MUSTRELOADUI)

**Comment by Roeshambo** [comment]
Are you an officer? There shouldn't be anything in there requiring you to reload. If you are getting that popup, it should be printing an error to your chat. Post that if possible.

**Comment by shershenator** [comment]
> Are you an officer? There shouldn't be anything in there requiring you to reload. If you are getting that popup, it should be printing an error to your chat. Post that if possible.

I am GM. It happens every time I try to show UI (/dkp). Error message: Monolithdkp.lua:51 : attempt to call method 'SendData' (a nil value)

**Comment by Roeshambo** [comment]
Were you using 2.0.0 or 2.0.1 before this?

**Comment by shershenator** [comment]
1.6.3 i suppose, definitely not 2.*

**Comment by Roeshambo** [comment]
And you did the migration?

**Comment by shershenator** [comment]
The data file is an old file I restored from backup after first version 2 failed, so no. This time i had no migrate button

**Comment by Roeshambo** [comment]
Use your most up to date saved variables file you used for 1.6.3 and migrate.

**Comment by Roeshambo** [comment]
And can you please post the saved variables file you were using from 2.0

**Comment by shershenator** [comment]
I have no idea how to migrate now, since the beta doesn't offer me anything. The most up to date file is a file from current (1.6) version, do you want me to post it?

**Comment by Roeshambo** [comment]
If you use a saved variables file from 1.6, you will get a migrate option at login. Make sure your game is closed when you put the file in place.

**Comment by Roeshambo** [comment]
I'd like to see the 2.0 version of the file if you have it.

**Comment by shershenator** [comment]
The are no option to migrate. I got a 'what's new' window and nothing else, so I don't have 2.0 version file. https://i.imgur.com/7WHFUfG.png

**Comment by Roeshambo** [comment]
Ok post what you have please

**Comment by Roeshambo** [comment]
Also, try using the /dkp migrate command. If it does nothing, then you're using a migrated file (2.0 version)

**Comment by shershenator** [comment]
Here
[MonolithDKP-.zip](https://github.com/Roeshambo/MonolithDKP/files/3925643/MonolithDKP-.zip)

**Comment by shershenator** [comment]
When I use /dkp command, i got an error and a reloadui message box :)

**Comment by Roeshambo** [comment]
Ok, that's definitely a 1.6 file. Make sure your GM public note doesn't have a tag in it with an officers name. IE: {MonDKP=OfficerName}. If it does, delete that and type /dkp migrate

**Comment by shershenator** [comment]
At first there was an old tag {MonDKP=12345...}, i deleted it, but nothing changed

**Comment by Roeshambo** [comment]
Oh wait... You're on a russian client.. Redownload the beta from here. I think I may have uploaded a copy that was missing some localization entries which would error you out. It's been since updated.

**Comment by shershenator** [comment]
From here? I downloaded the version you see on the screenshot from git few hours ago

**Comment by Roeshambo** [comment]
Ya. Download it again. Earlier today I uploaded some localization updates but only the English ones. If the Russian variables are missing, it would error you out. I've uploaded those since then.

**Comment by shershenator** [comment]
Unfortunately, that is not the case. Same error and no migrate button...

**Comment by Roeshambo** [comment]
In that lua file, Delete the whitelist table (MonDKP_Whitelist) and see if that changes anything

**Comment by Roeshambo** [comment]
Make sure your game is closed when you delete it.

**Comment by Roeshambo** [comment]
If that doesn't work, replace your init.lua file with the one I'm linking below. When you load into the game, turn on Lua errors with /console scriptErrors 1 and then reload your ui. Then use "/dkp test" command and if any errors pop up, link them here. Make sure to look at the bottom of the error wndow for an arrow, the first error, if there are multiple, tends to be the most important.


[init.zip](https://github.com/Roeshambo/MonolithDKP/files/3925785/init.zip)

**Comment by Roeshambo** [comment]
Actually scratch that... Give me 5 minutes and redownload the addon. I screwed up. Completely forgot I changed compression / encryption formats and didn't even upload the Lib files......

**Comment by Roeshambo** [comment]
Redownload the addon and make sure to restart your client to bring in the new files. You should be good now.

**Comment by dc1509** [comment]
The sync issue has been successfully resolved after installing the Beta 2.0.2

Thank you !

**Comment by shershenator** [comment]
> Redownload the addon and make sure to restart your client to bring in the new files. You should be good now.

It's seems to be working now, we'll test it today in our 2 raids. Thank you!

**Comment by Roeshambo** [comment]
@shershenator I would recommend you make sure to get syncing started early. When first implementing the add-on with a large list of entries already existing it can take a bit of time to get everyone on the same page. Especially with people logging in and out mid sync all the time

**Comment by shershenator** [comment]
Thank you. We did our raids today and everything seems to went ok.
