### ISSUE TITLE
Missing texture

### ISSUE THREAD

**Issue by joheri85** [Roeshambo/MonolithDKP#137]
![image](https://user-images.githubusercontent.com/58121029/70256606-07f9ef00-1789-11ea-9d59-5959af741144.png)

Speaks for itself i think =P

i did delete the whole addon folder and re-downloaded but the texture is still missing.

**Comment by Roeshambo** [comment]
Did you restart your client? Texture should be there.

**Comment by Roeshambo** [comment]
Download and try again. Honestly not sure how that texture may have been missing... Texture folder hasn't been touched for months here.

**Comment by joheri85** [comment]
i did several times, its been missing since first 2.0.2  commit

**Comment by Roeshambo** [comment]
Ya I just uploaded the texture a bit ago. Make sure you restart your client to load the new texture
