### ISSUE TITLE
Possible bug.

### ISSUE THREAD

**Issue by RobertHaworth** [Roeshambo/MonolithDKP#141]
The officers and guild leader in my guild are all having a similar issue and I think i have a theory as to why it is happening.

Bug Description: One of our members bid 265 DKP on Onslaught Girdle last night. We can see the correct loot history, but the 265 DKP is not correctly reflected as spent in the DKP Tables.

Theory for bug: We ended the raid either before or mid-bid so that everyone else could leave the raid yet still get their "end-of-raid" DKP.

Is the only way to fix this manually edit his DKP to get the -265DKP to be reflected properly?

Attached a screenshot of the Loot History and DKP table
![dkp_issue](https://user-images.githubusercontent.com/1219463/70293748-e445a180-17a6-11ea-9180-971c2fb3c06d.PNG)

**Comment by Roeshambo** [comment]
Unfortunately, that's likely what happened as the table hadn't finished broadcasting. I would recommend you manually edit their dkp in the saved variables file (search for ["player"] = "Collosus"). And then just rebroadcast it to the guild next time you raid. 2.0 will be releasing shortly which has an option to validate tables. Which rebuilds all player profiles based off of their loot and dkp history.
