### ISSUE TITLE
Request: "Add Raid Members" button to add Non-Guild members

### ISSUE THREAD

**Issue by XScorpion2** [Roeshambo/MonolithDKP#142]
Currently managing a cross guild raid, and would be nice to just click a single button to add all the folks, instead of hunt down who I am missing to add them individually.

**Comment by DanSheps** [comment]
This already exists.  It is in the Manage tab.

**Comment by XScorpion2** [comment]
"Add Raid Members" in the manage tab only works for Guild members in the raid. I want to add All members in the raid regardless of guild.

**Comment by XScorpion2** [comment]
Currently I've hacked this by inserting `InGuild = true;` right before Line 104 of ManageEntries.lua and using a a macro function with `/run AddRaidToDKPTable();`

**Comment by XScorpion2** [comment]
No longer need this function, we merged.
