### ISSUE TITLE
Bid window doesn't work properly, can't list slash commands

### ISSUE THREAD

**Issue by valeflare** [Roeshambo/MonolithDKP#144]
Hey there,
since yesterday night I am encountering bunch of those problems:

- Whenever is command "/dkp bid #item" exectuted there's response in chat saying "MonolithDKP: Opening Bid Window for: #item" but window won't pop up.

- If this command is executed without including variable(an item) there's same response however bid window opens. There I can drag whatever item I want, edit variables (boss name, set min DKP) and also start auction HOWEVER after pressing the pressing button "Start auction" there's like 50% chance it won't change to button "Stop Auction" so I am not able to stop the auction (except reloading or restarting the game) in another 50% of tries it does change .

- Last but not least is problem that occurs whenever command "/dkp ?" is executed. To be more certain "MonolithDKP: List of slash command:" is printed into chat but that's the beggining and also the end of the whole message - it lacks commands.

![Capture](https://user-images.githubusercontent.com/56998575/70326730-8318df00-1835-11ea-8e54-171dfd39435a.PNG)

Every other part of MDKP is working properly and as well as usual, including proper values of DKPs, proper operations when adding/removing DKPs (livetime values included). Any idea how to fix this kind of a problem ? I've already tried to reinstall MDKP, delete cache, delete WTF folder then starting game again so I got clear folder in which I placed .lua file but non of those worked.

Cheers !

**Comment by Roeshambo** [comment]
Turn on Lua errors and post any errors that pop up (/console scriptErrors 1). Make sure to look at the bottom of the error window. If there are more than 1 error, the first one to fire tends to be the most important one. And did your guild migrate your data and are using the beta or are you still on 1.6? I wonder if you've got a conflict with another addon or something.

**Comment by valeflare** [comment]
Well, we're still using the 1.6 version of the addon tho we migrated and then we rolledback thanks to many recoveries I got.
Anyway there's list of errors I got:

1. Rightaway when I log into the game

```
Message: Interface\AddOns\MonolithDKP\Core.lua:384: attempt to index field '?' (a nil value)
Time: Fri Dec  6 17:22:40 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\Core.lua:384: attempt to index field '?' (a nil value)
[C]: ?
Interface\AddOns\MonolithDKP\Core.lua:384: in function `Print'
Interface\AddOns\MonolithDKP\init.lua:215: in function 
Interface\AddOns\MonolithDKP\init.lua:213>
Locals: 
```
 
2. When I execute "/dkp ?"

```
Message: Interface\AddOns\MonolithDKP\Core.lua:384: attempt to index field '?' (a nil value)
Time: Fri Dec  6 17:24:52 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\Core.lua:384: attempt to index field '?' (a nil value)
[C]: ?
Interface\AddOns\MonolithDKP\Core.lua:384: in function `Print'
Interface\AddOns\MonolithDKP\init.lua:95: in function `help'
Interface\AddOns\MonolithDKP\init.lua:138: in function `?'
Interface\FrameXML\ChatFrame.lua:4609: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4270: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4306: in function <Interface\FrameXML\ChatFrame.lua:4302>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
Locals: 
```

3. When "/dkp bid #item" is executed

```
Message: Interface\AddOns\MonolithDKP\Core.lua:384: attempt to index field '?' (a nil value) 
Time: Fri Dec  6 17:26:06 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\Core.lua:384: attempt to index field '?' (a nil value)
[C]: ?
Interface\AddOns\MonolithDKP\Core.lua:384: in function `Print'
Interface\AddOns\MonolithDKP\init.lua:24: in function `?'
Interface\AddOns\MonolithDKP\init.lua:132: in function `?'
Interface\FrameXML\ChatFrame.lua:4609: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4270: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4306: in function <Interface\FrameXML\ChatFrame.lua:4302>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
Locals: 
```

4. When I execute "/dkp bid" and drag Item into the window , button works properly and I can't get error

**Comment by Roeshambo** [comment]
The error you receive when first logging in. Is that the only one received? Or is there a left button on the bottom of the error?

**Comment by valeflare** [comment]
That's the only one I recieve after logging in, I have to execute command to get another error.

**Comment by Roeshambo** [comment]
In game, type the following "/dump FCF_GetNumActiveChatFrames()" without the quotes, case sensitive. And tell me what it says

**Comment by valeflare** [comment]
```
Dump: value=FCF_GetNumActiveChatFrames()
[1]=8
```

**Comment by valeflare** [comment]
I tried to delete 1 window and it works as it should now so I guess that's the problem. So do I understand well that there's limitation of maximum noWindows for MDKP to work properly ?

**Comment by Roeshambo** [comment]
Yes. At least as it's written. I kinda wrote that part on the fly and it's completely changed in the new version. Also didn't anticipate anyone requiring that many chat frames lol. On line 376 of core.lua, you'll see an array with incrementing "ChatFrame"s. You can add more to the end of it (IE: ChatFrame10, ChatFrame11, ChatFrame12 etc) to accommodate more windows. The next version includes a dropdown to select what frames the addon messages are printed to.

**Comment by valeflare** [comment]
**Thank you** for your time and effort I really appreciate that, anyway goodluck with debugging MDKP v2.0
Cheers !
