### ISSUE TITLE
Please help!

### ISSUE THREAD

**Issue by juanmanuelduke** [Roeshambo/MonolithDKP#145]
Hello, we need help, after making a guild merge the addon is presenting us many errors regarding the synchronization, only the GM and three officers have permission to write in the public and offical note it would not detect some as oficers, some of the officers and the GM from the previous guild still get the option to manage DKP even though they don't have permission to write in the notes.
We have tried everything (I am talking about more than 10 people trying to fix it) reinstall, delete the files in the WTF, change the ranges of the guild, disable the permissions to write notes, everything. All other users do not get their tables updated, they still have the data from the previous guild.
We are all in version 1.6.3.
If you have any idea how to fix it, I would appreciate it very much.

**Comment by Roeshambo** [comment]
You'll have to restore from a backed up copy of your saved variables file. 1.6 didn't have protections against that yet unfortunately as I didn't anticipate it.

**Comment by Roeshambo** [comment]
What errors are occurring? If they don't have write to officer note permissions in the guild logging out and back in should correct that

**Comment by Roeshambo** [comment]
Another thing you can try, the old guild may have used a white list. Close your game and look for MonDKP_Whitelist in the saved variables file. If there are names in it, delete that table, log in and broadcast the whitelist to them (it should empty theirs).

**Comment by Roeshambo** [comment]
If this issue persists please reopen.
