### ISSUE TITLE
Lua error in v2.0.3 about srtsplit

### ISSUE THREAD

**Issue by XScorpion2** [Roeshambo/MonolithDKP#146]
Lines 1357 through 1359 of comm.lua:

```
				if curClass == "WARRIOR" then
					local a,b,c = strsplit("/")
					if strfind(message, "Protection") or tonumber(strsub(c, 1, -2)) > 15 then
```

strsplit("/") is not valid use of strsplit, fixed this by changing to code to match the "PALADIN" section:

```
				if curClass == "WARRIOR" then
					if strfind(message, "Protection") then
```

**Comment by Roeshambo** [comment]
Redownload. This has been fixed. Somehow I started writing that and forgot to finish? It'll work as you wrote it. The additional part simply recognizes fury/prot specs as tanks.
