### ISSUE TITLE
ALL DKP HAS DISAPPEARED AFTER UPDATE TO 2.0!

### ISSUE THREAD

**Issue by ddorfman77** [Roeshambo/MonolithDKP#147]
PLEASE HELP! I am the GM and just updated Monolith to 2.0 version and we lost ALL of our DKP. I tried to downgrade my addon to the previous version but everything is still gone.

**Comment by Roeshambo** [comment]
Did you already complete the migration when that occurred?

**Comment by tangiblethoughts** [comment]
Same issue here. Officers can see DKP but all members are seeing weird values like negatives, etc.

**Comment by Roeshambo** [comment]
Tell them to look at the status indicator on the bottom left. If they're seeing strange numbers then the sync likely hasn't completed. After migrating initially it takes time to get everyone sync'd up considering people are loggin in and off constantly.

**Comment by tangiblethoughts** [comment]
Indicator is green and there is no active sync in progress.

**Comment by tangiblethoughts** [comment]
All members are also seeing 0 entries in DKP history

**Comment by Roeshambo** [comment]
non-officers get automatically wiped when they have 2.0 so they can be resync'd by the officer that did the migration. If that officer didn't finish broadcasting to all officers then they are the only one that can sync everyone up.

**Comment by tangiblethoughts** [comment]
How does the officer who initiated the migration sync everyone up?

**Comment by Roeshambo** [comment]
When migrating to the new system, only one officer can execute the migration as per the instructions. Then that officer must be online to broadcast all entries to other officers. If they didn't allow all entries to broadcast before logging off, the other officers/members might only have a partial sync.

**Comment by tangiblethoughts** [comment]
Okay, by manually clicking the button. Will try that.

**Comment by tangiblethoughts** [comment]
The officer that initiated the migration was the first to update, then did the migration, then rest of guild updated. Just manually clicked sync but everyone's DKP is still missing from their end.

Officers can see the tables correctly, no one else can.

**Comment by tangiblethoughts** [comment]
Another thing to note, I noticed in the GM's Public note that from the last sync, it had a different MonolithDKP ID than what was in the officer note.

**Comment by Roeshambo** [comment]
The GM note is not used for anything other than the migration now. It's simply used to identify that an officer already conducted the migrations so two officers don't do it by accident. As far as other players syncing up, it often takes time when pushing that many different people. Have them reload their UI to force a reevaluation. But when everyone's doing it all at once, it can get screwy. It won't mess anything up, but if someone logs in/reloads mid sync, they won't receive anything until they're able to start a sync themselves. Eventually it resolves itself.

**Comment by tangiblethoughts** [comment]
Just screen shared with a member that had all the wrong DKP amounts in their table. They can actually still see the DKP History and Loot History but the numbers are completely wrong. Most people are negative.

**Comment by Roeshambo** [comment]
The sync sends entries one at a time. So their DKP reflects the accumulation of the entries that they do have so far. Hence why they're so wrong. Once they have all entries, it adds up properly.

**Comment by tangiblethoughts** [comment]
How long should it take do you think? It has been over 30 minutes and the indicator in the corner is green. We raid in 10 minutes just trying to figure out what we are going to do.

**Comment by Roeshambo** [comment]
Have one person log off and back in and wait. It'll request a sync as soon as it's done evaluating that they already have unless a sync was already requested. Several people reloading and relogging won't speed it up.

**Comment by tangiblethoughts** [comment]
Does every single officer need to delete their old tables as prompted? One of the officers is not online.

**Comment by tangiblethoughts** [comment]
There is no active sync and no numbers are being adjusted for any player

**Comment by tangiblethoughts** [comment]
Should there be an active sync?

**Comment by tangiblethoughts** [comment]
Has any guild successfully migrated?

**Comment by Roeshambo** [comment]
Every guild that has used it so far has migrated successfully. Worst case scenario, if any non-officers aren't receiving the entries properly, tell them to use the "Wipe Tables" button in the options and then request a sync.

**Comment by Roeshambo** [comment]
Their status indicator should turn red after a few seconds and the tooltip should show them what they're missing. That number will start to go down as they are receiving entries.

**Comment by Nhiosis** [comment]
2.0 looks great, we had a similar problem im sure it was user error. Sync showed duplicated officer names and some odd values, between very negative or super high. 

Would you recommend trying just with one officer online? It seemed no matter what i tried it duplicated the tables or something.

**Comment by tangiblethoughts** [comment]
Is there any option to revert? Our raid is about to start and 45 minutes after the migration all members have the incorrect tables and the officers that deleted their tables when prompted that the migration was complete, are now also seeing the incorrect tables. Only the person who initiated the migration currently has the correct tables. Should it take over an hour to sync? We've only been raiding for 4 weeks so it's not like we have a lot of history.

**Comment by Roeshambo** [comment]
The most conflicting factor in the sync is a ton of people logging in/reloading all in close proximity. Only one sync can occur at any given time and they can take 30-45 seconds to complete. If you reload or log in while one is occurring, you will not be part of that sync. Yes the initial migration can take time to get everyone on the same page. But once that initial front loading is completed everyone will stay accurate.

**Comment by Roeshambo** [comment]
@Nhiosis if you have duplicate entries, it sounds like more than one officer executed the migration against instruction. I would recommend having one officer roll back to a backed up version of their saved variables file (as they should have created per instruction) while all others wipe their tables. Then have that one officer do the migration. (you will need to delete the {MonDKP=OfficerName} tag from the guild leaders note)

**Comment by tangiblethoughts** [comment]
There's one thing that is odd though. The DKP is effectively off by 90 for everyone but 2 of our new members.

As I mentioned, after initially updating to 2.0, then reverting to 1.6.3, I noticed that in the Public Note there was a {MonDKP=#####) this # was different than the # in the Officer Note. Is there any chance that the missing 90 has to do with there being two different MonDKP IDs?

I just find it odd that the new members are not affected.

**Comment by Nhiosis** [comment]
Thanks! I (GM) rolled back to my backed up saved variable file and previous version of the addon. We'll try to proceed from here.

**Comment by Roeshambo** [comment]
No, the notes are completely irrelevant with 2.0. The only thing it does is identifies which officer did the migration. That note simply blocks the migration menu from popping up for any other officers to help prevent two people doing it. (two people doing the migration would be catastrophic). Have the players that are off by 90 to run a table validation (right click the DKP window and select Validate Tables). That can take a few minutes to run. But it'll make sure all DKP is reflective of the history.

**Comment by tangiblethoughts** [comment]
Hey Roeshambo. Sorry I'm sure you're busy. I noticed a couple other threads where people were having issues you asked for their Saved Variables file. Could I post mine for you to look at?

Everyone in my guild is still having the same issue with seeing strange & negative values in their table but they see all the dkp and loot history.

**Comment by tangiblethoughts** [comment]
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3935792/MonolithDKP.lua.txt)

**Comment by Roeshambo** [comment]
@tangiblethoughts do you have your premigration saved variables file still? I'm seeing duplicate indexes in that one.

**Comment by Roeshambo** [comment]
If you do, delete all indexes from the DKPHistory table and the Loot table. In the MonDKP_Loot table, delete ["index"] = Officer-#,   the whole line. There should only be player, loot, zone, date, cost and boss. In the MonDKP_DKPHistory table same thing, It should only have players, dkp, date and reason. Once you can do ctrl+f and not find any keys called "index", use that file to do the migration. That should fix your problem

**Comment by Roeshambo** [comment]
For example: 
```
{
		["player"] = "Fashionkilla",
		["loot"] = "|cffa335ee|Hitem:16806::::::::60:::::::|h[Felheart Belt]|h|r",
		["zone"] = "Molten Core",
		["date"] = 1574819216,
		["boss"] = "Gehennas",
		["cost"] = -11,
		["index"] = "Ghouldank-8",
}, -- [52]
```
Should be:
```
{
		["player"] = "Fashionkilla",
		["loot"] = "|cffa335ee|Hitem:16806::::::::60:::::::|h[Felheart Belt]|h|r",
		["zone"] = "Molten Core",
		["date"] = 1574819216,
		["boss"] = "Gehennas",
		["cost"] = -11,
}, -- [52]
```

**Comment by Roeshambo** [comment]
So it pretty much seems all issues so far, for the most part, are rooting in SV files that already went through the first migration and still have indexes from it. I feel better about it now. :p

**Comment by Roeshambo** [comment]
Additional note, have everyone wipe their tables so you can rebroadcast the new migrated file before you complete the migration. Button to do it is in the Options tab

**Comment by Roeshambo** [comment]
If this issue has not been resolved please reopen.

**Comment by tangiblethoughts** [comment]
@Roeshambo 

Hi, I do have my pre-migration file, but this file does not have any of the dkp or loot history from yesterday's raid. Can I just delete the index line from my current file and then have members sync off of that?

**Comment by Roeshambo** [comment]
You can manually add them to the file, just do so in order and increment the index by one on each. Then change your "current" index in the meta to the highest index you created. Each table has it's own index count. Loot and dkphistory

**Comment by Roeshambo** [comment]
If you're uncomfortable doing it just post both files and I can do it

**Comment by tangiblethoughts** [comment]
[PREMonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3937662/PREMonolithDKP.lua.txt)
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3937664/MonolithDKP.lua.txt)

**Comment by tangiblethoughts** [comment]
I tried going in but am a little nervous of making a mistake. If you could help that would be great. 

Once the file is fixed, do I need to complete the migration again? 

Do I do that within the current version or do I have to revert and they update again?

Do our members have to revert at all during this process?

**Comment by Roeshambo** [comment]
The 2nd file (not pre) has all of the correct data right? Just not migrated properly?

**Comment by tangiblethoughts** [comment]
That is correct to my knowledge. All my tables are working completely fine from this file

**Comment by Roeshambo** [comment]
This is the second file you listed above migrated properly. If any other officers have incorrect data, make sure they wipe their tables prior to logging in with this loaded as your SV file. 
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3937710/MonolithDKP.zip)

**Comment by tangiblethoughts** [comment]
Do I still need to delete all the index lines from the file you sent back to me as you previously instructed?

E.G.
["index"] = "Ghouldank-8",

**Comment by Roeshambo** [comment]
Nope. Use the file as is. It was migrated in your name.

**Comment by tangiblethoughts** [comment]
Thank you! Appreciate all your hard work man

<3 Ghouldank, Stalagg

**Comment by tangiblethoughts** [comment]
@Roeshambo I just put that file into my folder and the tables are now vastly different for all members and still incorrect. I see double entries for several items / dkp intervals.

**Comment by Roeshambo** [comment]
Can you reload and upload your new file. I have a feeling another officer may not have deleted their tables and sent you duplicate data.

**Comment by tangiblethoughts** [comment]
We actually seem to have resolved the issue. For some reason, duplicate entries were created by myself and another officer. We deleted the duplicate entries and the other officer wiped their tables. Now they are seeing the correct information. We are having the general guild try to resync now too.

**Comment by Roeshambo** [comment]
Ok. I just loaded up your SV file and didn't see any duplicate entries so pretty positive someone simply had old data that mixed with yours. Would probably be safest to simply have everyone wipe and use the file I sent as a clean start.
