### ISSUE TITLE
GM note deleted.

### ISSUE THREAD

**Issue by Nhiosis** [Roeshambo/MonolithDKP#148]
Any way to restore? I've searched comment sections but can't seem to find a method! Looking to update to 2.0 but GM note deleted.

**Comment by Roeshambo** [comment]
GM note is supposed to get deleted and updated with an officers name once they complete the migration. This note is exclusively to prevent multiple officers from doing the migration. Once all officers have gotten sync'd with the migrating officer, the note can be deleted and used as normal (the addon no longer uses any notes in game to manage timestamps)
