### ISSUE TITLE
DKP ? not working

### ISSUE THREAD

**Issue by IyaJenkei** [Roeshambo/MonolithDKP#152]
when i type /dkp ? its just makes some blank spaces. doesnt show any list of commands

**Comment by Roeshambo** [comment]
I'm guessing you're on 1.6 correct?

**Comment by IyaJenkei** [comment]
nope 2.0.3

**Comment by Roeshambo** [comment]
Turn on Lua errors with /console scriptErrors 1 and try to use it. Post errors if you get any. If there are multiple (left arrow on bottom) post the first one that occurred as well.

**Comment by IyaJenkei** [comment]
i got nothin

**Comment by Roeshambo** [comment]
relog and see if there are any errors when you login.

**Comment by Roeshambo** [comment]
Also check your Options tab to make sure you have a window selected in the drop down.

**Comment by IyaJenkei** [comment]
no errors on login. got it checked for all windows.

**Comment by IyaJenkei** [comment]
![image](https://user-images.githubusercontent.com/41968508/70384445-09bbe200-1944-11ea-8a2d-8d01c8616ddf.png)

**Comment by IyaJenkei** [comment]
the 2 empty spaces under the trade chat and above myra are what happens when i type /dkp ?

**Comment by Roeshambo** [comment]
And it doesn't print to any of the tabs?

**Comment by IyaJenkei** [comment]
nope

**Comment by Roeshambo** [comment]
Type the following into chat and post a screenshot of what it dumps:
`/script for i=1, NUM_CHAT_WINDOWS do local name = GetChatWindowInfo(i) print(name) end`

**Comment by IyaJenkei** [comment]
![image](https://user-images.githubusercontent.com/41968508/70384522-4e944880-1945-11ea-8ed3-d2fb09be8fc9.png)

**Comment by Roeshambo** [comment]
Did you run the command twice? Or did it print everything twice?

**Comment by IyaJenkei** [comment]
i did it twice to make sure

**Comment by Roeshambo** [comment]
And all 4 chat frames are checked on in the options tab?

**Comment by IyaJenkei** [comment]
yes

**Comment by Roeshambo** [comment]
That's spooky.... Can you take a pic of the options tab w/ that dropdown open?

**Comment by IyaJenkei** [comment]
![image](https://user-images.githubusercontent.com/41968508/70384609-d9297780-1946-11ea-9a11-4517c649676b.png)

**Comment by Roeshambo** [comment]
Ah, ya. Uncheck "Suppress Addon Notifications"

**Comment by Roeshambo** [comment]
I'll have to hide that dropdown if it's checked.

**Comment by IyaJenkei** [comment]
rofl. sorry

**Comment by Roeshambo** [comment]
No worries. I could probably remove that option entirely since you can suppress them simply by unchecking everything. :p
