### ISSUE TITLE
Reset everything?

### ISSUE THREAD

**Issue by joheri85** [Roeshambo/MonolithDKP#153]
What would be the correct way to start over?

I have been testing this in advance of going live. So now when 2.0 looks to be really great i just tried to delete the saved variable files and clear the {MonDKP=CharacterName} from GM note.
Im not sure if i need to do anything else.

First i tried to deleting the .lua file only but then it seems the .bak files is used, correct?
Also after i delete the GM note and restart nothing gets written back to the GM Note, shouldnt it?

Is there anything else that has to be done in order to "get a clean slate".

**Comment by Roeshambo** [comment]
You must close your client entirely before you can delete the SV file. It's not possible to delete it with the client open. And no, the GM note is no longer used within the addon. The only time it's used in 2.0 is to identify which officer has done the migration. Once all officers have the new data, it can be deleted.

**Comment by joheri85** [comment]
okay thank you
