### ISSUE TITLE
How to make it UP TO DATE

### ISSUE THREAD

**Issue by Boticka** [Roeshambo/MonolithDKP#154]
hello, we were in Molten Core and something went wrong in the last two bosses in Addon. Malenka and Sodastream won the item but the price did not drop from "lifetime_gained" and the DKP remained. We tried to fix it by canceling the prize but added a DKP to change it.

I played with the database, where I fixed everything, but the problem is that I cannot update the addon because I am not UP TO DATE

all dokuments [here](https://drive.google.com/drive/folders/14Mbj7Jj9fSVosfdijVYyuHgZgEvnb8O1?usp=sharing)

thx for help Botka

**Comment by Roeshambo** [comment]
If you have the most up to date information on your tables, then simply delete the GMs public note. If you don't have the most up to date information, then have someone that does broadcast to you.
