### ISSUE TITLE
Upgrade to 2.0.4 went wrong

### ISSUE THREAD

**Issue by oggez** [Roeshambo/MonolithDKP#156]
Hey, we updated to 2.0.4 today and the values are wrong. Tried resetting but nothing seems to work.

This is the file we used before migrate.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3937105/MonolithDKP.zip)

Can you help us out?

**Comment by Roeshambo** [comment]
By values you mean the players total DKP in the main window?

**Comment by Roeshambo** [comment]
Can you give me the post migration file as well please.

**Comment by oggez** [comment]
Yes it seems some raids are missing after migration (older ones), when we tried to reset and migrate again it seems we got double the values.

Heres the current one we have:
[currentMonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3937133/currentMonolithDKP.zip)

**Comment by Roeshambo** [comment]
Delete your current saved variables file with your client closed and replace it with the one below. Then when you login, delete the GM note (will say {MonDKP=OfficerName}) and tell all officers to wipe their tables (button in the Options tab). Then type /dkp migrate and migrate the new file.

**Comment by Roeshambo** [comment]
I've migrated the file for you. Please make sure all officers wipe their tables and replace your SV file with this one. Only do so after you're certain all officers have wiped their tables (button in Options tab)
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3937499/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
If this didn't resolve your issue please comment here and I'll reopen this. :)
