### ISSUE TITLE
GM Saved variables file

### ISSUE THREAD

**Issue by Mirthinvictus** [Roeshambo/MonolithDKP#157]
Thanks for taking a look github does not support posting lua files here so its .txt

[MonolithDKP.txt](https://github.com/Roeshambo/MonolithDKP/files/3937132/MonolithDKP.txt)

**Comment by Roeshambo** [comment]
Do you have a backup of the file before it was migrated?

**Comment by Mirthinvictus** [comment]
nope, I've got screenshots of current dkp values. if you can't fix this, what are the steps for a fresh reset for everyone. I can manually enter the 57 values. Shouldn't take me too long. Also thanks for the addon

**Comment by Roeshambo** [comment]
There are absolutely no loot entries in the table you provided. Is that how it's supposed to be?

**Comment by Roeshambo** [comment]
You can start fresh by having all officers use the "Wipe Tables" button in the options, including yourself. Then have all other members wipe their tables.

**Comment by Mirthinvictus** [comment]
Yes, we don't use the !bid system for to avoid conflict of interest and offspec bids. I'd LOVE to be able to save custom reasons for distributing DKP in the drop down menu though.

**Comment by Roeshambo** [comment]
Ok Have all of your officers wipe their tables and you log off and close your client. I'm going to migrate your DB manually and you just put it in place of your current file (back it up just in case). Then when you login, you should begin pushing them out to the other officers.

**Comment by Mirthinvictus** [comment]
Thanks for all the help

**Comment by Roeshambo** [comment]
Ok. First and foremost, make sure all officers have wiped their tables and currently have no data. Then replace your saved variables file with this one (remove .txt from the end. Your client must also be completely closed before you can replace it) and launch your game. Shortly after login you should begin the sync process.
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3937234/MonolithDKP.lua.txt)

**Comment by Roeshambo** [comment]
All other non-officers must also wipe all of their tables. But they aren't a threat to contaminating your file because only officers can broadcast.

**Comment by Mirthinvictus** [comment]
you should get paid for this ;) i'll let you know how it goes, my officers are filtering in.

**Comment by Roeshambo** [comment]
> I'd LOVE to be able to save custom reasons for distributing DKP in the drop down menu though.

There is an "Other" option in the DKP adjust menu to give custom reasons.

**Comment by Mirthinvictus** [comment]
I use it all the time man. Arcanite Bar donations, flask donations. Loot distribution. It's a simple thing, but I type "Bar x (X), Flask x (x), or Loot every time I do something. I use boss kill, and on time dkp option frequently too though. The only reason I don't use the !bid option is that it would be unfair to see my classes gear bids.

**Comment by Roeshambo** [comment]
Ah, well in those circumstances I either have another officer do the auction or I close the bid window entirely and only open it back up after bidding is completed.

**Comment by Roeshambo** [comment]
If you continue to have issues with this please reopen the ticket and let me know.

**Comment by Mirthinvictus** [comment]
I've done what you asked. Had my officers delete there .lua files. and reinstall MonolithDKP. Got my DKP table back, but the situation has flipped. I don't have missing entries, but I have 2 missing entries for both officers. We've redone this process multiple times being diligent to wipe every last bit of MonoDKP off their PCs. Officer 1 missing entries 2 Officer 2 missing entries 2. When before it was myself Missing a ton of entries.

We're going to Excel until I can sort this out.

Thank you so much for your time. I dropped you a 20 earlier for your hard work today. I can see you been putting out fire.

**Comment by Roeshambo** [comment]
If you loaded that file I gave you, had all officers wipe their tables and it said you were missing entries, it was most likely because another player in the guild thought you were. You would have had all of the entries. Doesn't mean anything was actually missing. When syncing, all players send you what they currently have of yours. So lets say you start a sync and you have 300 entries in the DKP table. But I have the old information and mine says you have 305 entries made by you. I send you a message back saying "i have 5 entries here that you don't.. so you're missing some". It doesn't actually change what data you do have. The best way to get that cleared up is to have those players with old data wipe their tables and rebroadcast to them (it wouldn't hurt to delete the MonDKP_Meta_Remote table in your SV file as well)

**Comment by Roeshambo** [comment]
@Mirthinvictus

**Comment by Roeshambo** [comment]
If I remember correctly, your SV file had "test" entries created by other officers. When I migrated, those entries became yours. That's most likely why it says they have missing entries from other players.

**Comment by Mirthinvictus** [comment]
Thanks for the info man! I'll pass this along. You've been more than helpful!

**Comment by Roeshambo** [comment]
For the most part, the issue should correct itself as there are several steps in the sync process that corrects people with incorrect remote data. Problem is, if there are multiple officers online, the players pick at random whom to request from. So if those officers that it says you're missing entries from started a sync, they should fix your remote variables.
