### ISSUE TITLE
Updated and my dkp is out of sync

### ISSUE THREAD

**Issue by Mixxcorpserun** [Roeshambo/MonolithDKP#159]
I am an officer in my guild, and it seems everyone's dkp is correct and all well. Except my tables are totally empty. It says i am out of sync and no officers can sync me. I dont even get broadcast notifications. Also, if i update from wowinterface i get another update from the twitch client?

**Comment by Roeshambo** [comment]
They likely still have 1.6 and have not migrated to 2.0 yet. The two versions are not compatible as they use completely different systems. One officer must update to 2.0 and execute the migration process before they can begin distributing that new data to the other officers.

**Comment by Mixxcorpserun** [comment]
I believe they all updated the addon last night/this morning. It seems like i am the onlyone with this issue. Could it be related to me logging on my alt (who is not an officer tag) before my main this morning?

**Comment by Roeshambo** [comment]
Nope. Shouldn't have any bearing on what you receive. Please post your saved variables file. Also, when you mouse over the status indicator what does the tooltip say?

**Comment by Mixxcorpserun** [comment]
It says Your tables are currently empty. Click to initiate a sync request. This will also pul lspec and role information from all online players. But if I click it, it says no officers are online or recently online to update it. I deleted my saved variables file just before because I tried to uninstall/reinstall totally because I seem to be the only one in my guild with this issue.

**Comment by Roeshambo** [comment]
Sounds like either no officers are online or you just have to try to sync again after a few minutes. There is a 60 second cooldown on syncs to help reduce unnecessary traffic.

**Comment by Mixxcorpserun** [comment]
I had 3 different officers online. All tried to broadcast ect.  Maybe i need the guild leader online?

**Comment by Roeshambo** [comment]
Please post your saved variables file.

**Comment by Mixxcorpserun** [comment]
MonDKP_DB = {
	["MinBidBySlot"] = {
		["Other"] = 10,
		["OneHanded"] = 10,
		["Bracers"] = 10,
		["Legs"] = 10,
		["Belt"] = 10,
		["Hands"] = 10,
		["Boots"] = 10,
		["Ring"] = 10,
		["Cloak"] = 10,
		["Head"] = 10,
		["Trinket"] = 10,
		["Chest"] = 10,
		["OffHand"] = 10,
		["Range"] = 10,
		["Neck"] = 10,
		["Shoulders"] = 10,
		["TwoHanded"] = 10,
	},
	["raiders"] = {
	},
	["defaults"] = {
		["HistoryLimit"] = 2500,
		["AutoOpenBid"] = true,
		["MonDKPScaleSize"] = 1,
		["BidTimerSize"] = 1,
		["DKPHistoryLimit"] = 2500,
		["HideChangeLogs"] = 0,
		["SupressTells"] = true,
		["ChatFrames"] = {
			["General"] = true,
			["Combat Log"] = true,
		},
		["supressNotifications"] = false,
		["TooltipHistoryCount"] = 15,
		["CurrentGuild"] = {
			["Mixx"] = "Corpse Run",
		},
	},
	["DKPBonus"] = {
		["IncStandby"] = true,
		["IntervalBonus"] = 2.5,
		["CompletionBonus"] = 0,
		["OnTimeBonus"] = 5,
		["UnexcusedAbsence"] = 0,
		["NewBossKillBonus"] = 0,
		["BossKillBonus"] = 10,
		["BidTimer"] = 60,
		["DecayPercentage"] = 20,
		["GiveRaidStart"] = false,
	},
	["bossargs"] = {
		["CurrentRaidZone"] = "Onyxia's Lair",
		["LastKilledBoss"] = "Onyxia",
		["RecentZones"] = {
			"Badlands", -- [1]
			"Searing Gorge", -- [2]
			"Blackrock Mountain", -- [3]
			"Orgrimmar", -- [4]
			"Dustwallow Marsh", -- [5]
			"Durotar", -- [6]
			"The Barrens", -- [7]
			"The Hinterlands", -- [8]
			"Arathi Highlands", -- [9]
			"Wetlands", -- [10]
			"Loch Modan", -- [11]
			"Burning Steppes", -- [12]
			"Eastern Plaguelands", -- [13]
			"Onyxia's Lair", -- [14]
			"Silithus", -- [15]
		},
		["LastKilledNPC"] = {
			"Anvilrage Warden", -- [1]
			"Flamekin Torcher", -- [2]
			"Deathlash Scorpid", -- [3]
			"Flamekin Rager", -- [4]
			"Dark Iron Slaver", -- [5]
			"Frenzied Plaguehound", -- [6]
			"Noxious Plaguebat", -- [7]
			"Carrion Grub", -- [8]
			"Hate Shrieker", -- [9]
			"Darrowshire Defender", -- [10]
			"Onyxia", -- [11]
			"Onyxian Whelp", -- [12]
			"Onyxian Warder", -- [13]
			"Firemane Scalebane", -- [14]
			"Firemane Flamecaller", -- [15]
		},
	},
	["timerpos"] = {
		["y"] = -20.4443950653076,
		["x"] = -315.556213378906,
		["point"] = "CENTER",
		["relativePoint"] = "CENTER",
	},
	["modes"] = {
		["ZeroSumBidType"] = "Static",
		["channels"] = {
			["raid"] = false,
			["whisper"] = false,
			["guild"] = true,
		},
		["StandbyOptIn"] = true,
		["Inflation"] = 0,
		["rounding"] = 2,
		["ZeroSumBank"] = {
			["balance"] = 0,
		},
		["mode"] = "Minimum Bid Values",
		["rolls"] = {
			["min"] = 1,
			["AddToMax"] = 0,
			["max"] = 100,
			["UsePerc"] = false,
		},
		["MaximumBid"] = 0,
		["CostSelection"] = "First Bidder",
		["increment"] = 15,
		["AutoAward"] = true,
		["AddToNegative"] = false,
		["SubZeroBidding"] = false,
		["costvalue"] = "Integer",
		["AntiSnipe"] = 0,
		["AllowNegativeBidders"] = false,
	},
}
MonDKP_Loot = {
}
MonDKP_DKPTable = {
}
MonDKP_DKPHistory = {
}
MonDKP_MinBids = {
	{
		["item"] = "Head of Onyxia",
		["minbid"] = 10,
	}, -- [1]
	{
		["item"] = "Eskhandar's Collar",
		["minbid"] = 10,
	}, -- [2]
	{
		["item"] = "Netherwind Crown",
		["minbid"] = 10,
	}, -- [3]
}
MonDKP_Whitelist = {
}
MonDKP_Standby = {
}
MonDKP_Meta = {
	["Loot"] = {
		["Mixx"] = {
			["current"] = 0,
			["lowest"] = 0,
		},
	},
	["DKP"] = {
		["Mixx"] = {
			["current"] = 0,
			["lowest"] = 0,
		},
	},
}
MonDKP_Meta_Remote = {
	["Loot"] = {
	},
	["DKP"] = {
	},
}
MonDKP_Archive = {
}
MonDKP_Archive_Meta = {
	["Loot"] = {
	},
	["DKP"] = {
	},
}
MonDKP_Errant = {
}

**Comment by Roeshambo** [comment]
Doesn't seem like you have anything there that would block a sync. I would wait until the individual that conducted the migration logs in and have them start a sync. If it still doesn't work, let me know.

**Comment by Mixxcorpserun** [comment]
I’m out now but will check later. Thank you! By the way, I’m talking to the other officers in discord and it seems nobody did a migration. But how are they seemingly ok but I’m not? That’s why I’m confused. If we messed something up or not haha

**Comment by Roeshambo** [comment]
Someone has to do the migration. The old table is not compatible with the new version. Also if they are officers, they would have been prompted with a window at login to do the migration or it would say who already did it.

**Comment by Mixxcorpserun** [comment]
I think i know what happened. i think somehow i was the only one to update. I am looking into finding out if anyone else did. How do i go about migrating if thats what it is? are instructions listed somewhere? Thanks again

**Comment by Roeshambo** [comment]
You have to be an officer to do the migration, a window would pop up at login with instructions. Only one person in the guild can do the migration and then feed those entries out to everyone else.

**Comment by Mixxcorpserun** [comment]
so i already updated and I dont see the migration instructions. Is there a way to revert to 1.6.3?

**Comment by Roeshambo** [comment]
You can download 1.6.3 again but you'll need an officer to broadcast the tables back to you.

**Comment by Mixxcorpserun** [comment]
kk thank you!

**Comment by Mixxcorpserun** [comment]
i imagine we have to update right? my guild is debating staying at the 1.6.3 version but my argument is that we should all migrate for future patches, new raids, ect.

**Comment by Roeshambo** [comment]
All future features additions will be to 2.0. if 1.6 is sufficient then by all means.

**Comment by Roeshambo** [comment]
If they are reluctant to switch due to the migration issues and they aren't confident they can execute it successfully, have them post the SV file that requires migration and I can do it for them. Then all they have to do is have all other officers wipe their tables and it'll distribute.

**Comment by Mixxcorpserun** [comment]
Perfect. I will talk to them today. I was going to watch the instruction video later. Thank you for all the help!

**Comment by Roeshambo** [comment]
The migration works properly. The only hang up is there were a few guilds that had migrated to 2.0 last month and it got their tables all mixed up. So I've been manually migrating it for them and reindexing everything since it was a problem I technically created on accident.

**Comment by Mixxcorpserun** [comment]
Hey there. Had an issue where certain officers (If raid lead) don’t auto give dkp. But we have one that does. Any idea why? I couldn’t find any settings.

**Comment by Roeshambo** [comment]
The setting for it is in the dkp modes window (/dkp modes), Misc tab. You can broadcast the settings after you change them and the officer it wasn't turned on for likely wasn't online to receive the broadcast, if one was made.
