### ISSUE TITLE
Feature: Export to CSV

### ISSUE THREAD

**Issue by b4ugh** [Roeshambo/MonolithDKP#16]
Not a bug or an issue, but an idea - would exporting to CSV be something possible?  Exporting to HTML is nice but uploading un-styled HTML to a page is not pretty and creates complexities when attempting to custom-style the HTML.  Exporting to CSV allows devs to import the CSV and can do whatever they want with the data / how they want to structure the HTML / etc. 

I'd love to help out with this but I've never created a wow addon before and do not know how to code in LUA.  But I'd be happy to test / debug / troubleshoot.  Thank you!

**Comment by Roeshambo** [comment]
Get the newest version released this morning (v1.4.0). It has CSV, as well as XML, as an option. At the top of each table it tells you which value is which field.

**Comment by Roeshambo** [comment]
.
