### ISSUE TITLE
Missing entries after migration to 2.0.4

### ISSUE THREAD

**Issue by Durza1985** [Roeshambo/MonolithDKP#160]
I am also having missing entries. I am GM and did the migration. I already did the migration a few weeks ago when 2.0 first was released and then rolled back to 1.6.

I have no file before the migration saved, sorry

**Comment by Durza1985** [comment]
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3937220/MonolithDKP.lua.txt)

**Comment by Roeshambo** [comment]
That's an addon file. I'll need your saved variables file located at WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua

**Comment by Durza1985** [comment]
Ok sorry, this should be the right one: 

[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3937248/MonolithDKP.lua.txt)

**Comment by Roeshambo** [comment]
What is your characters name?

**Comment by Durza1985** [comment]
Schelm

**Comment by Roeshambo** [comment]
Also, you've got literally thousands of entries giving 0 DKP. Are those entries required?

**Comment by Roeshambo** [comment]
Here is your corrected Saved Variables file. Ensure all officers wipe their tables prior to you logging in with this. Other players can wipe it later, but the most important part is having ALL officers wipe prior to using it. If another officer with your original entries logs in, they will send them to you and screw your file up. 
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3937417/MonolithDKP.zip)

**Comment by Durza1985** [comment]
Thank you. Will try it later after work and close the issue if it works.

The 0 DKP entries are not required and were produced due to some issue with the raid timer we had one time.

**Comment by Roeshambo** [comment]
I cleared up most of them for you. You went from around 2,600 entries down to about 300.

**Comment by Durza1985** [comment]
Thank you, great job!
