### ISSUE TITLE
Missing enteries, DKP history out of date, all DKP is wrong

### ISSUE THREAD

**Issue by Menura-Uv** [Roeshambo/MonolithDKP#162]
Hi, 

We just updated to v.2.0.4 and i'm missing a lot of enteries after the migration, as soon as my officers started updating to v.2.0.4 the DKP table went from being correct to being complitely wrong.

So right now all of my members DKP is nothing like it was, i exported everything to XML before doing the migration.

Is there a way to reset the table so it shows the right amount of DKP, history and loot? 

We're having issues with syncing as well... 

This is my current saved variables.. i dont have the ones before the migrations..

Hope you can help thanks!

[MonolithDKP.lua.bak.zip](https://github.com/Roeshambo/MonolithDKP/files/3937301/MonolithDKP.lua.bak.zip)

**Comment by Roeshambo** [comment]
That file is more or less empty (only 2 DKP entires and zero loot entries). Do you have a copy of it prior to you migrating it?

**Comment by Menura-Uv** [comment]
I don’t have a copy of the saved variables prior to migrating, although I exported, DKP history and loot history to XML.

Could that help?

**Comment by Roeshambo** [comment]
I may be able to rebuild it from that if it's not absurdly long 0_o.

**Comment by Menura-Uv** [comment]
I had one of my members and officers send me their MonolithDKP.lua file, they should have the enteries and history. This might be more helpful? 

[MonolithDKP praliz.zip](https://github.com/Roeshambo/MonolithDKP/files/3938352/MonolithDKP.praliz.zip)

[MonolithDKP Ganner.zip](https://github.com/Roeshambo/MonolithDKP/files/3938354/MonolithDKP.Ganner.zip)

**Comment by Roeshambo** [comment]
Yes that'll work. Give me a minute

**Comment by Roeshambo** [comment]
Are you an officer? Or what officers name should I use? The indexes must be in an officers name.

**Comment by Menura-Uv** [comment]
Ganner is an officer, I'm a GM (Menura), Praliz is a member

**Comment by Roeshambo** [comment]
Ok this is the migrated file. Have all other players wipe their tables (button in Options tab to do so). But most importantly, have your Officers wipe their tables. Then close your client, replace the saved variables file with this, and log in. If the others wiped their tables they'll start receiving data. If any officers fail to wipe their tables and they have entries from a failed migration, it'll mix with yours.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3938446/MonolithDKP.zip)

**Comment by Menura-Uv** [comment]
It seems to have worked, thank you so much for your help! 

Really appreciatethe the work you do with the Addon! :)

**Comment by Roeshambo** [comment]
No problem. Good luck.
