### ISSUE TITLE
Missing entries : Gambit 41 &different dkp to others after migration

### ISSUE THREAD

**Issue by lykann1337** [Roeshambo/MonolithDKP#163]
Hi
I have recently updated and then migrated to the new 2.0.4 update via twitch for MonolithDKP and have been experiencing some issues!
Followed the instructions on twitch to the letter and I am missing 41 entries on myself

Although I still have data in my table as do the rest of my guild some of the data is different between a few of my officers
I'd like to note that I am the officer who deals with all things related to dkp and with this addon in our guild and my tables were/are the ''master tables''
I will link a copy of my of my MonolithDKP.lua and also a lua error I have experienced in game when specifically looking at dkp history from Lealie (another officer in my guild)

[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3937310/MonolithDKP.zip)

also heres the Lua error I got on wow

Message: Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:313: bad argument #2 to 'strsplit' (string expected, got nil)
Time: Sun Dec  8 23:20:48 2019
Count: 3
Stack: Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:313: bad argument #2 to 'strsplit' (string expected, got nil)
[C]: in function `strsplit'
Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:313: in function <Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:303>

Locals: (*temporary) = "-"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Roeshambo** [comment]
Have all of your officers wipe their tables and reload their UI. I'm remigrating the file properly and will upload it here. You'll close your client and replace your current saved variables file with that (not the .bak file). When you log in you'll broadcast those new entries to the officers. Make sure they have all wiped their tables prior.

**Comment by Roeshambo** [comment]
Make sure all officers have wiped their tables prior to logging in with this SV file.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3937355/MonolithDKP.zip)

**Comment by lykann1337** [comment]
followed instructions and all of my online officers wiped tables and reloaded their ui and now it is showing 127 missing entries after sync

**Comment by lykann1337** [comment]
nope never mind, it has now re-synced and the data is correct across all tables
Thank you for your swift response and your help!
also ty for this addon and your continued work on it! truly a amazing piece of work!

**Comment by Roeshambo** [comment]
Thank you. Glad it got worked out.
