### ISSUE TITLE
2.0.4 issues.... 

### ISSUE THREAD

**Issue by ibeebrackin** [Roeshambo/MonolithDKP#164]
Anyway we can just go back to previous version, appears this version has a bunch of issues, broadcast dkp is not there for myself or any officers, all the officers are on 2.0.4 and about 3-4 different tables....

**Comment by Roeshambo** [comment]
The problem that is occurring it seems is that several people executed the migration last month and didn't roll back to prior files so the indexes remained. If you're an officer, post your Saved Variables file here and I can get it fixed for you. All other officers will have to just wipe their tables and retrieve the new data from you.

**Comment by ibeebrackin** [comment]
Do you know if we auto broadcast now? The button is no longer there for me. I wiped my table and got the correct table from one of my officers

**Comment by Roeshambo** [comment]
If everyone is on 2.0.4 it will automatically sync on login. Did you get the correct tables from someone using 2.0.4?

**Comment by ibeebrackin** [comment]
Yes, thank you

**Comment by Roeshambo** [comment]
Do you need any additional help with that? Or has it been resolved?
