### ISSUE TITLE
Migration Broke :(

### ISSUE THREAD

**Issue by incredibad** [Roeshambo/MonolithDKP#166]
Hey there,

We're trying to migrate our guild's data and everything just disappeared when we were trying to go through the steps. Obviously we've done something wrong, but attached is my pre-migrated lua file.

My character's name is Powered
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3937422/MonolithDKP.zip)

Thanks <3

**Comment by Roeshambo** [comment]
Have all of your officers wipe their tables (Options tab). I'll migrate this for you and have you replace your current saved variables file with it. Only after they've all wiped their tables, log in with this file and you'll automatically start broadcasting it to them.

**Comment by Roeshambo** [comment]
Most important part is your officers make sure their tables are wiped. If they have any old entries, they may broadcast them to you.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3937433/MonolithDKP.zip)

**Comment by incredibad** [comment]
Ok, thank you very much. I'll make sure the tables are wiped by our officers and give it a try shortly. Will let you know if there are any more issues <3

**Comment by incredibad** [comment]
Seems to have worked, appreciate the help @Roeshambo, much love and great work on the addon!
