### ISSUE TITLE
Missing Entries

### ISSUE THREAD

**Issue by Orsini87** [Roeshambo/MonolithDKP#167]
Hi Ro,

I swear I followed the steps properly but it appears to have 27 missing entries. We just downloaded the new version you pushed 30 mins ago as well. Our officers log on at different times and we're worried we wont get them to wipe their tables. Is there any way you could migrate this for us?

[MonolithDKPBackup.txt](https://github.com/Roeshambo/MonolithDKP/files/3937464/MonolithDKPBackup.txt)

**Comment by Roeshambo** [comment]
You only have 45 DKP History entries but 454 Loot entries. Is this correct? Or did you run into an issue with DKP history that got it wiped out?

**Comment by Roeshambo** [comment]
Also, what is your characters name?

**Comment by Roeshambo** [comment]
All migrated under the name Psychotic. Make sure all officers wipe their tables prior. In the event you have one officer that didn't due to being offline or something, and they end up corrupting your data with a broadcast, simply find a time when all officers can be online and reapply this file while they all wipe their tables.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3937482/MonolithDKP.zip)

**Comment by Orsini87** [comment]
My character's name is Psychotic.

I believe the 45 DKP History entries is correct. We're using Mono as an attendance / loot tracking utility - not so much the DKP function :)

Thank you for your help!

**Comment by Roeshambo** [comment]
If you have additional issues please reopen the ticket

**Comment by Orsini87** [comment]
Hi Roe, 

We're experiencing this when we try to load history a few times

Date: 2019-12-08 18:45:29
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\MonolithDKP\Modules\LootHistory.lua line 340:
   attempt to compare string with number
Debug:
   [C]: ?
   MonolithDKP\Modules\LootHistory.lua:340:
      MonolithDKP\Modules\LootHistory.lua:274
Locals:

AddOns:
  DBMCore, v1.13.23
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6.6
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  ElvUI, v1.17
  MonolithDKP, v2.0.4
  Questie, v5.2.3
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=472)

**Comment by Roeshambo** [comment]
Ok, that's weird. Some of your loot cost values converted to strings somehow in October it appears. Didn't notice that before...  Here's a repaired copy. You will likely have to have everyone delete their tables again or they won't receive the new data unfortunately.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3937685/MonolithDKP.zip)
