### ISSUE TITLE
DKP table blank and dont receive broadcasts

### ISSUE THREAD

**Issue by Fitzsio** [Roeshambo/MonolithDKP#168]
Ok so i updated the addon to the latest version and the GM says he did the migration as he was supposed to but since then i have a blank DKP table and dont receive broadcasts. I'am not an officer but looking at the addon on my main and my alt and it seems like maybe my main may have officer privileges. Also I see no orange text about Monolith when i login to my main but i do on my alt.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3937652/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
Nothing appears wrong with your file. You just need a broadcast. I would stay online a bit and try to sync periodically. If you request a sync while one is in progress it will ignore you. If an officer is online that has migrated tables, they will send it to you.

**Comment by rondon37** [comment]
Our guild is switching to Monolith currently and none of the officers can seem to sync at all. sometimes it attempts to sync but most of the time it says "synchronizing dkp tables" with no names listed. all 4 of us trying to sync have 2.0.5 version

**Comment by Roeshambo** [comment]
When you say switching to, does that mean you've never used it? Or migrating from 1.6 to 2.0?

**Comment by rondon37** [comment]
we never used it. brand new files for all of us

**Comment by Roeshambo** [comment]
Ok. Then you have nothing to sync I'd imagine. The sync simply sends entries to players that do not have them. IE: If you are offline and another officer hosts a raid. When you get online, the sync will send you any entries they had that you don't.

**Comment by rondon37** [comment]
Well our GM added his values for items and settings and broadcasted those as well as added the guild list and none of that information is syncing to other officers

**Comment by rondon37** [comment]
The GM has a list of guild members but none of the officers can receive that info it just says "no profiles listed" on the top

**Comment by Roeshambo** [comment]
Officers can add any names they want to the list. You never broadcast a list of players. You only add players that exist in the history. So if the GM gave everyone on the list 1 DKP, for example, you'd add those names to your list. At no time are profiles ever broadcasted unless called for in the history.

**Comment by rondon37** [comment]
excuse me . it states "no profiles returned"

**Comment by rondon37** [comment]
okay. But if I were to input DKP to players manually from our old spreadsheet, would that information be able to be seen from other officers

**Comment by Roeshambo** [comment]
Yes. When you apply DKP or reward loot, that information is automatically broadcasted to the entire guild. Everyone online that has the addon will see it appear in their window almost instantaneously.

**Comment by rondon37** [comment]
there is also some issues with 2 of our officers not being able to see the manage tab. The whitelist is turned off

**Comment by Roeshambo** [comment]
Make sure they have "Edit Officer Notes" permissions in your guild and then have them reload their UI. That guild permission is what dictates if someone has officer permissions within the addon

**Comment by Roeshambo** [comment]
If they already have those permissions, make sure no players are selected on the list and click the "Set Whitelist" button. This will ensure the whitelist is cleared

**Comment by rondon37** [comment]
Thank you!

**Comment by kore98** [comment]
Having massive issues with the new update, can't view anyones names or broadcast anything - I am an officer  (No Profiles Returned). Tried downloading GM's dkp file since it worked for him, but sadly not working for me. Please help :( Kore#8712

**Comment by Roeshambo** [comment]
Have you wiped your tables? Options tab has a button for it.

**Comment by Fitzsio** [comment]
i tried as you said but i dont receive broadcasts on my main rogue when they're sent and i've tried to sync countless times but it never works.

**Comment by Roeshambo** [comment]
Best way to start receiving broadcasts if you are having issues with it would be to close your game client entirely and go to _classic_\WTF\Accounts\ACCOUNT_NAME\SavedVariables and locate the MonolithDKP.lua and MonolithDKP.lua.bak and delete both of them. Make sure the game client is closed entirely when you delete them. Then when you login, you'll be able to sync if an officer with 2.0.3+ is online. If they are not on 2.0.3+ you won't be able to sync with them at all as it's not compatible with older versions.

**Comment by Fitzsio** [comment]
Ok i did as you said but my rogue still doesnt receive broadcasts and cant sync with the GM. My rogue doesnt even see the orange text from monolith on login but my other chars appear to work fine or atleast they see the orange text on login.

**Comment by Roeshambo** [comment]
You might not have your main window selected for addon messages in the options tab. Might explain why you're not seeing the text. As far as receiving broadcasts, if you're not getting them then your GM very likely is not on 2.0.3 or later. You will never receive broadcasts from earlier versions because the prefixes are completely different.

**Comment by Fitzsio** [comment]
suppress addon notifications is unchecked and GM is on 2.0.4 same as me. if it helps i think monolith sees my main as an officer since my rank has alot of privileges such as promoting/demoting, changing notes/officers notes and i can read officers chat. my main also has extra stuff within the addon compared to my alt.

**Comment by Roeshambo** [comment]
Rank shouldn't hold any bearing on if you receive broadcasts. Thinking perhaps your GMs file migrated improperly. Would you be able to have him send you that to post here?

**Comment by kore98** [comment]
I can't recieve broadcasts, my gm is on latest version, supress addon notification is not ticked and i've deleted the .lua and .lua.bak files while game is entirely closed. How do i fix this?
