### ISSUE TITLE
DKP Export issue on DKP history page

### ISSUE THREAD

**Issue by lwatkins** [Roeshambo/MonolithDKP#169]
We've migrated and things seem to look correct inside the game, but the export view has a (seemingly) trash entry right up front.

https://i.imgur.com/1b0smBb.png
https://i.imgur.com/h5pnf1g.png

You can see that the first entry has a lot of decimal numbers with many digits, exponents, percentages... but the entries that come after that appear as they do in the game. 
https://i.imgur.com/SwFBwJ3.png

**Comment by Roeshambo** [comment]
That entry was part of the migration. The new system runs entirely on the history. You don't exactly track peoples DKP, you determine what it is based on all of their history loaded chronologically. This way if anything gets screwy, it can be rebuilt (right click the DKP table and use Validate Tables to rebuild). During the migration, if the DKP history didn't add up properly to the DKP values you had listed for each player, it created a hidden entry that compensated for it. So if you had 100 DKP on your table, but your history only added up to 90 for whatever reason, it created an entry giving you 10 more. Make sense?

**Comment by lwatkins** [comment]
Gotcha, thanks.

P.S. Appreciate the addon!

**Comment by Roeshambo** [comment]
I can't really explain why the WoW API has such a hardon for decimals though. It seems if you don't round everything, it makes some crazy decimal.
