### ISSUE TITLE
Vanilla Classic

### ISSUE THREAD

**Issue by Vyrus22** [Roeshambo/MonolithDKP#17]
Hey, I am using your addon for my guild in vanilla classic. I am currently experiencing an issue when I add our raiders+officers to the list, and give them dkp, most of the list disappears and I can't see anyone on the list other than a select few. Is there something I am doing wrong to cause this?

**Comment by Roeshambo** [comment]
Identified and resolved. Please download the newest version here or wait until they're approved at curse/wowint.
