### ISSUE TITLE
Multiple issues with new update

### ISSUE THREAD

**Issue by ATypeBlameaux** [Roeshambo/MonolithDKP#170]
1) Not syncing across all of raid.  Everyone updated, but not everyone receiving redistributions.  Sync button does not reach everyone.  I am an officer and not receiving updates from our raid leader.  Tried syncing raid leader + myself both on 2.0.5 and I got no update or communication

2) Guild uses custom bid system.  We silent bid outside monolith and use high bid whisper !bid and that person is the only bid.  Before update, the bid would successfully input and redistribute.  After update, no matter the bid whispered the amount docked is the minimum dkp set to the itemslot.  Raid leader had to adjust minimums each time to redistribute properly.

3) Raid leader boss-loot screen does not come back up when exited out of.  Prior to update, screen could be exited and revisited freely.  Post update, after exiting screen cannot bring it back up.

Guild: Blackwater (RL Scallywahg)
Server: Blameaux - US (Classic)

**Comment by ATypeBlameaux** [comment]
Update: we may have figured out #2.  But syncing is still an issue.  I deleted addon and reinstalled and stiill cannot receive updates to dkp.  Multiple people in raid did not receive updates during raid.

**Comment by Roeshambo** [comment]
Did you conduct the migration yourself or was it another officer? When you say no one's receiving redistributions, are you referring to syncing the old entries or do you mean when new entries are created they are not being received (2.0.5 is not compatible with any versions below 2.0.2 so if they're using anything below that, they will not receive anything)? By raid leader boss-loot screen do you mean the auction window to start bidding? It can be opened at any time with /dkp bid or shift+alt clicking an item within the loot window. There shouldn't be any issues with that. If you are having problems please turn on script error reporting (/console scriptErrors 1) and have whoever else that is having issues do the same and report any errors received.

**Comment by ATypeBlameaux** [comment]
I apologize for verbal spewing issues here.  Maybe we should take them one at a time.  Want to figure out the syncing issues before anything else.

Another officer conducted the migration.  We're both on voice together and when he presses "sync" nothing happens on my end.  My dkp looks like it did before the migration.  I tried deleting the addon entirely and reinstalling and no better.  My dkp log does not display any information from today's raid (12/8)

Other guild members are reporting dkp lists inconsistent than the raid leader's list.

**Comment by ATypeBlameaux** [comment]
By raid leader boss loot screen i meant the window that allows RL to redistribute dkp.

Edit: love the addon by the way, we've been using it for all of classic.  Appreciate your work.

**Comment by Roeshambo** [comment]
After the officer migrated, did you wipe your tables? Or are you still seeing the old DKP values in your main window?

**Comment by ATypeBlameaux** [comment]
i did not wipe tables or do anything other than update the addon.  Don't know how to wipe tables.  Other officers are getting syncs but not all of us.  Don't think any officer did anything other than install update (other than RL, who migrated).

Note that the RL may have migrated before i updated my addon.  Does that affect anything?

**Comment by Roeshambo** [comment]
The new version is designed to ignore all broadcasts until you've set it up to receive. The triggers for that is empty tables. After they migrated, your migration window should have changed to identify the person migrating with additional instructions. If it was closed that may not have happened. No worries though. In your Options tab, at the bottom, there is a "Wipe Tables" button. Click that and then reload your UI and you'll be able to receive sync broadcasts.

**Comment by ATypeBlameaux** [comment]
Awesome that fixed that issue.  Do all raid members need to wipe tables or just officers?

**Comment by Roeshambo** [comment]
Everyone must start with empty tables. Reason being is the migrated table creates indexes. They must receive all of those entries with the proper indexing.

**Comment by Roeshambo** [comment]
Non officers should have their tables wiped automatically when they log in.

**Comment by ATypeBlameaux** [comment]
Thank you for your help.  I think we had a setting off which messed up another issue.  Will follow-up after next raid if anything persists.

**Comment by Roeshambo** [comment]
If you'd like to test prior, you can always create a 2 man raid and test the other parts you believed to be broken on junk mobs.

**Comment by Roeshambo** [comment]
If you have any additional issues please comment and I'll reopen the ticket :)
