### ISSUE TITLE
Lost all Loot History and DKP History

### ISSUE THREAD

**Issue by chaluo** [Roeshambo/MonolithDKP#171]
Hey.
I am a officer. With 1.6.3 I did the migration. Just installed 2.0.5 and loot history and DKP history is gone. I can still see everyones DKP in the "left" window.

**Comment by Roeshambo** [comment]
Please post your saved variables file

**Comment by Roeshambo** [comment]
As well as a pre migration copy if you have it

**Comment by Roeshambo** [comment]
Additionally, did you yourself perform the migration? When you logged in you would have had a large box open up with instructions and a button appearing at the bottom to migrate. It would have reloaded your UI after it executed.

**Comment by chaluo** [comment]
Hey. Attaching file.
Do I need to do another migration? I did one when I updated to 1.6.3.
I did the migration when I updated for 1.6.3

[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3938477/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
Ok I'm guessing you migrated about a month ago and moved back to 1.6.3. I'll migrate the file for you. Make sure all other officers wipe their tables (button to do that in Options tab). They must be on 2.0.5 for it to work. It's not compatible with older versions. What is your characters name and are you an officer?

**Comment by chaluo** [comment]
Moz is my characters name. I am a officer. I am on 2.0.5. Everyone thats online atm (not many) are also 2.0.5

**Comment by Roeshambo** [comment]
If you're not an officer, what is an officers character name? The indexes must use an officers name.

**Comment by chaluo** [comment]
I am a officer. Moz is the name of my character

**Comment by Roeshambo** [comment]
Ok here's a properly migrated SV file. Before you load this up. Make sure all of your officers wipe their tables (button to do so in the Options tab). Also, make sure no other officers have migrated before loading this up or you'll mix entries and effectively double everything. After all officers have wiped, close your client and put this file in and log in with it. You'll begin broadcasting it to them. Absolute most important part is that your officers wipe their tables.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3938516/MonolithDKP.zip)

**Comment by chaluo** [comment]
That worked. Thank you! Some cash heading your way. Thanks for a awesome addon

**Comment by Roeshambo** [comment]
Thank you! And I'm glad you like it. Hoping to have more additions soon.
