### ISSUE TITLE
Validate error after changing the guild

### ISSUE THREAD

**Issue by BreakBB** [Roeshambo/MonolithDKP#173]
After leaving the guild I've got a message that data has been erased to prevent corruption. But upon joining a new guild (and now on every login) I get the following error message:

```
MonolithDKP\Modules\Validate.lua:86: bad argument #1 to 'pairs' (table expected, got nil)
[C]: in function `pairs'
MonolithDKP\Modules\Validate.lua:86: in function `ErrantCheck'
MonolithDKP\init.lua:299: in function <MonolithDKP\init.lua:250>
```

Looks like you either have to check if `MonDKP_Meta.DKP` is `nil` or change it to be an empty table instead of `nil` erasing the old data.

**Comment by Roeshambo** [comment]
Ah. That sounds like an oversight on my part. Thank you

**Comment by BreakBB** [comment]
Thank you very much 👍
