### ISSUE TITLE
Problems with newer Monolith

### ISSUE THREAD

**Issue by ramboozer** [Roeshambo/MonolithDKP#175]
I've been reading here about you asking people to upload there files so you can add index values to them....Can you please maybe give a short explanation how to upgrade from 1.6.x to 2.x.x? I've looked around and haven't been able to find any relevant information aside from what I stated. The guild I am currently in has used MDKP for 2 or more months now and we need to easily transition everything to the newer system without losing any data.

**Comment by Roeshambo** [comment]
The short version is you go into your saved variables file and remove the index key from the first and last entry in each of the loot and dkphistory tables, and then completely delete any meta/remote tables near the bottom and then load up on 2.0.5 and migrate it, it will reindex everything. If you're not comfortable with doing that, upload the sv file and I'll gladly do it for you

**Comment by Roeshambo** [comment]
If you need additional help please comment and I'll reopen this. I'll gladly do the migration for you if you're concerned about complications.
