### ISSUE TITLE
Double Migration HELP!

### ISSUE THREAD

**Issue by tornadoff** [Roeshambo/MonolithDKP#178]
Hellow
Two of our officer  press "Migration"  and now all data is doubled. Can we cancel one Migration? Or what we can do now to return everything?
It is impossible to delete everything manually. We had 2.5 months every week for two raids. We will manually delete this week. Given the fact that after each deletion of one item, the scroll scrolls back to its original position and it is impossible to delete a lot at once with the filter.
Can u help us?

**Comment by Roeshambo** [comment]
Yes. Post your saved variables file, pre migration if possible. Or any one that is available and I'll remigrate it

**Comment by Roeshambo** [comment]
Make sure all data is in it. If you need to get one of theirs you can. Just make sure all entries are in it, even if they're duplicated

**Comment by tornadoff** [comment]
> Yes. Post your saved variables file, pre migration if possible. Or any one that is available and I'll remigrate it

I sent it on u e-mail

**Comment by Roeshambo** [comment]
Ok I'll look into that as soon as I get home

**Comment by tornadoff** [comment]
Thanks. I also wanted to add that I had already started manually deleting duplicated positions. I don’t know how it will be displayed in the file that I sent.

**Comment by Roeshambo** [comment]
It's fine. In the new version there is an added section to the migration that deletes entries with identical time stamps. I just have been using that to correct files by remigrating with it. If you delete the index key from the first and last entries in each table as well as delete the mondkp_meta and meta_remote tables, then log back in it should let you migrate it again. I haven't received an email from you yet so I'll check when I get home

**Comment by tornadoff** [comment]
To be honest, I didn’t understand anything: where and what to delete? once we did something we didn’t understand - now we had to bother you.

**Comment by Roeshambo** [comment]
No worries. I want to get everyone fixed. The migration was a bit of a challenge to get past so if there's any problems I'm working to get everyone migrated. Once we get past that part, the rest is smooth.

**Comment by Roeshambo** [comment]
I believe I got your email but it did not have anything attached. You can simply drop the file into the text box here

**Comment by arialpew** [comment]
I wonder why officer are authorized to do migration ?

The addon should only permit the migration process via Guild Master (1 man) to avoid the "double migration" issue when officer fail and do a migration that already happened (I got this problem in the first v2 release 2 weeks ago, all DKP entries was duplicatd because 1 of our officer failed by not listening us, he was confused, and it seem this issue can arise in the new version that you release).

It would be nice to prevent any members to do it, except the Guild Master.

I don't know if it's possible, maybe find the "MONDKP" guy in the guild via LUA API to know which guy can do the migration process and prevent others members that have permission in MonolithDKP addon to do it ?

Anyway, i'm waiting 2/3 weeks before switching to the new version, to see how it goes. But now I know that saving the SavedVariables make everything easier to recover :) . That helped us a lot when the first v2 was release and then deleted.

Thanks for this addon btw ;) .

**Comment by Roeshambo** [comment]
Surprisingly, a lot of guilds have mentioned that their GM doesn't use the addon. Not sure why. But if I would have restricted it to GM it would have just gotten some blowback from that.

**Comment by tornadoff** [comment]
[MonolithDKP № 1.zip](https://github.com/Roeshambo/MonolithDKP/files/3943649/MonolithDKP.1.zip)

**Comment by tornadoff** [comment]
[MonolithDKP №2 .zip](https://github.com/Roeshambo/MonolithDKP/files/3943650/MonolithDKP.2.zip)

**Comment by tornadoff** [comment]
if I did and understood everything correctly: in the first folder the file is before the migration, and in the second after the duplicated migration.

**Comment by tornadoff** [comment]
Could you still answer two questions:
1. After you give me the corrected file - how do we proceed? Do all officers have to duplicate their files in the "SavedVariables" folder and only after that will I go into the game with a new file? Or do you need to take some other steps?
2. Do officers mean only officers or class leaders too?

**Comment by Roeshambo** [comment]
What is the name of the character that you want the migration done under? Must be an officer. For your questions. Everyone in your guild must wipe their tables. They can either delete the file in their saved variables entirely or they can use the "Wipe Tables" button in the options tab. Any officers that have permission to edit DKP will need to do it first and foremost. But everyone in the guild will have to do it to get the correct data.

**Comment by Roeshambo** [comment]
Basically, you don't want to log in with the newly migrated file, and then have other officers with old data broadcast to you giving you bad data. So it's best to just make sure everyone in the guild wipes their tables first.

**Comment by tornadoff** [comment]
name of the character -  "Ce"

**Comment by Roeshambo** [comment]
That look more correct to you?
![image](https://user-images.githubusercontent.com/6285297/70513717-c1ddbc00-1af7-11ea-84a7-e17194653b88.png)

**Comment by tornadoff** [comment]
Hm, no... Can u show how much DPK have character - "Ce"? it should be around 750-800.
i see first character " Littlexoxo " in table and he should be have about 780 DPK (it says "-825 DPK", but this should not be 100%.)

**Comment by Roeshambo** [comment]
That look accurate to you?
![image](https://user-images.githubusercontent.com/6285297/70514267-eede9e80-1af8-11ea-976e-36a5f0c32221.png)

**Comment by Roeshambo** [comment]
Here's that file migrated with the character "Ce" as the migrating officer. Make sure everyone wipes their tables. If you see your indicator turn red saying you're missing entries, it's likely because someone didn't wipe their tables.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3943860/MonolithDKP.zip)

**Comment by tornadoff** [comment]
thanks a lot! All working now

**Comment by Roeshambo** [comment]
No problem.

**Comment by tornadoff** [comment]
Good evening. I have received a new table from you yestoday. Everything was fine. Today updated to 2.0.6. Somewhere overpriced by 200%, and somewhere around 50%. Will I get everything back? Why did this happen? The class leaders also had to clean the old table or not? We only have 2 officers and a GM, and we all definitely deleted the old tables.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3952213/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
Is it only non officers that have incorrect data?

**Comment by tornadoff** [comment]
I apologize. The second officer said that this is old data from him - today he went from another computer where there was old data. This is our mistake. Could you help me one last time? I threw the file above.
We allrady have radi and some corrections yestoday and today allready/

**Comment by Roeshambo** [comment]
Of course. Yes it looks like data was duplicated. I'll manually move the new entries from yesterday/today into the file I gave you yesterday and reindex everything for you. You'll have to make sure everyone in the guild wipes their data again unfortunately. Especially the officers. I'm working on a script that people can run when something like this happens to repair their data.

**Comment by tornadoff** [comment]
I will be grateful.

**Comment by Roeshambo** [comment]
Are you the only person that added entries to the table since I gave you the fixed one?

**Comment by tornadoff** [comment]
yes

**Comment by Roeshambo** [comment]
Here ya go. Got it as close as I could with the history that occurred after the last migrate.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3953419/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
If you have more issues please let me know and I'll reopen. Gotta clean up :p
