### ISSUE TITLE
Constant yellow after migration between officers

### ISSUE THREAD

**Issue by vilestyle** [Roeshambo/MonolithDKP#179]
Hello,

Our guild recently migrated. Everything seems correct, DKP entries etc. 

However, the light is constantly yellow and it says im updating Officer1, officer2, officer3 and no amount of time or /reloads seems to make it go green. And its always just those 3 other guild officers.

Edit- It seems to have gone green on my PC, but not my laptop. Strange. 

Is this something to worry about?

Thank you for all the hardwork, we love the 2.0 update
Vilestyle <. blamaeux. >

**Comment by Roeshambo** [comment]
Yellow means it's currently syncing. Does it go green or red after it completes?

**Comment by Roeshambo** [comment]
Additionally, it'll say up to date or out of date in the tooltip. If it says up to date, you're good

**Comment by vilestyle** [comment]
Yes, it says up to date. Perhaps that meant those other officers were syncing someone else? Either way, all seems to be good. Thank you again, awesome work!

**Comment by Roeshambo** [comment]
Yes, whenever someone logs in they request a sync unless one is already in progress. Seemed to be the best way to make sure all data gets propagated throughout the guild if someone is missing entries from a raid they didn't attend etc.
