### ISSUE TITLE
Doesn't work on Russian locale

### ISSUE THREAD

**Issue by Voley** [Roeshambo/MonolithDKP#18]
I have tried the addon extensively on live BFA and classic.   
I'm guild master on both.
Tried adding guild members, raid members and target, to no avail.
It asks - are you sure? I click Yes, and alert window hides, but nothing happens.

I have followed setup instructions as described on addon page before adding anyone.

What can be done about that?

If you need any more debug info, I'm ready to provide.

Version 1.4.4

**Comment by Roeshambo** [comment]
I'm still relatively new to the WoW API and Lua as a whole and have not quite delved into including locales. So the EN clients is really all I would imagine it would 100% work on at the moment. If I'm able to get around to it, I'd like to localize the addon for more regions. But it will take time. If you'd like to turn on your script errors with "/console scriptErrors 1" and then attempt to do what is not working, it might give a bit more information. If you do get an Lua error, please post that.

**Comment by xiobartreexs** [comment]
Message: Interface\AddOns\MonolithDKP\Modules\comm.lua:348: attempt to compare number with nil
Time: Thu Sep 12 18:44:07 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\Modules\comm.lua:348: attempt to compare number with nil
(tail call): ?
Interface\AddOns\MonolithDKP\Modules\comm.lua:348: in function `?'
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...ace\AddOns\DBM-Core\Libs\AceComm-3.0\AceComm-3.0.lua:258: in function <...ace\AddOns\DBM-Core\Libs\AceComm-3.0\AceComm-3.0.lua:246>

Locals: <none>

**Comment by xiobartreexs** [comment]
I turned on the errors using this command and nothing else appeared.
I’m trying to add a target from a party or from a guild for a rank such as “officer” and nothing happens.

**Comment by xiobartreexs** [comment]
Message: Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:181: attempt to concatenate field 'hex' (a nil value)
Time: Fri Sep 13 01:19:10 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:181: attempt to concatenate field 'hex' (a nil value)
Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:181: in function DKPHistory_Update'
Interface\AddOns\MonolithDKP\ConfigMenuTabs.lua:286: in function ConfigMenuTabs'
Interface\AddOns\MonolithDKP\MonolithDKP.lua:131: in function CreateMenu'
Interface\AddOns\MonolithDKP\init.lua:251: in function OnInitialize'
Interface\AddOns\MonolithDKP\init.lua:114: in function <Interface\AddOns\MonolithDKP\init.lua:96>
Locals: self = <table> {
 ConfigTab1 = <unnamed> {
 }
 StartRaidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\RaidTimer.lua:127
 SortDKPHistoryTable = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:25
 StartTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:347
 GetDKPSettings = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:262
 Table_Search = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:427
 ConfigTab2 = <unnamed> {
 }
 Sync = <table> {
 }
 StartBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:691
 ToggleBidWindow = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:270
 ConfigTab4 = <unnamed> {
 }
 LootHistory_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\LootHistory.lua:321
 DKPTable_Set = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:505
 PurgeDKPHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:281
 ConfigTab6 = <unnamed> {
 }
 UIConfig = MonDKPConfig {
 }
 Commands = <table> {
 }
 ConfigTab3 = <unnamed> {
 }
 ZeroSumBank_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\ZeroSumBank.lua:68
 PurgeLootHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:270
 StopRaidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\RaidTimer.lua:104
 ToggleExportWindow = <function> defined @Interface\AddOns\MonolithDKP\Modules\exportDKP.lua:348
 GetGuildRankGroup = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:218
 GetGuildRankIndex = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:175
 DKPModesFrame_Create = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPModes.lua:17
 BroadcastTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lu

**Comment by Roeshambo** [comment]
Is this a new issue or related to the localization posted above? Also, please make sure the guild leaders public note is 0 or empty.

**Comment by xiobartreexs** [comment]
guild leaders public note = 1568323718

**Comment by Roeshambo** [comment]
You're trying to add all guild members rank officer and above and it's giving you that?

**Comment by xiobartreexs** [comment]
Do you have a discord? I could take part in testing or some help so that the addon works on a Russian client. It would be great

You're trying to add all guild members rank officer and above and it's giving you that?
-I’m a guild master, I tried adding an officer by rank and the list remains empty.

**Comment by xiobartreexs** [comment]
nothing happens and the error is not shown, although I entered this command.  "/console scriptErrors 1"

**Comment by Roeshambo** [comment]
That will simply show any errors that occur after. Need to redo whatever isn't working

**Comment by xiobartreexs** [comment]
No errors appear

**Comment by Roeshambo** [comment]
And what specifically are you trying to do?

**Comment by xiobartreexs** [comment]
I am trying to add to the addon a list of people who are with me in the party so that they count DKP points

**Comment by xiobartreexs** [comment]
I can show everything to you in a discord through screen sharing

**Comment by Roeshambo** [comment]
Are they within your guild? And which option are you using to add players? I'm at work so can't discord atm

**Comment by xiobartreexs** [comment]
Write to the discord when it is convenient. and I’ll show you everything, with screenshots, video, as you want
StreetX
#9223

**Comment by Roeshambo** [comment]
Msg me on my server https://discord.gg/uRwSnbw

**Comment by custodian** [comment]
@voley @xiobartreexs try this version https://github.com/custodian/MonolithDKP/tree/voodoo-release

**Comment by Voley** [comment]
@custodian Seems to be working OK, but I don't see item bidding in this version. 
@Roeshambo can you please look into changes by custodian?

**Comment by custodian** [comment]
@Voley item bidding windows is available only to guild officers

**Comment by Voley** [comment]
@custodian yes, but I'm guild leader

**Comment by custodian** [comment]
@Voley make sure that lua errors are not hidden, i.e. 
run `/console scriptErrors 1`, 
next reload ui `/reload ui`, and try `/dkp bid [item-link]`
Keep an eye on MonolithDKP system messages in general chat (lack of permissions, other reasons) 
Copy paste any lua errors here.
