### ISSUE TITLE
missing entries

### ISSUE THREAD

**Issue by agroholic** [Roeshambo/MonolithDKP#180]
1st of all thx for making a great add-on 
im having problem with the addon which always says missing entries even tho we Remove our Entries Table and still have our Guild bank Entries even tho he delete all his entries .
we want to start fresh table . even tho try to delete all the tables and still having issue with the Missing Entries . 

below is the zip file which contain our Monolith DKP , we just want to remove the Mcibank entries as it show in the addon 
https://gyazo.com/92c4dfa089456669165ffa3b4589b382
this is the image it show that i have missing entries even tho we delete all the tables and want to fill it manualy
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3942246/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
It looks like the 3 entries are in your MonDKP_Meta_Remote table. What that means is someone in your guild either thinks those 3 entries exists or they themselves have 3 entries. So someone in your guild has a MonDKP_Meta table that has a "current" value of 3 for Mcibank. Just gotta find that person and have them wipe their tables (button in Options tab does that). Until they wipe that off their table, they will keep reporting that 3 exist somewhere.

**Comment by agroholic** [comment]
ok ill check with officers which has the Mcibank Entries . thx alot
