### ISSUE TITLE
Dkp issue

### ISSUE THREAD

**Issue by Skeltyr** [Roeshambo/MonolithDKP#181]
I cant seem to paste the .html file here

**Comment by Roeshambo** [comment]
Copy your saved variables file. Located at wtf\accounts\account_name\savedvariables\monolithdkp.lua

**Comment by Roeshambo** [comment]
Can just drag and drop the file into the text box

**Comment by Skeltyr** [comment]
Says does not support that file type

**Comment by Roeshambo** [comment]
You can either zip it or add a .txt to the end

**Comment by Skeltyr** [comment]
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3943181/MonolithDKP.lua.txt)

**Comment by Roeshambo** [comment]
Ok I'll clean it up and migrate it for you to get rid of the duplicates. What is the migrating officers character name? It needs to be an officer or could get screwy.

**Comment by Roeshambo** [comment]
Here's the table after remigration and validation. Just need to know which officer to assign the indexes to and I'll send it your way with instructions.

![image](https://user-images.githubusercontent.com/6285297/70499829-a1096c80-1adf-11ea-8bc8-a515ed5a4d4a.png)

**Comment by Skeltyr** [comment]
Sporanox, thank you

**Comment by Roeshambo** [comment]
Ok here's your migrated tables. Best way to get this set up is to not use it yet. Set up a time to give this file to all of your officers. Make sure everyone has their client closed and put this file into the savedvariables folder i showed you above. (delete the old one first). That way when you all log in, no one will have any information that could contaminate it. From there it'll get automatically distributed to the rest of the guild. It's normally not that complex but I'm taking extra steps to make sure your migration goes smoothly :p
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3947604/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
If this did not fix your issues please comment and I'll reopen.
