### ISSUE TITLE
Sync with out of guildies?

### ISSUE THREAD

**Issue by Drfreshz** [Roeshambo/MonolithDKP#182]
Is there anyway to make the list populate for people who are not in the guild?

**Comment by Drfreshz** [comment]
Is there anyway to make the list populate for people who are not in the guild?

**Comment by Roeshambo** [comment]
No unfortunately there is not at the moment. Especially after tomorrow. The only channels that are available for addon communication is GUILD, WHISPER, and RAID. I would like to make a system that can allow you to talk to other players outside of the guild. But I haven't been able to get to something that complicated yet.
