### ISSUE TITLE
After Update only one officer has accurate dkp and it will not broadcast to the rest of the guild! Help

### ISSUE THREAD

**Issue by lunchboxx666** [Roeshambo/MonolithDKP#183]
The last update wiped all member dkp and it will not broadcast the correct dkp to everybody! Please Help!

**Comment by lunchboxx666** [comment]
Here is the LUA file from the officer that has all the numbers correct. Please help!
[MonolithDKP(1).lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3943435/MonolithDKP.1.lua.txt)

**Comment by Roeshambo** [comment]
His loot table is completely empty. Do you not log loot? Or is that incorrect?

**Comment by lunchboxx666** [comment]
I logged loot by subtracting dkp using other with the item as the reason code.

**Comment by Roeshambo** [comment]
Ok. I'll get this migrated properly. What is the character name the indexes should be under? Must be an officer.

**Comment by lunchboxx666** [comment]
I got it from Sticky but i want to migrate it to Khorne as that is me and i am the guild leader. Is that possible?

**Comment by Roeshambo** [comment]
Of course. Have all of your officers wipe their tables completely (button in Options tab to do so). Everyone else in the guild will require a wipe if they had received broadcasts but the officers are most important.

**Comment by lunchboxx666** [comment]
Ok cool Thanks. When you fix it please let me know how to implement the fix. Thanks for your time and your addon makes dkp management great and i appreciate you.

**Comment by Roeshambo** [comment]
All you're going to do is wait until you're positive everyone has wiped their tables. Then you'll put this file that I'll give you into your saved variables folder (WTF\Accounts\ACCOUNT_NAME\SavedVariables\). Your game client must be closed when you put it in there. Make sure to delete the old MonolithDKP.lua. When you log in, you will broadcast to the guild to sync up.

**Comment by lunchboxx666** [comment]
is the new broadcast button the green circle?

**Comment by Roeshambo** [comment]
Yes. You'll automatically broadcast on login though.

**Comment by Roeshambo** [comment]
All set. Just make sure all officers wipe their tables. If they log in with the old data, they will send it to you and it will get all mixed in with this. Then you'll just have to start over.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3943493/MonolithDKP.zip)

**Comment by lunchboxx666** [comment]
Are officers only people who are whitelisted?

**Comment by Roeshambo** [comment]
As long as other officers within the guild have that whitelist, yes. But I don't like to trust the whitelist as it's kind of dodgy. Overall, officers in the addon are dictated by the "Edit Officer Note" permissions within your guild settings.

**Comment by lunchboxx666** [comment]
Perfect. We are back up and running with correct numbers. Youre the best Roeshambo, Thanks for all your help.

**Comment by Roeshambo** [comment]
No problem.
