### ISSUE TITLE
Request: Current High Bid in Raider's Bidding Window

### ISSUE THREAD

**Issue by Jaredn** [Roeshambo/MonolithDKP#184]
Not sure what the master looter interface looks like since I'm just a raider, but testing monolith out tonight I noticed I had to read raid chat for bids instead of having it just update in my bid window interface.  It's a bit annoying to constantly be trying to watch raid chat for bids and simultaneously increase my bid.

Something simple like "Current Max Bid - Bidder_Name" would be sufficient:

Example:

Current High Bid: DragonKiller - 250

**Comment by Roeshambo** [comment]
Those options are available for the officers to turn on. If they do have options to allow you to see bids turned on, make sure they broadcast the settings to the guild. What you show is based off settings they send to you.
