### ISSUE TITLE
Migration Help

### ISSUE THREAD

**Issue by charaspepe** [Roeshambo/MonolithDKP#185]
Hello,

We did the 2.0.4 migration and ran into issues. So we restored the original table and attempted the migration again. Now we are having issues where we have 2 officers that are syncing data that no longer exists. It says there are 9 tables from one officer and a few from another officer. 

[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3945065/MonolithDKP.lua.txt) This is the current migrated table 

[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3945071/MonolithDKP.lua.txt) This is pre-migration table 

[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3945073/MonolithDKP.lua.txt) This is the original migrated table,some of the DKP was off by around 150-200 DKP 

Any help would be greatly appreciated!

Thank you,

**Comment by Roeshambo** [comment]
Here ya go. Make sure before you use it all officers wipe their tables completely. Can delete their SV files entirely or they can use the Wipe Tables button in options. All other players that have received data will also have to delete their tables but the officers are the most important part to prevent them from sending you some of that old data.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3945127/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
If you start seeing your tooltip saying you're missing entries, it's most likely because someone in the guild still has the old information and they are telling you more entries exist than actually do. Newest version of the add-on should auto resolve that after they've wiped their tables

**Comment by charaspepe** [comment]
Thanks for the quick response. I'll have all the officers wipe data and drop the new table in tonight when I logon. 

When do you think the new version will be available?

Thanks,

**Comment by Roeshambo** [comment]
It's already up. 2.0.5, if everyone is on it, will auto correct someone if they have incorrect index counts

**Comment by Krispxxy** [comment]
[Monolith DKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3947590/Monolith.DKP.zip)

**Comment by Roeshambo** [comment]
If you continue to have issues please comment on here and I'll reopen and look into it :)

**Comment by Krispxxy** [comment]
Hey, I never got a chance to save that file. Sorry about that. I was
waiting for my officers to log on to coordinate the migration but they
never were able to log on all together, so i was not able to get that file.
Do you still have that file from our discussion saved?

**Comment by Krispxxy** [comment]
My account name was Krispxxy

**Comment by Krispxxy** [comment]
Nevermind, I was able to find file in email notifications! thanks!

**Comment by Roeshambo** [comment]
https://github.com/Roeshambo/MonolithDKP/issues/191
