### ISSUE TITLE
Question for migration

### ISSUE THREAD

**Issue by f1est0** [Roeshambo/MonolithDKP#187]
**Hello.** In order to correctly transfer data from version 1.6.3 to version 2.0.5, you just need to exit the game, save the database (MonolithDKP.lua) for an emergency, delete 1.6.3 and install 2.0.5? Does he automatically edit it?

**Comment by f1est0** [comment]
And can I "Officer" update it all without participation GM. Or is there a migration help page?

**Comment by Roeshambo** [comment]
All officers will need to participate. It's best to coordinate it and do the migration when all officers can be online. You'll all load up with 2.0.5 and ONE officer will click the "Migrate" button when it pops up at login. Then, all other officers should get a window popping up telling them that one officer has migrated and they must wipe their tables (if this doesn't pop up for whatever reason, have them click the Wipe Tables button in the options tab). Once they're all wiped the migrating officer can open the GUI and start a migration by clicking the status button on the bottom left. If one already started, wait till it completes and start it again.

**Comment by f1est0** [comment]
And if you lower all the officers, after which the two of us with the guilds master, set it up. And then back up. So will it work?

**Comment by Roeshambo** [comment]
Ya that would be safe. When you demote them to a rank that doesn't have "Edit Officer Note" privileges, make sure they log off and back in to ensure the addon recognizes they are no longer officers. Their tables will automatically be wiped when they log in. So if they want to back it up just to be safe, have them do so before they do log back in.

**Comment by Roeshambo** [comment]
If you have issues please comment here and I'll reopen.
