### ISSUE TITLE
Cant migrate

### ISSUE THREAD

**Issue by sveber** [Roeshambo/MonolithDKP#188]
Hei,

Updated to 2.0.5 using twitch addon, all the tabels are gone, no migrate button, and no other officers have done anything yet.

what to do?

**Comment by Roeshambo** [comment]
That's unusual actually. Please get the SavedVariables file from one of the officers that has all data still and post it here. I'll make sure it's migrated properly for you and have instructions to make sure it goes smoothly.

**Comment by sveber** [comment]
i was the one officer with the correct data, the other officers dont have the complete list, but i guess thats the best we can get?

**Comment by Roeshambo** [comment]
If you haven't reloaded or logged since logging in and having data gone, you'll still have a MonolithDKP.lua.bak file that should have the information

**Comment by sveber** [comment]
cant find that file

**Comment by sveber** [comment]
Does the savedVariables have to be from another officer?

**Comment by Roeshambo** [comment]
Just has to be from anyone that has the most up to date information as possible. Even a non officer.

**Comment by sveber** [comment]
is the file named SavedVariables? we cant find it

**Comment by Roeshambo** [comment]
_classic_\WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua

**Comment by sveber** [comment]
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3946778/MonolithDKP.zip)

**Comment by sveber** [comment]
That shuld be the one

**Comment by Roeshambo** [comment]
Ok looks good. As soon as I get home I'll get that migrated for you. You can tell your officers all to wipe their tables. When I send this back it'll be migrated and ready to broadcast. All you'll do is put this into the folder you found it above (while your WoW client is completely close) and then start up and login. Shortly after it'll start syncing up. Make sure your WoW client is closed when you put the file in or it won't take.

**Comment by Roeshambo** [comment]
What is the officers name that the migration should be done as?

**Comment by sveber** [comment]
Tankyspanky

**Comment by sveber** [comment]
Awsome, thanks for the help!

**Comment by Roeshambo** [comment]
Ok here's your migrated tables. Best way to get this set up is to not use it yet. Set up a time to give this file to all of your officers. Make sure everyone has their client closed and put this file into the savedvariables folder i showed you above. (delete the old one first). That way when you all log in, no one will have any information that could contaminate it. From there it'll get automatically distributed to the rest of the guild. It's normally not that complex but I'm taking extra steps to make sure your migration goes smoothly :p
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3947597/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
If you have any more issues please comment here and I'll reopen it and help you any way I can.

**Comment by sveber** [comment]
Hey, we did the steps, and now it says, monolith dkp has not completed initalization..

**Comment by sveber** [comment]
classic\WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua

This is where to put that file?
Shuld we delete the addon and reinstall it before we put in the file maybe?

**Comment by Roeshambo** [comment]
Nope. Just delete the old SV file and put the new one in place while the game is closed. "monolith dkp has not completed initalization" means it simply hasn't initialized yet. Just wait a few seconds. I pushed back the initialization of the addon to avoid loading before other necessary elements.

**Comment by sveber** [comment]
its been 5 min and its not completed

**Comment by Roeshambo** [comment]
Try relogging... That's not normal.

**Comment by sveber** [comment]
still not working :/

**Comment by sveber** [comment]
It was a new update today, migth that have something to do about it?

**Comment by sveber** [comment]
is it possible to delete everything and reinstall, then put the new SV file into it?

**Comment by Roeshambo** [comment]
I'm logged in with the 2.0.6 version and it's functioning fine for me. Just redownloaded the addon from curse to be sure there wasn't corruption in the uploaded version and I log in and open it just fine.

**Comment by Roeshambo** [comment]
Yes you can do that.

**Comment by sveber** [comment]
Its working now! takes a lot of time for it to zync, but it works! thanks again =)

**Comment by Roeshambo** [comment]
Ya when you're doing a full table dump it can take time because it must be throttled. If you send too many chat messages with the data too fast the game will disconnect you. But once you're past the initial sync it's really quick
