### ISSUE TITLE
Any advice?

### ISSUE THREAD

**Issue by Squigglymoo** [Roeshambo/MonolithDKP#189]
When we use the addon, everyone is "out of date" unless the GM is online. (this is after i completed the migration). Some raiders have 2.0.5 but still see crazy amounts of DKP that is different to the GM and officers. Any tips to fix this? i have asked them to wipe the tables and get updated from officers again, but no matter what we do we cant fix it.

Any help?

**Comment by Squigglymoo** [comment]
Oh i forgot to mention, every time GM logs on it says we all have 188 Entries to be updated from him, even if he makes no changes.

**Comment by Roeshambo** [comment]
It sounds like his migration got mixed up. Most likely from previous indexes. Post his saved variables file here and I'll get it migrated for you. All you'll have to do is have everyone in your guild wipe their tables and then give the file I send back to the GM and have him log in with it. All officers must have their tables completely wiped clean (button in options tab). All other members should wipe as well.

**Comment by Squigglymoo** [comment]
But i completed the migration for the guild. Would that matter?

**Comment by Roeshambo** [comment]
When 2.0 was initially released a month ago did he do a migration with it? If so he would have indexes with his name on it causing that to occur.

**Comment by Squigglymoo** [comment]
Yes he did, i will message him now
