### ISSUE TITLE
New issue with applying decay

### ISSUE THREAD

**Issue by oggez** [Roeshambo/MonolithDKP#190]
Hey, we tried to apply decay today after our raid, but it seems that only the person who applied it actually got it.
The rest of the officers can see the decay but it did nothing with the dkp values. It also sais they are missing one entry when trying to sync.

Here's our file:
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3947313/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
Ok. That's unusual. That script has been completely untouched for months. I'll look into that.

**Comment by Roeshambo** [comment]
The decay reduced everyone's DKP properly for the person that did the decay?

**Comment by oggez** [comment]
Yes

**Comment by Roeshambo** [comment]
Do you know if he used the Add to Negative option to return DKP to players that were in the negative?

**Comment by oggez** [comment]
Yes that option was checked

**Comment by Roeshambo** [comment]
Ok there's the bug. Thank you. You're not adding any additional entries to that file for a few days are you?

**Comment by oggez** [comment]
Well, we have a raid tomorrow

**Comment by Roeshambo** [comment]
Ok. Best way to fix that is to get the SV file from the officer that did the decay and give that to all your officers. Make sure their client is closed before putting that file in place. Everyone else can just wipe and request a sync. i'll get that fixed immediately.

**Comment by oggez** [comment]
Alright, we can do that.
Is there anything we need to change in the file before we do that?

**Comment by Roeshambo** [comment]
Yes. Let me actually go ahead and fix that manually really quick and give you the file. Looking at the script the officer that did the decay will probably have an incorrect file as well. I'll have that posted in a little bit. I'm fixing the script here on Git so you can download it from here

**Comment by oggez** [comment]
I think he went to sleep, so it will have to wait until tomorrow. I'll post it asap

**Comment by Roeshambo** [comment]
Go ahead and log in with this. You'll need to validate your table (right click the DKP table and select Validate Tables). It'll take a few minutes to run but it'll fix the profiles that didn't receive the decay.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3947495/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
Heading home in a few minutes and I'll get the script fixed and verified and let you know in case you apply another decay soonish.

**Comment by Roeshambo** [comment]
You can download the AdjustDKP.lua file here on github and replace the one in your MonolithDKP\Modules folder with it and it'll correct the decay issue for Add to negative.

**Comment by Roeshambo** [comment]
If you have additional issues with this please comment and I'll take a look.
