### ISSUE TITLE
Migration Help

### ISSUE THREAD

**Issue by Krispxxy** [Roeshambo/MonolithDKP#191]
Hello,

I have recently just updated the monolith DKP addon today. All of the data is whipped on the addon and there is no migration option. I am the GM of the guild and none of my officers mess with the addon. Is there a way you can help me bring back most recent data?

**Comment by Krispxxy** [comment]
The officers in the guild have updated the addon and the data has shown up for them but the table for me is still empty.

**Comment by Roeshambo** [comment]
Yes. Please get the SavedVariables file from one of your officers. I'll migrate it for you to make sure it's done properly and then give it back. Then just have all of your officers use the "Wipe Tables" button in their options tab and then you log in with the migrated file I give you. They will want to back up the saved variables file before wiping it just in case. Then when you log in with the new file, it will broadcast to them.

**Comment by Krispxxy** [comment]
Ok do you need monolith.lua file or monolith.lua.bak file ??

**Comment by Roeshambo** [comment]
the one with just .lua

**Comment by Krispxxy** [comment]
[Monolith DKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3947591/Monolith.DKP.zip)
Most recent file from one of my officers, I do not see the DKP data table though, just loot history.

**Comment by Roeshambo** [comment]
It's all there. What is the character name of the officer you want the migration done under?

**Comment by Krispxxy** [comment]
Can you do it under me as GM? Krispxxy
If not you can do this officer, Laplace

**Comment by Roeshambo** [comment]
Ok here's your migrated tables. Best way to get this set up is to not use it yet. Set up a time to give this file to all of your officers. Make sure everyone has their client closed and put this file into the savedvariables folder. (delete the old one first). That way when you all log in, no one will have any information that could contaminate it. From there it'll get automatically distributed to the rest of the guild. It's normally not that complex but I'm taking extra steps to make sure your migration goes smoothly
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3947735/MonolithDKP.zip)

**Comment by Krispxxy** [comment]
Sounds good , thank you for your help and quick responses !

**Comment by Krispxxy** [comment]
Would it work to migrate if I removed all the "Edit Officer Note" check mark in the guild control and then reload the new migration table?

**Comment by Roeshambo** [comment]
Yes that would work. Just make sure any officers that were online when you removed that permission relogs. The addon determines someone's officer status at login. If you remove the permission and they stay logged in, they'll retain officer permissions within the addon until they relog.

**Comment by Roeshambo** [comment]
If you need additional help with this issue please comment and I'll reopen.
