### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by shrenk090** [Roeshambo/MonolithDKP#192]
Hello,

I've got a .lua of one of the officers, I can see the DKP list in version 2.0.5 but the synchronisation of the list does not work. If I give someone DKP everyone with the addon just can see the amount I added. Everyone who updated the addon has en empty list ?
How to sync the old list ?
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3947663/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
What is the migrating officers character name? I'm going to migrate it for you. What you're going to do is give this file, after i've migrated it, to all of your officers and have them replace their SavedVariables file while their client is closed. Make sure you set up a time for all of you to do it together or else it could get contaminated with old entries from your migration. After that, all non officers in the guild can wipe with the Wipe Tables button in their options tab and request a sync.

**Comment by shrenk090** [comment]
The name is Shrenk :)
If I whitelist GM can I replace the file and sync it to everyone without giving it to all the officers? and after it synced whitelist back the officers or delete it ?

**Comment by Roeshambo** [comment]
The whitelist is kinda iffy. You can try it but I'm not sure I'd rely on it. If something goes wrong you can always simply have everyone wipe their tables and start over again with the file. But everyone must wipe their tables completely before you log in with this (officers especially). It'll only broadcast to them after they've wiped their tables. I just suggest giving the file to the officers to ensure they don't have any data they can accidentally send you had they migrated by mistake.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3947790/MonolithDKP.zip)

**Comment by shrenk090** [comment]
Thank you ! :)

What is an officer for the addon ? Ranks with permissions ? If so could I remove all the permissions of the Ranks under GM and it should recognize everyone as a member and not as an officer ? :/

**Comment by Roeshambo** [comment]
Any ranks that have "Edit Officer Note" permissions in the guild is recognized as an officer. If they are online when you demote them, you need to ask them to relog before the addon picks up on the change

**Comment by shrenk090** [comment]
ok so it should work if I remove the permission "Edit Officer Note" of the Ranks and wait until they log in and the addon recognize it after they log in even if they were not on when I changed the Rank permission without demoting them?

**Comment by Roeshambo** [comment]
No it'll recognize it after you switch it. But if they are online when you do switch their permissions they will need to relog as the addon still saw they had permissions prior. If they are offline when you switch it, then when they log in they will not get officer permissions.

**Comment by Roeshambo** [comment]
If you continue to have issues please comment here and I'll reopen and assist.
