### ISSUE TITLE
Migration help

### ISSUE THREAD

**Issue by claimer21** [Roeshambo/MonolithDKP#193]
Hi, having a small issue with the migration.  Some officers don't have the correct data.

I am the officer that initiated the migration, the other officers then wiped their tables.  2 officers seem to have the wrong data after the sync is finished.  The other two officers and myself have the correct data.  We tried having them wipe their tables again and then synced but that didn't work.  How do we fix this?

@Lumee-Stalagg

**Comment by Roeshambo** [comment]
Can you please post your saved variables file and we'll see about getting you fixed

**Comment by duffman4evr** [comment]
Hi @Roeshambo - just a quick question (didn't want to make a new issue) - given that wowinterface.com is showing a [warning ](https://www.wowinterface.com/downloads/info25094-MonolithDKP.html)to stay away from 2.0, would it be wise for me to notify my guild to stay on the older version for now?

**Comment by Roeshambo** [comment]
You can sure. I'm workin to get it running smoother. The migration is the speed bump. After that it's running just fine.

**Comment by claimer21** [comment]
@Roeshambo here is my saved variables file.  I "think" our officers might be good now, I gave the ones who were having issues a copy of my saved variables file and had them wipe tables before replacing it.  Still worried something might be messed up or get messed up down the line though.



[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3951166/MonolithDKP.zip)

**Comment by claimer21** [comment]
Ehh maybe we're not good to go after all.  It's saying my  tables are out of date now, but they were up to date last night before I logged off, so I don't know how as no officers have made any updates.

Is there an easy way to do a full wipe and then we just manually adjust in the DKP values of everyone?  I wouldn't mind fully wiping our tables and starting fresh.  Would also make syncs faster, etc.

**Comment by Roeshambo** [comment]
Your data is most likely all still correct. What happens during a sync is you ask what everyone's current index is for each officer. If it's higher than yours it says you're missing entries. So in your case, what's most likely happening, is someone in your guild hasn't wiped their tables of the old data. All you have to do is make sure all non officers wipe their tables and redownload the new data from you or another officer that has them.

**Comment by Roeshambo** [comment]
If you'd like to post your current SV file I can confirm for you that you have all of the correct data and that is, in fact, the issue.

**Comment by claimer21** [comment]
My current SV file is posted above, do you see it? I attached it

**Comment by Roeshambo** [comment]
Was it saying you were out of date with that one?

**Comment by Roeshambo** [comment]
According to that SV file, you're missing one entry from Lumee. Which I believe is you. So that means someone in the guild likely just has old data and thinks one more entry exists than actually does.
