### ISSUE TITLE
Migration Help

### ISSUE THREAD

**Issue by nomenclad** [Roeshambo/MonolithDKP#194]
The only Officer with the correct DKP tables is named Pewed. Here is his lua. I can't get it to sync with my cleared out tables for the life of me. 

[MonolithDKP Correct.zip](https://github.com/Roeshambo/MonolithDKP/files/3948271/MonolithDKP.Correct.zip)

**Comment by Roeshambo** [comment]
Ok I'll get that migrated for you shortly. Best practice to get it set in place safest is to not put it into saved variables until you're ready. Set a time when all of your officers will be online and have all of them close their game and put the SV file I give you into their SavedVariables folder so they all have the same data. This will prevent old data from possibly tainting the file in a sync. Then the rest of the guild can just wipe their tables and sync with the officers.

**Comment by nomenclad** [comment]
Hey Roeshambo, I think I've actually figured out how to remove the index and meta on my own. I just need to sync up with other officers.


[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3948397/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
After you've removed the indexes and all of the meta tables (can just delete all tables below MonDKP_DKPHistory) you can run the migration again which should fix it. After that, all ofthe rofficers MUST wipe their tables. If they login with old indexes, they'll send you those indexes in a sync and mess your tables up

**Comment by Roeshambo** [comment]
Would you still like me to migrate it for you?

**Comment by nomenclad** [comment]
Trying to save you more work since I know it's a cluster right now. If you have the time to look it over I'd appreciate it.

Is it possible to set the file to read-only to prevent it from being accidentally sync'd with other officers when they log on to clear their tables?

**Comment by Roeshambo** [comment]
It's no problem. I wanna get everyone up and going with it. I knew the migration was going to be the biggest hurdle.

**Comment by Roeshambo** [comment]
And no it's not. BUT you could change guild permissions so you're the only person that has "Edit Officer Note" permissions. Just make sure if anyone that had the permissions when you change it logs off and back in. The addon identifies officer status on login. If you remove permissions and they don't relog they'll still be recognized as an officer.

**Comment by nomenclad** [comment]
I think I'm going to take that route and turn that permission off overnight when everyone is offline. Thanks for the heads up.

**Comment by Roeshambo** [comment]
Is Pewed the name of the officer you'd like them migrated as? Or a different character name?

**Comment by nomenclad** [comment]
I'd prefer LuLou so that I can do it myself. Thank you.

**Comment by Roeshambo** [comment]
Lulou is the character name?

**Comment by nomenclad** [comment]
Correct

**Comment by Roeshambo** [comment]
Ok, there was a fairly large migration correction. An entry is created if the total history doesn't add up to what the DKP table said each player had for DKP. Just so the history properly adds up to what the DKP table said each player had. Do these look like the proper DKP values for these players?
![image](https://user-images.githubusercontent.com/6285297/70592378-3ae41e80-1b9f-11ea-804c-c8860fde3828.png)

**Comment by nomenclad** [comment]
Those look correct. We had some issues back at the start of classic with Officers not syncing correctly with the addon and it caused some errors. We were planning to reset when BWL comes out so we didn't stress it so much.

**Comment by Roeshambo** [comment]
Ok just wanted to make sure. That's why the correction is there. Some people had some history get lost

**Comment by Roeshambo** [comment]
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3948514/MonolithDKP.zip)

**Comment by nomenclad** [comment]
Thank you very much

**Comment by Roeshambo** [comment]
If you continue to have issues with this please comment and I'll reopen.
