### ISSUE TITLE
Issue with many bids on DKP Bid Interface

### ISSUE THREAD

**Issue by alatterner** [Roeshambo/MonolithDKP#195]
After doing raid tonight, we had some issues with some members of our raid. They have the most recent version (2.0.5).

When using the bidding window, our raid members were having both lua errors and monolith issues when the number of bids exceeded a certain number (one theory from one of them was that it was when the number of bids went past the window size). I'm not sure of the specific number.

In the Monolith window, they were getting a "WARNING: Your DKP Modes settings have changed and can not run that until your UI is reloaded. Can we reload to complete that?" Reloading doesn't fix it.

In chat, they're getting a lua error: 
...nterface/AddOns/MonolithDKP/Modules/Bidinterface.lua:154: attempt to index local 'row' (a nil value).

Let me know if there are any other pieces of information you need.

**Comment by alatterner** [comment]
If it helps at all/may be the culprit, I used the fix described in:
https://github.com/Roeshambo/MonolithDKP/issues/165

**Comment by Roeshambo** [comment]
The fix described in that ticket is what allows bids to be accepted if it's equal to the current highest bid. As far as the error your receiving, yes it looks like it's reaching the max rows in the table and erroring out because there aren't additional rows created. I'll see about getting that fixed.

**Comment by Roeshambo** [comment]
I've fixed this and it'll be in the next version.
