### ISSUE TITLE
Many people removed from list

### ISSUE THREAD

**Issue by rondon37** [Roeshambo/MonolithDKP#196]
Right before we got to the first boss in MC, the addon removed 30 people from the list and deleted all their dkp. I tried to manually input all the entries again and sync them but no one was able to sync with me. It also kept saying we were missing 40 entries from our GM

**Comment by Roeshambo** [comment]
That doesn't sound right. Can you please post your saved variables file? Fortunately the way it's designed, even if you delete someone, it doesn't actually delete their DKP as it can be rebuilt from the history. It's sounding like there was a failed migration somewhere in there. Also if you can get your hands on an officers saved variables file that has the closest to accurate data it will also help.

**Comment by rondon37** [comment]
it doesn't allow me to attach file

**Comment by rondon37** [comment]
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3948803/MonolithDKP.lua.txt)

**Comment by Roeshambo** [comment]
Ok there's only 4 loot entries in that file. Is that accurate?

**Comment by rondon37** [comment]
I manually entered the loot entries

**Comment by rondon37** [comment]
because before we got to the final boss it wiped everyones dkp and we were afraid to use it again

**Comment by Roeshambo** [comment]
Ok. What is the officers name you'd like this remigrated as? The indexes must use an officers name or it won't work right.

**Comment by Roeshambo** [comment]
Oh i see. Is there someone else in your guild that still has all of the entries by chance? We could rebuild you a file from theirs if they do.

**Comment by bellumcaliga** [comment]
[monolith.txt](https://github.com/Roeshambo/MonolithDKP/files/3953690/monolith.txt)

**Comment by Roeshambo** [comment]
is 45 players the correct number you should have?

**Comment by rondon37** [comment]
yes

**Comment by Roeshambo** [comment]
Any chance the migrating officer created a backup before doing the migration as was suggested?

**Comment by rondon37** [comment]
we started from scratch. we didn't have monolith prior to 2.0

**Comment by Roeshambo** [comment]
Really.. Ok that's unusual. Have not heard of that happening. 30 players with DKP were suddenly removed. Were there any messages when that occurred? And did anyone mention doing anything when it happened? There's nothing within the addon that would have done that. It would have been an officer deleting them.

**Comment by Roeshambo** [comment]
Does this look like proper data to you?
![image](https://user-images.githubusercontent.com/6285297/70686303-8961ed80-1c71-11ea-8cb9-5894c2763d3f.png)

**Comment by rondon37** [comment]
we all just got a message in chat saying that all these people were removed.

**Comment by rondon37** [comment]
and all those dkp numbers are very high. look almost doubled

**Comment by Roeshambo** [comment]
Ok. Ya did someone try recovering by giving those people DKP back?

**Comment by Roeshambo** [comment]
When you get a message saying players are deleted, it means someone selected them and hit "Remove Entries" in the Manage tab. There are no scripts that automatically remove players unless initiated by an officer.

**Comment by Roeshambo** [comment]
So. I know it's not made overly obvious. But when you right click on the DKP table, at the bottom of the context menu, there is an option to "Validate Tables". What this does is it rebuilds all profiles based off of the DKP and Loot history. So if you delete someone, you can readd them and validate tables. And it will give them all the DKP back that they earned (or spent) in the history.

**Comment by rondon37** [comment]
So how would i get rid of the excess dkp that was awarded ?

**Comment by rondon37** [comment]
because my tables show the correct dkp but the gms numbers are way high

**Comment by Roeshambo** [comment]
Does the GMs table look pretty much exactly like the picture I linked above?

**Comment by rondon37** [comment]
no his does not look like the table above.

**Comment by rondon37** [comment]
it is now accurate. but we are having issues with all of the officers syncing

**Comment by Roeshambo** [comment]
Does it say there are entries missing?

**Comment by rondon37** [comment]
no it is slowly syncing but they have to go into the rank drop down tab and manually enter people then itll sync to the right dkp. is there also a way to add more than one person to the white list? GM is saying it only allows him to add one

**Comment by Roeshambo** [comment]
Since you guys barely have any data in your tables, to be completely honest, I would take a screenshot of the correct DKP for everyone, and then have everyone wipe their tables and manually adjust everyones DKP to where it needs to be and go from there. Make sure all officers with permissions to edit DKP are online and wipe at the same time so they don't accidentally log in and send bad data. Whitelist is iffy at best. But no he can add as many as he likes. Just control+click on the list for all the players he wants on it.

**Comment by rondon37** [comment]
it is still telling us that we are missing 28 entries from our GM

**Comment by Roeshambo** [comment]
That most likely means someone in the guild didn't wipe their tables. When you sync, everyone reports what they currently have. If someone still has entries from before, they will report that to you. Once they wipe and you sync with the GM online, he corrects it with how many entries he actually has.

**Comment by rondon37** [comment]
only officers can wipe tables correct?

**Comment by Roeshambo** [comment]
Everyone can wipe their own tables. And everyone should. It's just the officers that are priority to do it because if they don't they'll just broadcast the stuff you deleted back to you.
