### ISSUE TITLE
Migration Help

### ISSUE THREAD

**Issue by nick-goodyear** [Roeshambo/MonolithDKP#197]
I am the only one with access to the correct data.  Went from 1.6.4 to 2.0.4 to 2.0.5

Characters name is Elfslaughter
and here is my file 
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3948743/MonolithDKP.zip)

Pretty much I have the correct data and everyone else cant see it.  I have already removed the Edit Officer Note permission from everyone until this is sorted out.

Thanks!

**Comment by Roeshambo** [comment]
Ok. I'll get this migrated. Then all you have to do is load it up and have everyone else in the guild wipe their data. Then you'll broadcast it to them. When all of your officers are showing all accurate data they're all set.

**Comment by Roeshambo** [comment]
Migrated and indexed with "Elftslaughter". If you have any issues please let me know. But as long as no other officers are able to broadcast the bad data to you, you shouldn't have any issues 
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3948821/MonolithDKP.zip)

**Comment by nick-goodyear** [comment]
Sorry, I think I supplied the incorrect file.

Here is the correct.   ( I was comparing someone else file before)
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3948847/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
That second file you just posted has only 68 Loot entries and 311 DKP History entires. Where as the first one I migrated has 477 loot entries and 424 DKP history entries. Is the one you just posted the one you want to use?

**Comment by nick-goodyear** [comment]
Yes we have only been running dkp for a bit.  But I noticed that all the names of the players and loots were all wrong.  it was another guilds file.   I was comparing their file with ours to see if there was something I could fix myself

**Comment by Roeshambo** [comment]
Ah gotcha. Ok i'll migrate that really quick.

**Comment by Roeshambo** [comment]
Here ya go.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3948971/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
If you need additional assistance please let me know.
