### ISSUE TITLE
Migration help

### ISSUE THREAD

**Issue by Kartor1** [Roeshambo/MonolithDKP#200]
Hi, 

I was using this addon for my guild and upgraded from 1.6.3 to the latest version and all my data is lost.

Need assistance please.

Thanks and regards,
Kartor

**Comment by Roeshambo** [comment]
Non officers get their tables wiped automatically because an officer must migrate their data and distribute the new data.

**Comment by Kartor1** [comment]
ok can you help me solve this please?

What can I do to get the data back. I am the GM of this Guild ofc.

**Comment by Roeshambo** [comment]
Ok we can get that fixed up. Get a hold of one of your officers that has the data and have him send you his saved variables file and I'll help you get it migrated

**Comment by Kartor1** [comment]
ok so some questions:

when you say have one of my officers send me the file, if they updated the addon they lost it too?
me as a Gm I don't have this list you need?

**Comment by Roeshambo** [comment]
No. I have a feeling you logged in on a non officer alt and that's why it got wiped. Someone will still have the file.

**Comment by Kartor1** [comment]
you are correct one of my alts is not officer :(

**Comment by Roeshambo** [comment]
That's unusual. There's nothing in the addon that would wipe your tables if you are an officer. We can still fix the problem. Just gotta get a copy of that file from someone when they're available and I'll migrate it properly for you.

**Comment by Kartor1** [comment]
yes yes you are right one of my alts was a bank not an officer

ok so next step where do then need to go to get this file please?

**Comment by Roeshambo** [comment]
Just speak with an officer or someone thjat has all current data and ask them to send you their saved variables file at \WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua. Then post that here.

**Comment by Kartor1** [comment]
ok another question, if they don't see anything on the dkp addon does that mean that the data is lost or its still saved somewere?

**Comment by Roeshambo** [comment]
Means it's been wiped.

**Comment by Kartor1** [comment]
ok I checked my file I have 2 files MonolithDKP.lua and MonolithDKP.lua.bak.........is the bak back up?

**Comment by Roeshambo** [comment]
It's only a backup for one reload. You can check it but it likely has the same data as the .lua. Your best bet is to get the file from someone that hasn't wiped their tables. Everyone in the guild should have one so it wouldn't be too hard.

**Comment by Kartor1** [comment]
my worry is that all ppl who I have asked so far all are saying they are seeing nothing on the dkp list

**Comment by Roeshambo** [comment]
Your officers would most likely have it.
