### ISSUE TITLE
DKP Wiped on all

### ISSUE THREAD

**Issue by Gankrr** [Roeshambo/MonolithDKP#202]
Hey,

This is our first time using Monolith, we've been using it for a month. We all updated today and thought nothing of it. Not a single officer nor me(GM) can see any DKP now. I can attatch my .lua file but I have no idea if it's overwritten. It does not work to /dkp migrate nor can I find out how I can manually trigger the migration. 

[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3951570/MonolithDKP.zip)

Gankr - Noggenfogger EU

**Comment by Roeshambo** [comment]
That's unusual. Any chance you logged in as a non officer alt? Try to get a SV file from someone in the guild that hasn't updated and still has the data and I'll gladly get you fixed up.

**Comment by Gankrr** [comment]
Hey man!
We've been reading up on all of your replies and posts. We managed to fix the issue! Thank you for your reply!

Gankr

**Comment by Roeshambo** [comment]
Ok. I just want to make sure your file is migrated properly. So I'll tell you how to check that really quick. When you look into your SV file. You'll see a MonDKP_DKPHistory table and MonDKP_Loot table. You'll notice entries in there have a numbered index along with the officers name (Looks like Gankr-1 etc). Look at the very top index of each table, and then go to the bottom of the table and you'll see an entry counter next to the last entry telling you how many there are. If the top index number and the bottom entry count for both tables are the same, you're good there. Then check MonDKP_Meta and MonDKP_Meta_Remote. If MonDKP_Meta -> that officers name in the indexes -> current is the same as the highest index in the corresponding table (DKP or Loot) and lowest is 1 ,you're set there. And the Meta_Remote should show just the highests for each table. If you're uncertain on what to check or just want to be sure, feel free to post it here and I'll verify.
