### ISSUE TITLE
Wrong DKP Data / Numbers for some guild members (including all officers)

### ISSUE THREAD

**Issue by Solid924GER** [Roeshambo/MonolithDKP#203]
Hello,

yesterday I commented your Monolith DKP Migration video and wrote the following:

"We have the following problem with the newest update after the migration:

I have the correct DKP Data / Values. Some people in the guild also have but some don't. All officers do not have the correct DKP Data as well. Syncronising won't help.
They deleted the addon and also the .lua file and installed the addon again but the wrong values / data remain for them and they do not get my DKP updates...

Any idea how we can fix this? Thank you very much!"

You told me that I should upload my saved variables and you could fix it.
My characters name is: **Nîcèoné**

Thank you very much!

[SavedVariables_Nîcèoné.zip](https://github.com/Roeshambo/MonolithDKP/files/3951623/SavedVariables_Niceone.zip)

**Comment by Roeshambo** [comment]
Hey, I'll gladly get you fixed up. But those aren't the correct files. You'll need to post the file located at WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua

**Comment by Solid924GER** [comment]
[SavedVariables_Nîcèoné.zip](https://github.com/Roeshambo/MonolithDKP/files/3951815/SavedVariables_Niceone.zip)

Oh, sorry! These should be the correct files. Thank you once again :)

**Comment by Roeshambo** [comment]
Ok your table looks like it migrated properly. There was one error but it wouldn't really effect you in syncing data. Load this file up in place of yours and then anyone that has incorrect data, have them wipe their tables (button to do that in the options tab) and then once they've done that, start a sync (status indicator on the bottom left). It'll take a little time to send all the data but once it's done they should be all good.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3951853/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
If you continue to have issues here please comment and I'll do everything i can to help.
