### ISSUE TITLE
Probable issue post migration of new update

### ISSUE THREAD

**Issue by Koined** [Roeshambo/MonolithDKP#204]
Hi there, we just did the new update and did the migration and I'm guessing there's no broadcasting DKP button anymore like it was before in 1.6.x

Anyways I am not sure if I did it incorrectly or not, I am the one that did the migration. Clicked the button, deleted the GMs old note and it was replaced with [MonDKP=Asinia] (aka my name, the officer that did the migration) but for the rest it seems some of the DKP values are off either by one or two or three, and some even by 20 dkp.

as I said, what I did was back up SV pre migration > updated addon > migrated > deleted GMs note - tell me if I did anything wrong and if there's anything I can do for the rest of the members and their tables besides just giving them my savedvariables mondkp lua files.

If there's anything to help let me know please, sorry for my redundancy :D

[MonDKP-SV-PostMigration.zip](https://github.com/Roeshambo/MonolithDKP/files/3951630/MonDKP-SV-PostMigration.zip)

**Comment by Roeshambo** [comment]
Everyone elses is off by a little bit but yours is correct, is that right?

**Comment by Roeshambo** [comment]
All of your tables look correct and migrated properly. If their data is incorrect, have them go to the Options tab and wipe their tables. Then they can request a sync and they'll get all the correct data from you.

**Comment by Koined** [comment]
Alright, I'll let them try that and see what happens and report back to you.

Thanks a lot for your hard work on the addon, it has helped us immensely and I really enjoyed using it. Had to edit the lua file to fix a few things after we transferred to a new server with some of our members having new names but it was a nice adventure nonetheless. Gained a lil' bit of lua knowledge on the way.

Cheers.

**Comment by Roeshambo** [comment]
If you need additional assistance just comment here please.
