### ISSUE TITLE
Can't sync

### ISSUE THREAD

**Issue by Nidums** [Roeshambo/MonolithDKP#207]
Guild leader seems to have lost the ability to sync the DKP list with people that have updated to the new version, he still can still the lists and they are correct.

**Comment by Roeshambo** [comment]
What does it say when he tries to sync?

**Comment by Jordyderuijter** [comment]
Same here, the broadcast dkp tables button is simply gone?

**Comment by Roeshambo** [comment]
In new version, the status indicator on the bottom left is the Sync button.
