### ISSUE TITLE
Shhsleep / Blackrose saved variables

### ISSUE THREAD

**Issue by blackroseblackrose** [Roeshambo/MonolithDKP#208]
Heres the saved variables cache of myself. 
-note, i have backup pictures of the entries i took last night after the raid. and entered them into what i have now. 
-Note , all of my officers are saying
 the dkp entries were reverted to last weeks entries. 
[https://github.com/blackroseblackrose/entries-blackrose/blob/master/MonolithDKP.lua.bak](url)

**Comment by blackroseblackrose** [comment]
[entries-blackrose-master.zip](https://github.com/Roeshambo/MonolithDKP/files/3952294/entries-blackrose-master.zip)

**Comment by Roeshambo** [comment]
That SV file appears to be empty. Please get a saved variables file from another member of your guild that has all of their data and I'll rebuild you one
