### ISSUE TITLE
/dkp award not working in 2.0.4/2.0.5/2.0.6

### ISSUE THREAD

**Issue by YannickFousse** [Roeshambo/MonolithDKP#209]
In previous versions up to 1.6.3, I used the command /dkp award to attribute loot in my guild instead of the bid system. The command doesn't work anymore, no messages is displayed (error or otherwise) and the window that should open to choose raid/boss doesn't open.

**Comment by Roeshambo** [comment]
The command is /dkp award [item link] now. If you're not getting a message telling you that then you have addon messages suppressed or a channel not selected. In the Options tab "Suppress Addon Messages" blocks them entirely and the dropdown that says Addon Notifications selects what chat windows it prints it to.

**Comment by YannickFousse** [comment]
Thanks, couldn't find the "new" command anywhere in the change logs.

**Comment by Roeshambo** [comment]
-Changed the manual award command to "/dkp award [item link]" for ease-of-use. Cost is automatically defaulted to the minimum bid/cost set for that type of item but can be changed as needed.

Sorry there were a lot of notes so it got kinda tucked in there. Also if addon messages are being printed to a chat window, if you type the command in the old style it notifies you of that.
