### ISSUE TITLE
Ru classic

### ISSUE THREAD

**Issue by StealControl** [Roeshambo/MonolithDKP#21]
Cant add members 

Date: 2019-09-18 03:53:38
ID: 1
Error occured in: Global
Count: 1
Message: ...terface\AddOns\MonolithDKP\Modules\ManageEntries.lua line 164:
   attempt to concatenate field 'hex' (a nil value)
Debug:
   ...terface\AddOns\MonolithDKP\Modules\ManageEntries.lua:164:
      ...terface\AddOns\MonolithDKP\Modules\ManageEntries.lua:142
   ...terface\AddOns\MonolithDKP\Modules\ManageEntries.lua:460: OnAccept()
   ..\FrameXML\StaticPopup.lua:5003: StaticPopup_OnClick()
   [string "*:OnClick"]:1:
      [string "*:OnClick"]:1
Locals:
rank = 1
guildSize = 332
class = "Охотник"
addedUsers = nil
c = <table> {
 Warrior = <table> {
 }
 Druid = <table> {
 }
 Shaman = <table> {
 }
 Warlock = <table> {
 }
 Priest = <table> {
 }
 Hunter = <table> {
 }
 Rogue = <table> {
 }
 Mage = <table> {
 }
}
name = "Стилконтрол"
rankIndex = 1
numPlayers = 1
(for index) = 47
(for limit) = 332
(for step) = 1
i = 47
search = false
(*temporary) = "|cff"
(*temporary) = nil
(*temporary) = "Стилконтрол"
(*temporary) = ""
(*temporary) = <table> {
}
(*temporary) = "attempt to concatenate field 'hex' (a nil value)"
_ = "Офицер"
MonDKP = <table> {
 SortDKPHistoryTable = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:25
 StartTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:347
 GetDKPSettings = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:262
 StartBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:691
 PurgeDKPHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:281
 ClassGraph_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:116
 ConfigTab3 = <unnamed> {
 }
 UIConfig = MonDKPConfig {
 }
 GetGuildRankGroup = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:218
 BroadcastTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:335
 ConfigTab6 = <unnamed> {
 }
 ClassGraph = <function> defined @Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:6
 BroadcastStopBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:672
 ValidateSender = <function> defined @Interface\AddOns\MonolithDKP\Modules\comm.lua:15
 CreateBidWindow = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:1006
 CheckOfficer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:191
 DKPHistory_Reset = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:31
 ZeroSumBank_Create = <function> defined @Interface\AddOns\MonolithDKP\Modules\ZeroSumBank.lua:86
 Options = <function> defined @Interface\AddOns\MonolithDKP\Modules\Options.lua:57
 AdjustDKPTab_Create = <function> defined @Interface\AddOns\MonolithDKP\Modules\AdjustDKP.lua:244
 ConfigTab1 = <unnamed> {
 }
 ConfigMenuTabs = <function> defined @Interface\AddOns\MonolithDKP\ConfigMenuTabs.lua:112
 LootHistory_Reset = <function> defined @Interface\AddOns\MonolithDKP\Modules\LootHistory.lua:304
 FilterDKPTable = <function> defined @Interface\AddOns\MonolithDKP\MonolithDKP.lua:45
 StartRaidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\RaidTimer.lua:127
 DKPModesFrame_Create = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPModes.lua:17
 ConfigTab4 = <unnamed> {
 }
 Table_Search = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:427
 ToggleBidWindow = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:270
 DKPTable_Set = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:505
 ToggleDKPModesWindow = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPModes.lua:5
 Commands = <table> {
 }
 PurgeLootHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:270
 ZeroSumBank_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\ZeroSumBank.lua:68
 GetGuildRankIndex = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:175
 ToggleExportWindow = <function> defined @Interface\AddOns\MonolithDKP\Modules\exportDKP.lua:348
 TableStrFind = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:466
 SeedVerify_Update = <function> defined @Interface\AddOns\MonolithDKP\TableFunctions.lua:664
 GetPlayerDKP = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:251
 BidTimer = <unnamed> {
 }
 Print = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:311
 LootHistory_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\LootHistory.lua:321
 UpdateSeeds = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:241
 DKPTable_Headers = MonDKPDKPTableHeaders {
 }
 DKPTable = MonDKPDisplayScrollFrame {
 }
 DKPHisto
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdvancedInterfaceOptions, v1.3.2
  Atlas, vv1.45.01.11302
  AtlasClassicWoW, vv1.45.00.11302.05
  AtlasLootClassic, vv1.1.11
  AtlasLootClassicMaps, vv1.0.0
  AucAdvanced, v8.2.6420 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AuctionFaster, v1.13.4
  BagBrother, v
  BagFreeSpaceCounter, v1.0.2
  Bagnon, v8.2.13
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BiSTracker, v1.2 
  ClassicCastbars, vv1.0.6
  ClassicCastbarsOptions, v
  ClassicSpellActivations, v
  DBMCore, v1.13.9
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6411 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.2
  Informant, v8.2.6374 (SwimmingSeadragon)
  MapCoords, v0.31c
  MaxCam, vv2.4.2
  Molinari, v80200.63-Release
  MonolithDKP, v1.4.4
  OmniCC, v8.2.4
  Prat30, v3.7.36
  Prat30Libraries, v
  Quester, v1.13.2.1
  RealMobHealth, v2.11
  RotationMaster, v1.1.2
  ShadowedUnitFrames, vv4.2-Classic-Beta7
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomCats, v0.0.2
  TomTom, vv80200-1.0.7
  WeaponSwingTimer, v4.1.0
  WhatsTraining, v1.8.4
  ZygorGuidesViewerClassic, v1.0
  BlizRuntimeLib_ruRU v1.13.2.11302 <none>
  (ck=607)

**Comment by custodian** [comment]
try this version https://github.com/custodian/MonolithDKP/tree/voodoo-release

**Comment by iceslash** [comment]
> try this version https://github.com/custodian/MonolithDKP/tree/voodoo-release

Hello, the addon isn't showing on the character's list.  Can you help with that?

**Comment by custodian** [comment]
@iceslash after extracting, you need to rename folder from "MonolithDKP-voodoo-release" to "MonolithDKP"
Make sure to backup and delete file 
```_classic_\WTF\Account\[Your account name]\SavedVariables\MonolithDKP.lua```

**Comment by iceslash** [comment]
@custodian okay, another problem. logged in, typed /dkp. it's not showing me the "award dkp/item" tab. only "filters", "options", "loot history" and "dkp history" there. what can it be?

**Comment by custodian** [comment]
@iceslash thats because you haven't read mod description, i.e. you are not eligible to adjust dkp. no guild permissions.

**Comment by iceslash** [comment]
@custodian i know, that i should be officer in guild, right? what else guild permissions needed? access for guild/officer notes?

**Comment by custodian** [comment]
@iceslash as description states, you must have ```Officer Note Writing permissions```

**Comment by iceslash** [comment]
@custodian thanks! gonna try it now.

**Comment by iceslash** [comment]
@custodian hey again :) trying to add guild members to the dkp table, selecting rank "officer" to add and it's adds only 2-3 people, but we have around 15 officers. same thing with rank "trial". What can it be?

**Comment by custodian** [comment]
@iceslash as I said: if you used original MonolithDKP addon before, make sure to backup and delete file
`_classic_\WTF\Account\[Your account name]\SavedVariables\MonolithDKP.lua`

**Comment by iceslash** [comment]
@custodian didn't use it before, did backup and deleted the file, after that logged back, and the table is empty and still adding only 2-3 people.

**Comment by custodian** [comment]
@iceslash voodoo-release version will add players with certain selected ran only and not above (as the default version of the addon does). If you need to add multiple guild ranks to roster, select and add then one by one.

**Comment by custodian** [comment]
@iceslash also, make sure, that lua errors are not blocked. If you have any error, post it here.

**Comment by iceslash** [comment]
> @iceslash voodoo-release version will add players with certain selected ran only and not above (as the default version of the addon does). If you need to add multiple guild ranks to roster, select and add then one by one.

Ye, i know. But the thing is i'm trying to do it one by one, for example trying to add "officer" rank, and it adds only 3 officers from 15. Same with another ranks. Also trying to add raid member and add by the target, aren't  working :(

**Comment by Roeshambo** [comment]
I've just uploaded a preliminary attempt at localizing it for all languages. Please download the new version (1.4.6) and test it out. Make sure to delete the savedvariables file prior to launching as it may contain bad data.

**Comment by iceslash** [comment]
@Roeshambo that one is much better, but still didn't add everyone in guild, missing GM, around 5 officers and other guys. We have 154 people in guild and it adds only 113.

**Comment by custodian** [comment]
@Roeshambo your approach with FillLocalizedClassList does not work, because localized class names are different for male and female character, i.e. you either need to use non-localized class tag (as in my pull request) or mixup male female class names, i.e. FillLocalizedClassList(t_male) and FillLocalizedClassList (t2_female, true)

**Comment by Roeshambo** [comment]
Thank you custodian. I'm completely ignorant to gendered language so that concept completely evaded me and it appeared to function properly when I ran it on my german client. Very much appreciated.

**Comment by custodian** [comment]
@Roeshambo i'm preparing another pull request with language neutral boss tracking: creature id/guid instead of plain name. 
will be pulled with in a few days.

**Comment by Roeshambo** [comment]
Greatly appreciated. I was actually just working on translations for that. I've also updated the table functions so the classes aren't displayed as all caps in game.

**Comment by iceslash** [comment]
So, what the reason, that it didn't add everyone in guild to the dkp table?

**Comment by Roeshambo** [comment]
It was adding everyone behind the scenes. What was breaking was when it was attempting to display those names, it was failing to find proper class colors as it was searching for them by their English names.  Is the new build working properly for you?

**Comment by iceslash** [comment]
That one that you uploaded few hours ago? If you speaking about that one, it's didn't add GM and some other guys to the table.

**Comment by Roeshambo** [comment]
I just applied custodians pull request about an hour ago, give that a shot and let me know.

**Comment by iceslash** [comment]
Aight, thanks.

**Comment by iceslash** [comment]
In previous version it adds 113 people from 154, now only 19... Dunno why.

**Comment by iceslash** [comment]
Nvm, everything is good. Great job guys @custodian @Roeshambo . Thanks you a lot!

**Comment by Roeshambo** [comment]
@custodian I'm not familiar with Russian but I was going to utilize a FillLocalizedClassList table simply for display. Names will be stored as their English counterpart per your fix, but will be displayed within the addon with the localized table. It works. However, since I'm not familiar with the language, it will only display male class names. Is this acceptable?

**Comment by custodian** [comment]
@Roeshambo should be just fine
