### ISSUE TITLE
What would be the easiest way to start fresh?

### ISSUE THREAD

**Issue by Croctor** [Roeshambo/MonolithDKP#211]
Things got all fucky, I cant seem to sync with one of the officers, so i cant see the awards from raid while everyone else can. I have all my numbers saved in a excel sheet, so whats the cleanest way to start it fresh

**Comment by Roeshambo** [comment]
You can use the wipe tables button in the options tab which will clear all of your data and then you should be able to receive sync days from other officers if they're online

**Comment by Roeshambo** [comment]
Did someone in your guild do the migration already? And are you an officer?

**Comment by Croctor** [comment]
Yes, and yes I'm the GM

**Comment by Croctor** [comment]
tried clearing last night, but it still is hanging onto those missing entries from one of the officers, tried having him use the wipe tables button, and its still hanging on to those entries

**Comment by Roeshambo** [comment]
Go ahead and post your saved variables file and I'll get you rebuilt along with your character name

**Comment by Croctor** [comment]
[MonolithDKP.txt](https://github.com/Roeshambo/MonolithDKP/files/3953343/MonolithDKP.txt)

Croctor

**Comment by Croctor** [comment]
also thanks for the help m8

**Comment by Roeshambo** [comment]
I assume you don't use the loot table correct? You do everything through DKP adjustments?

**Comment by Roeshambo** [comment]
So this file looks like it's nothing but individual adjustments made by you. Do you happen to have a copy of the complete sync saved that I can repair?

**Comment by Croctor** [comment]
It doesnt look like it, Due to personal error, This is why i was trying to find the best possible way to start fresh

**Comment by Roeshambo** [comment]
Ok. Best way to do a fresh start would be to just have everyone in the guild wipe their tables. There's a button for that in the Options tab

**Comment by Croctor** [comment]
thank you so much, i think that the reason i was having so many issues was because not everyone was wiping
