### ISSUE TITLE
guild members not getting correct figures after migration

### ISSUE THREAD

**Issue by bjorheim1** [Roeshambo/MonolithDKP#215]
I've migrated to the newest version of monolithDKP, everything seems correct - despite a couple of the guildmembers figures is very messed up. I've told them to delete the addon and savedvariables, redownload and then synced but they still get messed up figures.

Any suggestions?

**Comment by Roeshambo** [comment]
Can you post your saved variables file please? One that does have the correct data.

**Comment by bjorheim1** [comment]
https://volafile.org/r/13zymmz2r

**Comment by Roeshambo** [comment]
Can you put a .txt on the end of it and post it here please. Questionable sites are firewalled at work so can't get to it

**Comment by bjorheim1** [comment]
[Blizzard_Console.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3956235/Blizzard_Console.lua.txt)

**Comment by Roeshambo** [comment]
Sorry, I should be more specific. The saved variables file I need is in WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua

**Comment by bjorheim1** [comment]
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3956349/MonolithDKP.lua.txt)

**Comment by Roeshambo** [comment]
Ok I see what's going on with it. It appears the indexing got screwed up. You most likely did the migration when 2.0 was originally released last month and then rolled back when it was having some issues. As soon as I get home I'll get that reindexed for you.

**Comment by bjorheim1** [comment]
That's correct. Thanks

**Comment by Roeshambo** [comment]
Have all of your officers back up and delete their Saved Variables files in that location (with their game client closed). So when you login with the fixed file they don't accidentally send some of those old indexes which would duplicate data.

**Comment by bjorheim1** [comment]
I will

**Comment by bjorheim1** [comment]
Hi mate

When can I expect this to be ready 🙂?



Mvh
Gymmen
/Mattis

________________________________
Fra: Roeshambo <notifications@github.com>
Sendt: torsdag 12. desember 2019 16:39
Til: Roeshambo/MonolithDKP <MonolithDKP@noreply.github.com>
Kopi: bjorheim1 <mattisbjorheim@hotmail.com>; State change <state_change@noreply.github.com>
Emne: Re: [Roeshambo/MonolithDKP] guild members not getting correct figures after migration (#215)


Have all of your officers back up and delete their Saved Variables files in that location (with their game client closed). So when you login with the fixed file they don't accidentally send some of those old indexes which would duplicate data.

**Comment by bjorheim1** [comment]
Did u forget about me? @Roeshambo

**Comment by bjorheim1** [comment]
[MonolithDKP.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3963973/MonolithDKP.lua.txt)

I have updated the dkp for thursdays raid, please fix this text file instead of the first one.

**Comment by Roeshambo** [comment]
I apologize for the delay. I decided that instead of putting out fires constantly it would be better time spent fixing the issue. A new version will be out soon that will simply be an improvement on the original broadcast system as this one appears to have too many lynch pins in it. Once that is completed, I'll offer any assistance that is required to reconcile data. Please use 1.6.3 for the time being. I'm going to close all tickets related to this issue and once the new version is released, please check back here and post a ticket if you require data to be merged manually. This will require a backed up SV file from before the migration (or just after) as well as any entries that had been created since that you'd like merged.
