### ISSUE TITLE
Do you need the {MonDKP=*****} anymore?

### ISSUE THREAD

**Issue by funkekaiser** [Roeshambo/MonolithDKP#216]
Is the new {MonDKP=*****} to sync the old version to the new one?

When I delete the {MonDKP=*****} from the gm note, the addon does not replace it when I give someone some test dkp.

So who can edit the table now, still the officers who can edit the public note? And can I delete the ugly {MonDKP=*****}?

**Comment by Roeshambo** [comment]
Yes you can remove it. "Edit Officer Note" permissions within the guild manager is what determines if someone has officer privileges in the addon. It's no longer used for anything past the initial migration.

**Comment by funkekaiser** [comment]
thx
