### ISSUE TITLE
Double Migration happened - way for you to clean our data?

### ISSUE THREAD

**Issue by Leanback1318** [Roeshambo/MonolithDKP#217]
Hi Roeshambo, 

sadly one of our officers who wasn't active in the past and then came back, just updated monolithDKP and afterwards nominated himself to be the "migration" officer because of whatever reason. 

Now we have many of our data as "doubles" and the whole DKP table is destroyed. 

The data from the person "Hamburg" should have been removed if possible and if you can help with how to make the new file the "main data center". 

Thanks in advance. 
[AwakenPatchwerk.lua.txt](https://github.com/Roeshambo/MonolithDKP/files/3957255/AwakenPatchwerk.lua.txt)

P.S. Migration went perfect, since I missed as guild lead the first 2.0.x update and never migrated before, but afterwards this happend.

**Comment by Roeshambo** [comment]
Not a problem. As soon as I get home I'll get this fixed up for you. Once I do remigrate it, everyone in your guild will have to wipe their tables as all data will be reindexed. Especially your officers to prevent them from sending data that they "think" you do not have.

**Comment by Leanback1318** [comment]
Thanks in advance. 
Could you please just explain what has to be deleted and pressed ingame in the addon to wipe the data. 

Also is there a possibility to remove everyone the "officer" rank to prevent this happing when someone login without knowing?

**Comment by Roeshambo** [comment]
I rerun the migration process with additional scripts that takes care of duplicated data and reindexes each entry sequentially. Officer rank is determined by the "Edit Officer Note" permission within the guild settings. If you simply remove that permission from that rank and have any officers that were online when you do so relog, when they open the DKP window they should no longer see the adjust or manage tabs.

**Comment by Leanback1318** [comment]
I see, thank you for clarification. For your records, "Eislutscher" is the name of the Guildmaster and that's my account with whom I would do the reset.

**Comment by Roeshambo** [comment]
Any chance you could get a saved variables file from someone that has all names visible on their DKP GUI? I rebuilt yours. But it looks like all of the profiles were somehow deleted and I can't recreate them unless I'm in their guild :p

**Comment by Roeshambo** [comment]
If that's not possible I can tell you how to rebuild them.

**Comment by Baeumla** [comment]
Can you tell us how to rebuild it? I'm in the guild atm and I was thinking about coding an own parser to rebuild the database.

**Comment by Roeshambo** [comment]
No need. There is a function in the addon that rebuilds the database. I'll just get this reindexed for you and then you can do it

**Comment by Roeshambo** [comment]
Sorry about the delay. You're going to want to make sure no officers log in with old data. And make sure you don't log in with this and then have an officer log in with old data. Or they'll just send it back to you. Best to just give this file to all of the officers and then once all officers have it, then you can log in with it. To rebuild the DB, you're going to add all of the players to the DKP table like normal (manage tab) and then right click on someone and at the bottom you'll see "Validate Tables". It'll take a few minutes to run. But it'll rebuild everyone's DKP based off of their history.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3958775/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
You're probably going to get an out of date indicator for a while. Everyone in the guild must wipe their tables and download the new data from officers. Once they aren't reporting those missing entries it'll correct itself.

**Comment by Leanback1318** [comment]
I have now tried yours, some of the data was still missing or not correct. 

So in the end, we have screenshots with the raw DKP numbers, which should be somehow enough. 

Is there a possibility to somehow get a "clean restart" so that I just make a member list and add all DKP manually and everyone synch only this? 
We could live with loosing DKP/Loot history, but the current status quo is a little bit stressing. 

Thanks in advance.

**Comment by Roeshambo** [comment]
I apologize for the delay. I decided that instead of putting out fires constantly it would be better time spent fixing the issue. A new version will be out soon that will simply be an improvement on the original broadcast system as this one appears to have too many lynch pins in it. Once that is completed, I'll offer any assistance that is required to reconcile data. Please use 1.6.3 for the time being. I'm going to close all tickets related to this issue and once the new version is released, please check back here and post a ticket if you require data to be merged manually. This will require a backed up SV file from before the migration (or just after) as well as any entries that had been created since that you'd like merged.
