### ISSUE TITLE
/dkp causing lua errors

### ISSUE THREAD

**Issue by Dezcarath** [Roeshambo/MonolithDKP#221]
Hi Roeshambo, 

Monolith DKP is loading fine and I'm able to bring up other backslash commands, however when I use /dkp to bring up our guildies totals I keep getting lua errors. Would you have a solution to this because I'm out of my element when fixing these.

**Comment by Roeshambo** [comment]
Can you post what errors you're getting? If there are multiple (arrows on the bottom), the first one is usually the most helpful.

**Comment by Dezcarath** [comment]
I copied it all, I hope its not too much.
Date: 2019-12-12 19:38:22
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\MonolithDKP\init.lua line 270:
   attempt to index field 'DKP' (a nil value)
Debug:
   MonolithDKP\init.lua:270:
      MonolithDKP\init.lua:248
Locals:
(*temporary) = nil
(*temporary) = "Earthenbull"
(*temporary) = "player"
(*temporary) = "Earthenbull"
(*temporary) = nil
(*temporary) = <function> defined @Interface\AddOns\DBM-Core\Libs\AceComm-3.0\AceComm-3.0.lua:87
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 baseName = "MonolithDKP"
 EnableModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 IsModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 UnregisterComm = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 defaultModuleLibraries = <table> {
 }
 SendData = <function> defined @Interface\AddOns\MonolithDKP\Modules\comm.lua:1779
 UnregisterAllComm = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 OnCommReceived = <function> defined @Interface\AddOns\MonolithDKP\Modules\comm.lua:528
 enabledState = true
 OnEnable = <function> defined @Interface\AddOns\MonolithDKP\Modules\comm.lua:482
 SendCommMessage = <function> defined @Interface\AddOns\DBM-Core\Libs\AceComm-3.0\AceComm-3.0.lua:87
 RegisterComm = <function> defined @Interface\AddOns\DBM-Core\Libs\AceComm-3.0\AceComm-3.0.lua:60
 GetName = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 defaultModuleState = true
 Disable = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 IterateModules = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
 name = "MonDKP"
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 IsEnabled = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:387
 DisableModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
}
(*temporary) = "MDKPQuery"
(*temporary) = "start"
(*temporary) = "GUILD"
(*temporary) = nil
(*temporary) = "NORMAL"
(*temporary) = nil
(*temporary) = nil
(*temporary) = 5
(*temporary) = 255
(*temporary) = "attempt to index field 'DKP' (a nil value)"
MonDKP = <table> {
 CurrentIndex_Set = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:804
 DKPHistory_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:262
 StartTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:467
 MigrationFrame = <function> defined @Interface\AddOns\MonolithDKP\Modules\Migration.lua:211
 StartBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:714
 ValidateDKPTable_DKP = <function> defined @Interface\AddOns\MonolithDKP\Modules\Validate.lua:200
 PurgeDKPHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:344
 RaidTimerPopout = MonDKP_RaidTimerPopout {
 }
 SortLootTable = <function> defined @Interface\AddOns\MonolithDKP\Modules\LootHistory.lua:11
 ConfigTab3 = <unnamed> {
 }
 UIConfig = MonDKPConfig {
 }
 GetGuildRankGroup = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:208
 BroadcastTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:428
 ConfigTab6 = <unnamed> {
 }
 RequestSync = <function> defined @Interface\AddOns\MonolithDKP\Modules\comm.lua:399
 ClassGraph = <function> defined @Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:7
 BroadcastStopBidTimer = <function> defined @Inter

**Comment by Roeshambo** [comment]
Looks like your Meta table is corrupted. Can you please post your saved variables file. It's located @ WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua

**Comment by Dezcarath** [comment]
I cant post or open a lua file

**Comment by Roeshambo** [comment]
copy it to your desktop and put .txt on the end of it. then post that.

**Comment by Dezcarath** [comment]
I'm still having trouble. I had changed the name to include .txt but it's still not letting me

**Comment by Roeshambo** [comment]
Should be able to drag and drop into the chat box. Is it giving you an error?

**Comment by Dezcarath** [comment]
I can open it in word, though its a 32 page document.

Yes, it's saying it doesn't support the file type.

**Comment by Roeshambo** [comment]
Ah ok. You're probably not showing file extensions. If you can zip it you can post it with that format.

**Comment by Dezcarath** [comment]
[MonolithDKP.txt.zip](https://github.com/Roeshambo/MonolithDKP/files/3958504/MonolithDKP.txt.zip)

**Comment by Roeshambo** [comment]
Replace your MonolithDKP.lua file that you just sent me with the file in this Zip. Make sure your WoW client is completely closed when you do or else it won't take.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3958536/MonolithDKP.zip)

**Comment by Dezcarath** [comment]
whew yes that worked, thank you so much!

**Comment by Roeshambo** [comment]
No problem.
