### ISSUE TITLE
Issue With Multiple Loot Masters

### ISSUE THREAD

**Issue by alatterner** [Roeshambo/MonolithDKP#222]
Hi again!

For reference, we have 3 raids that run on different times. Last night, we had one of our raids (not mine) run with a different loot master (who is whitelisted). They did the full night and added DKP/did bids, etc. Business as usual.

Just now, I logged in to sync with last night's loot master (as ours is happening today). It seems that they ended up just syncing with mine? They didn't touch the button or anything. They ended up losing all of their entries from last night. I'm wondering if it ended up just having my records (without last night's information) overwrite hers?

**Comment by Roeshambo** [comment]
Nope. There is nothing that overwrites files as all indexes are based on the individual that created them. When you sync, the only thing you do is send what others are missing or receive what you're missing. There is no deleting.

**Comment by alatterner** [comment]
So we found someone who had a previous version of the file and haven't logged on. We're using their saved variables as what our data should look like.

I backed up the old version and placed their file in my savedvariables folder. When I log in, I see the values from last night. however, shortly after logging on, it remerges with everyone else and the entries are gone again (within a minute).

After closing the game and looking back in the savedvariables file (as me closing the game forces the write) and the values are no longer in there. It goes back to the old version without last night's values.

While I understand you say there's no deleting, I'm seeing deleting.

**Comment by Roeshambo** [comment]
Do you play from two separate computers?

**Comment by alatterner** [comment]
No I do not.

**Comment by Roeshambo** [comment]
The absolute only way entries can be deleted is if an officer logs in and essentially tells you entries you have shouldn't exist (IE: You have indexes for OfficerA that go up to 200 and OfficerA logs in and their Meta tables say he's only created 190). I'm wondering if perhaps the officer that created the entries has played from two different computers. Because his meta would increment for the entries they created on one computer, but it wouldn't be reflected on the other computer.

**Comment by alatterner** [comment]
I checked with the other loot master and she doesn't play from 2 computers. Our guild master does so I'm not sure if he's messing with us? But we shouldn't be updating from him,.

**Comment by Roeshambo** [comment]
Nope. Only the individual the entry is indexed as can tell another player to delete an entry.

**Comment by Roeshambo** [comment]
A new version will be out soon that should correct any issues experienced with the new system. It will be 2.0 with a variant on the original broadcast system (improved of course) as that one didn't cause these issues. After that is released, if you need assistance with data please post another ticket.
