### ISSUE TITLE
please help with our dkp table

### ISSUE THREAD

**Issue by junsunmin** [Roeshambo/MonolithDKP#234]
Great Great addon. Thank you for all your hard work.
when 2.0 came we ranked down our officer in order to avoid migration issue.
and our GM "misclicked" and we got messed up table. i had to delete all the double entries by hand in addon. it worked fine until we went back to 1.6.3. now it wont sync anymore.
and we tried to sync with warcraftdkp website and its all mess there because of migration issue.
is there anyway to clean up the lua file?
here is our lua and what dkp should be.
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3965806/MonolithDKP.zip)
https://docs.google.com/spreadsheets/d/194_8UDqTG3H452UceBsB76QFzG55YuBMxobkGjllxR4/edit#gid=0

**Comment by Roeshambo** [comment]
Your file looks like it should work just fine in 1.6.3. There is no "sync" functionality in 1.6.3. It was new to 2.0 and didn't work so well for some. I will be releasing a new version very soon (hopefully tomorrow) that will help w/ the issue. When that comes out, you will simply be able to manually adjust everyones DKP that has incorrect data.
