### ISSUE TITLE
Raid tuesday please help!

### ISSUE THREAD

**Issue by Harskare** [Roeshambo/MonolithDKP#235]
Hello! i understand that with the migration it has been super busy trying to come up with a formula to fix the duplicate officer "syncing" I've been searching for formulas to delete every "Nth" line in file but have had no luck so far. Please let me know if  you can help me sort out this file before my raid on tues. day to avoid all in guild chaos! Thank you! Harskare -Whitemane
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3966930/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
Is this an accurate representation of their actual DKP?
![image](https://user-images.githubusercontent.com/6285297/70957345-779a9480-203b-11ea-8563-fdee097442dd.png)

**Comment by Harskare** [comment]
The history looks correct however the top 2 dkp were "perkys" and "yip" at around 730 give or take 80 due to the most recent raid and we did not have anybody in negative

**Comment by Harskare** [comment]
any index from "sevan" are duplicates from what i can see in the file for what it is worth

**Comment by Roeshambo** [comment]
![image](https://user-images.githubusercontent.com/6285297/70957707-94839780-203c-11ea-8d27-34584c5c5851.png)

**Comment by Roeshambo** [comment]
If this is correct, the file is attached below. Please use 1.6.3 with this until 2.1 is released as the indexing is different and might not work properly with 2.0.6
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3971066/MonolithDKP.zip)

**Comment by Harskare** [comment]
YOU ARE A MIRACLE WORKER THANK YOU SO MUCH;!!
