### ISSUE TITLE
Githut Source doesn't match Curse Download

### ISSUE THREAD

**Issue by XScorpion2** [Roeshambo/MonolithDKP#236]
I'm using the source repository here locally in Classic WoW which is listed as v2.0.5, several of my officers are using the download from Curse Forge which is listed as v2.0.6. Any word on if this repo will be updated with the v2.0.6 source?

**Comment by Roeshambo** [comment]
I'm updating within a day or two to 2.1. The 2.0.6 update is not reflected on here due to issues with the version. 2.0.6 is available on curse in the Archived files.

**Comment by XScorpion2** [comment]
Great, thanks for the info. Love the code base, super clean.
