### ISSUE TITLE
DKP and loot history not displaying the correct data

### ISSUE THREAD

**Issue by Alibader84** [Roeshambo/MonolithDKP#237]
Hi, When I open the addon to see the current DKP of the guild I get is an uncompleted table where the DKP and changes are the same. When I take a look at history it goes a few days back and no more. I tried to clear tables and try to update it and had the DKP officer to update my tables and no changes. It seems only I got this issue the DKP officer and other guild members are working fine.
Regards,

**Comment by Roeshambo** [comment]
If your data is incorrect, delete your saved variables file and get all new data from your officers. SavedVariables are located at WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua
