### ISSUE TITLE
Newest Version

### ISSUE THREAD

**Issue by ramboozer** [Roeshambo/MonolithDKP#238]
Hey sorry if this is a stupid question. But I last updated Monolith DKP I sware through twitch client to version 2.0.4 I believe it was. Got a few new people in our guild and I tried to tell them to download that version and all they say they see is version 1.6.3 on Twitch. I haven't been able to find a 2.x.x version anywhere.
Attached is a screenshot of my Twitch Client looking @ Versions
https://puu.sh/EQ9Mb/bb3eb0aed7.png

**Comment by joheri85** [comment]
Its rolled back cause of sync not working as it should. You have to download the git version if you want 2.0.x
