### ISSUE TITLE
post-merge issue

### ISSUE THREAD

**Issue by Ezekaile** [Roeshambo/MonolithDKP#239]
I was the person who initiated a merge and after that some of my guildies records are different from mine. Savedvariables included
For example the officer who has the "core" table is Эзекиль (me) in my addon it says 535 DKP, and some of the member has it at 525

[member - Эйнауди.zip](https://github.com/Roeshambo/MonolithDKP/files/3973693/member.-.zip)

[Officer - Эзекиль.zip](https://github.com/Roeshambo/MonolithDKP/files/3973704/Officer.-.zip)

Thanks in advance

**Comment by Roeshambo** [comment]
Those SV files don't contain any information relevant to the addon (Addon SVs are located at WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua). With regards to your issue, what merge did you use? Was it the merge in 2.1? If so the 2.1 merge does not broadcast any entries created prior to the installation of 2.1. It also is not compatible with earlier versions.

**Comment by Ezekaile** [comment]
[Officer.zip](https://github.com/Roeshambo/MonolithDKP/files/3973863/Officer.zip)
[member.zip](https://github.com/Roeshambo/MonolithDKP/files/3973870/member.zip)

Thanks for the fast reply!
I'll send correct SVs in a few, sorry about that.
And it was 2.0.6 merge i used

**Comment by Roeshambo** [comment]
Ok. Ya 2.0.6 has been having some issues unfortunately. I just uploaded 2.1.0 which abandons the iffy sync system. I would recommend using that and have the individual with the most accurate SV file broadcast it to everyone else so they're on the same page.
