### ISSUE TITLE
Bad argument on 2.1.0

### ISSUE THREAD

**Issue by joheri85** [Roeshambo/MonolithDKP#240]
im getting this when updating from 2.0.6 to latest version:

![image](https://user-images.githubusercontent.com/58121029/71008524-0addd380-20e9-11ea-96b7-d75e6f3698b2.png)

![image](https://user-images.githubusercontent.com/58121029/71008496-01546b80-20e9-11ea-9f5e-051791665f8d.png)

**Comment by Roeshambo** [comment]
Yes, go ahead and update to 2.1 on curse. Fixed it but haven't uploaded to the repository just yet.

**Comment by joheri85** [comment]
ah yes, works. Thx
