### ISSUE TITLE
New Broadcast system and notifys

### ISSUE THREAD

**Issue by Ganktimebaby** [Roeshambo/MonolithDKP#241]
Broadcast to: 

Player gives me only one option A-T but we have many more online -_-

And other Players Reciving no Broadcasts. I Have the version 2.1.0 guid members over 2.0.

And i become no notify messages after updating or any other action
selected already Addon Notifications to all channels :(

**Comment by Roeshambo** [comment]
2.1 is not compatible with 2.0 as the broadcast system was changed. Many were having issues with 2.0s sync system. All must either be on 2.0 or 2.1. Additionally, the list of players online only displays the players that are on the DKP list.

**Comment by Ganktimebaby** [comment]
Ok Check!
