### ISSUE TITLE
Bid Screen not showing

### ISSUE THREAD

**Issue by Squigglymoo** [Roeshambo/MonolithDKP#243]
When in the raid and the Loot Master sends out the loot, the bid table is not opening. I have upgraded to 2.1.0 from this website, however, he has not...would this be why?

**Comment by ThaCow** [comment]
Is the problem that the current bids are not showing?
Because I had a similiar problem and the problem was that I had not wiped the dkp table after updating to 2.x

**Comment by Roeshambo** [comment]
It's most likely that you're on 2.1 and the raid leader is on 2.0. The two are not compatible. All must be on 2.0 or 2.1

**Comment by Squigglymoo** [comment]
Okay, i will get him to update later, Me and the GM always test any DKP update to make sure everything working perfectly before allowing our Guild to update the addon lol...dont want to lose all the information. Thank you for your quick reply.

**Comment by Roeshambo** [comment]
The new update reverts back to the broadcast system used in 1.6 because several guilds were having issues with 2.0 sync system. Though it's improved quite a bit. Posted a video regarding it on curse

**Comment by Squigglymoo** [comment]
Only broadcast system changed, we still get that special bidding screen?

**Comment by Roeshambo** [comment]
It's 2.0 with a spiced up version of 1.6 broadcast (status button in the bottom left opens broadcast ui to send data)

**Comment by Squigglymoo** [comment]
Sounds great, any reported problems or safe just to get everyone to update?

**Comment by Roeshambo** [comment]
Shouldn't be any problems. All of the problems reported were with the 2.0 sync system which has been scraped

**Comment by Roeshambo** [comment]
Only difference between 2.1 and 1.6 is a broadcast UI to select who the broadcast is sent to (if you want to send it to a specific person or to the whole guild) as well as what to send. Full broadcast is the exact same as the broadcast button in 1.6, sends all tables and gives recipient identical copies of your tables. Merge last 2 weeks sends entries created in the last two weeks and applies only what the recipient doesn't have (used for multi raid guilds that need to merge data from separate raids).
