### ISSUE TITLE
1.6.3 doesn't seem to auto-add DKP after boss kills or after time passed

### ISSUE THREAD

**Issue by hansendevdk** [Roeshambo/MonolithDKP#246]
I know you're probably no longer supporting 1.6.3. But after our last failed migration we're a bit hesitant about moving to 2.1 until we know everything is stable. But with 1.6.3 we're having issues with the auto-awarding of DKP. I can start the raid just fine and everyone get their on-time bonus, but the remainder of the DKP that should be awarded isn't awarded. So we have to add it manually after every raid. 

Do you have any idea what might be causing this?

**Comment by Roeshambo** [comment]
Only the raid leader distributes dkp with automatic functions (or else all officers would causing duplicates). Make sure the raid leader has the timer going and has the auto award option checked in the modes window. Should broadcast those settings to everyone to make sure everyone is on the same settings
