### ISSUE TITLE
Incorrectly considers DKP addon

### ISSUE THREAD

**Issue by tornadoff** [Roeshambo/MonolithDKP#247]
Hi man.
In our table, the program does not correctly consider DKP.
Screenshots example: Ce got 1090 DPK on full and spend 170 = mast be 920. Why addon show 955?

This problem is for many. The total sum is not correct when the spent is subtracted from the total number.
Why it's happening?

![WoWScrnShot_121919_233617](https://user-images.githubusercontent.com/36474049/71200001-fd774380-22b8-11ea-8ce7-cf00a88769fe.jpg)

**Comment by tornadoff** [comment]
![WoWScrnShot_121919_234250](https://user-images.githubusercontent.com/36474049/71200215-77a7c800-22b9-11ea-987f-fd7061d96596.jpg)
![WoWScrnShot_121919_234255](https://user-images.githubusercontent.com/36474049/71200219-7aa2b880-22b9-11ea-99ad-afd4e03a4c1c.jpg)

**Comment by tornadoff** [comment]
U can see than not only one man in table with this problem. addon incorrectly considers the total number.

**Comment by Roeshambo** [comment]
When you deduct points it doesn't remove that from the lifetime earned. When you award points it adds it to the lifetime earned and only subtracts from it when an item cost is refunded or an entry is deleted. There's no way to be 100% accurate with it because the add-on has no way of telling if you're subtracting points as a correction or as a penalty.

**Comment by Roeshambo** [comment]
There is a validate tables option in the right click menu but I would highly recommend backing up the tables before doing so. It'll add up all values so they're accurate. But if you're missing some history entries somehow, it can't consider those

**Comment by tornadoff** [comment]
All of our members have "-1% DKP Migration Correction"   and they have it two time. It's normal? 
![77c6b54306ff6b69fab4b8bdc275a1f4](https://user-images.githubusercontent.com/36474049/71205009-577d0680-22c3-11ea-884d-43e25f5ecf1b.png)

**Comment by Roeshambo** [comment]
The -1% is arbitrary and it should be hidden. Not sure why it's showing for you. That was a correction made during the migration process so the history properly matched their dkp.

**Comment by tornadoff** [comment]
This show only when i use Filter for member. Without filter i don't see this -1%

**Comment by Roeshambo** [comment]
Ah ok. I'll have to filter that out. Basically in the migration, lets say a player had 100 DKP on the table. But their history only added up to 90DKP. It assumed that was because a history entry got lost somehow due to the clunky way tables were broadcasted in earlier versions. So it created a new entry giving that person 10DKP in the history to compensate. So if you validated the tables it would add up properly.

**Comment by tornadoff** [comment]
For exaple:
I counted by hand. the Ce character earned 1090 DPK for all raids and addon indicates the correct number. 170 DPK was spent on things, and he also correctly displays this number. Why, then, the final number is 955. 1090-170 = 920. Where did he get another 35 DPK? They are not anywhere. There were no cons, there was no adjustment of things.

**Comment by Roeshambo** [comment]
In the example above where you showed the -1% entry. I see you've got a couple entries where you charged DKP for items but it's in the DKP History. Those would not be attributed to DKP spent and would not reduce DKP earned either. It's likely some combination of that. When you give someone DKP, it adds that to their DKP earned. When you award an item through the award item function, it adds that number to DKP spent. Those are the only 2 scenarios in which the number is adjusted (aside from deleting entries). The numbers are not added up each time and compared. That would cause an unbelievable amount of lag for you and possibly even a crash.

**Comment by tornadoff** [comment]
I deleted the migration adjustment and for some people the numbers are correct.
As I understand it: only “+” digits are written in green, what is transmitted as a thing is written in red.
Then where is the "-" which I give through the "others" function is written? For example, someone wipe raid and I want to record -50 DKP. As a result, an adjustment occurred, but it was not displayed anywhere?

**Comment by Roeshambo** [comment]
When you deduct dkp it will show it in the dkp history in red. Positive numbers are displayed as green

**Comment by Roeshambo** [comment]
All DKP modifications will be displayed in the DKP history. Loot History logs items that are awarded through the bidding system or with /dkp award [item]

**Comment by Roeshambo** [comment]
If you continue to have issues please let me know.
