### ISSUE TITLE
Error when officer broadcasts enire table

### ISSUE THREAD

**Issue by marknl** [Roeshambo/MonolithDKP#248]
When another officer (i'm one myself) broadcasts the complete list, I'm receiving this error in bugSack:

```1x MonolithDKP\Modules\comm.lua:290: attempt to compare number with nil
MonolithDKP\Modules\comm.lua:290: in function `?'
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ags\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...faceBugSack\Libs\AceComm-3.0\AceComm-3.0-12.lua:218: in function `OnReceiveMultipartLast'
...faceBugSack\Libs\AceComm-3.0\AceComm-3.0-12.lua:256: in function <...faceBugSack\Libs\AceComm-3.0\AceComm-3.0.lua:246>
```

The list _is_ eventually synced, and I receive latest data. Though the above error pops up.
This error does NOT show when I delete my savedvariables file monolithdkp.lua.

Also, thank you for creating and maintaining this addon! Love it!

**Comment by Roeshambo** [comment]
Is this with 2.1?

**Comment by Roeshambo** [comment]
If it's 2.1, the error can be disregarded. That line has been removed in the next release patch since it was essentially running an unnecessary loop.

**Comment by marknl** [comment]
Yes. It's 2.1.0

Thanks for the heads up. Looking forwards to the new release!
