### ISSUE TITLE
DKP Interface not showing any names or dkp values

### ISSUE THREAD

**Issue by NathanMathews** [Roeshambo/MonolithDKP#25]
Hello, 
Our guild is using the DKP addon and everything seems to be running well. 
Except as a guild member, I am unable to view any of the DKP amounts. 

If I type /dkp, the GUI interface loads but does not show any names. 
Disabling the filters does nothing to help. 

I have tried installing different versions and disabling all other addons but nothing seems to work. The rest of the guild has no issue.

**Comment by Roeshambo** [comment]
Please download the new version on here and let me know. It should correct your issue.

**Comment by NathanMathews** [comment]
I am still having no luck. 
I tried the most up to date version and previous versions. 

The only difference is that previous versions would say the list is out of date (even if the officer pushes out the updated list) and the newer version says it's up to date.

**Comment by Roeshambo** [comment]
Turn on your lua errors with /console scriptErrors 1 and then reload your UI and open the DKP window. If an error pops, copy and paste it all here.

**Comment by NathanMathews** [comment]
Hello, 
I have followed your instructions and no error was given :/

**Comment by Roeshambo** [comment]
Can you please upload the saved variables file here (WTF\Account\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua).

**Comment by NathanMathews** [comment]
Removed.

**Comment by Roeshambo** [comment]
Your tables appear to be empty which would be why you're not displaying anything.

**Comment by Roeshambo** [comment]
Log out of WoW completely and delete those 2 files you just showed me. Then login and have someone broadcast the dkp table.

**Comment by NathanMathews** [comment]
Hello,

I followed your instructions and even got the notification 'DKP Database updated by [GM}...
However, no data is showing on the table.

**Comment by Roeshambo** [comment]
I quite honestly can't explain this without an error. The "DKP Database updated by" should only fire if you received and applied the table. Is anyone else within your guild experiencing this issue? Or is it just you?

**Comment by Roeshambo** [comment]
Additionally, are the officers that are broadcasting to you also using the most up to date version?

**Comment by NathanMathews** [comment]
It was just me with the issue. 

Good news, it is fixed. It just started working randomly. I did nothing so I have no idea what fixed the issues.

**Comment by NathanMathews** [comment]
Hello, 

It stopped working again, however it stopped working the moment the guild leader started to delete people from the list who were no longer in the guild. The moment I got the message: DKP Database Updated by... it stopped working. Does this help at all?

**Comment by NathanMathews** [comment]
Okay sorry to keep spamming this.
It seems that a /reload fixes the issue. Relogging however does not.

**Comment by Roeshambo** [comment]
I've been scouring the code and testing it in game trying to recreate this issue and can't seem to replicate it. The remove entries function (deleting players) does absolutely nothing on your end but broadcast the DKP table. Which should overwrite the entire thing. Does it only occur when a specific officer does it? Or is it when any officer broadcasts to you? A broadcast should update your window immediately and not require a reload. (as far as addons are concerned, a /reload and relogging are the exact same thing)

**Comment by cbk5** [comment]
FWIW, we encountered identical issues earlier this week. The fix for us was to get EVERYONE updated to the same version, as Roeshambo suggested.

**Comment by Roeshambo** [comment]
Please let me know if this issue must be reevaluated.
