### ISSUE TITLE
Request: Move the timestamp to "Guild Info"

### ISSUE THREAD

**Issue by soosticus** [Roeshambo/MonolithDKP#250]
Rather than storing the timestamp in the Guild Leader's public note, it could instead be stored somewhere in the guild info, such as on the last line, with a disclaimer to not modify that line.

This would make it less risky to allow non-officers to modify public notes. and open it up for other fun info.

I'm not sure how doable this is, but I do remember 'dkp (reloaded)' doing something similar for storing epgp values back in the day.

**Comment by Roeshambo** [comment]
In 2.1 the timestamp has been removed entirely. Rather than storing it in the game at all it's stored as a "seed" in everyones DKP and Loot history tables. On login it's automatically propagated to the rest of the guild.

**Comment by soosticus** [comment]
Fantastic!
