### ISSUE TITLE
Max bids submitted through new window are rejected

### ISSUE THREAD

**Issue by lwatkins** [Roeshambo/MonolithDKP#251]
In our last raid, we had multiple people trying to use the new bidding window to bid their max DKP using the MAX button but it failed (just MAX and then Submit Bid). They receive an error message such as "Bid Denied! You only have 4259.85 DKP", even though they are using the bidding window's MAX button and that amount matches what we see in the addon. As master looter, I see nothing come through (since it was denied).

**Comment by Roeshambo** [comment]
I have a feeling I know why that is. The wow API enjoys taking round numbers and giving them ridiculous decimals. While they were sending 4259.85 dkp the API was likely reading it as something closer to 4259.8514325803158 or something like that. If I can't find a numeric work around I'll just use a Max command

**Comment by Roeshambo** [comment]
Make sure your mode settings are broadcasted. If you have 2 decimal places set, everyone in the raid must have theirs set by you as well or they will be rounding up to 4260. 0 decimal places is the default unless changed by an officer. You can set up a mock bid by making a raid with one of those players and create a bid with an item in your inventory. Test it and then broadcast your mode settings and test again. If it works, that was the reason

**Comment by Roeshambo** [comment]
Ensured all transmitted values are rounded per the officers settings (must be broadcasted to raid). If the broadcast was not your issue please let me know.

**Comment by lwatkins** [comment]
I broadcast the values to one of the affected people,  and it did allow them to bid correctly. Is there a way to sync that setting, at least during initial migration/setup? Otherwise we'd need to broadcast from within the settings menu each raid where a new person has joined.

**Comment by Roeshambo** [comment]
At the moment it's not automatically broadcasted no. I've been trying to consider a good way to do that without causing issues. (IE: What if you set certain settings then another officer auto broadcasts their data which is different than yours shortly after, etc) It could cascade into a mess. If I can figure out a surefire way to do it w/o causing problems I will.

**Comment by lwatkins** [comment]
That'd be great, if you can work out a way. Appreciate the addon.
