### ISSUE TITLE
DKP not updating and says up to date with no option to clear tables

### ISSUE THREAD

**Issue by Dalwebb** [Roeshambo/MonolithDKP#252]
I've tried uninstalling and reinstalling but the last recorded transaction is December 2nd and I've had problems ever since. One other guild mate is having the same problem. We've tried syncing and no success. It seems to be totally broken with no way of resetting.

**Comment by Roeshambo** [comment]
Ya it's a bit of an issue that plagued 2.0 which is why it was pulled down. 2.1 was posted and doesn't include the sync system (essentially rolled back to the old broadcast system with some improvements for usability). I would recommend moving your guild to that.
