### ISSUE TITLE
nil comparison error at comm.lua:290

### ISSUE THREAD

**Issue by atshane253** [Roeshambo/MonolithDKP#255]
raid leader called out that he was updating dkp and then it died.  was not in combat

Message: Interface\AddOns\MonolithDKP\Modules\comm.lua:290: attempt to compare two nil values
Time: Fri Dec 20 19:40:13 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\Modules\comm.lua:290: attempt to compare two nil values
Interface\AddOns\MonolithDKP\Modules\comm.lua:290: in function `?'
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...s\ClassicThreatMeter\lib\AceComm-3.0\AceComm-3.0.lua:218: in function `OnReceiveMultipartLast'
...s\ClassicThreatMeter\lib\AceComm-3.0\AceComm-3.0.lua:256: in function <...s\ClassicThreatMeter\lib\AceComm-3.0\AceComm-3.0.lua:246>

Locals: <none>

**Comment by Roeshambo** [comment]
Was this version 2.1? That error wouldn't make sense unless there was something before it. That's just a sort command for the received data.

**Comment by Roeshambo** [comment]
Is this 2.1? If it was, you can disregard this error. That section was irrelevant and wont be there in the release of 2.1 shortly. You would have still gotten the broadcast anyway.

**Comment by atshane253** [comment]
yeah, 2.1 from twitch app
