### ISSUE TITLE
Corrupted SV files.

### ISSUE THREAD

**Issue by Unlokhe** [Roeshambo/MonolithDKP#256]
[Errors.txt](https://github.com/Roeshambo/MonolithDKP/files/3991857/Errors.txt)
[SV.zip](https://github.com/Roeshambo/MonolithDKP/files/3991863/SV.zip)

**Comment by Roeshambo** [comment]
Go ahead and download 2.1.1. Should fix your problem. For future reference, the SV files you need are at WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua. But that error won't show in 2.1.1

**Comment by Unlokhe** [comment]
Oh, there are THREE folders all named the same thing... That's not confusing at all *roll eyes*. Thanks again, your support of this addon goes far beyond what one could expect.
