### ISSUE TITLE
dkp table total sum off by 5

### ISSUE THREAD

**Issue by Djfe** [Roeshambo/MonolithDKP#258]
He is new to the raid.
55 dkp in the table (correct value)
50 dkp total lifetime in the sum, even though it's 55
![WowClassic_2019-12-22_20-32-47](https://user-images.githubusercontent.com/5685512/71326812-6c92a900-2500-11ea-9eef-5c42970e4961.png)

version 2.1.1

**Comment by Roeshambo** [comment]
Curious... Any chance you happened to notice which entry didn't add to their lifetime earned? Every one of those are added with the same function with an exception of 1 (on time bonus). And that function absolutely adds the dkp awarded to lifetime gained. I'll have to poke around with that one.

**Comment by Roeshambo** [comment]
Ah, figured it out. The initial entry didn't add to it. Next patch will contain a fix. The officer that distributed the DKP would have an accurate number. You can ask him to broadcast his tables to you as a full broadcast.
