### ISSUE TITLE
Allow Bidding with Negative DKP

### ISSUE THREAD

**Issue by cbk5** [Roeshambo/MonolithDKP#26]
I would appreciate a feature to allow bidding with negative DKP. Druids get a lot of loot, leading to very negative DKP when using fixed-price. Our workaround is to give the person in question bonus DKP that is then taken away after they bid, but this is cumbersome and clutters the log.

**Comment by Roeshambo** [comment]
I can probably add that as an option.

**Comment by Roeshambo** [comment]
Added to DKP Modes window in 1.4.11. Sub Zero Bidding must be active.
