### ISSUE TITLE
Problem loading addon

### ISSUE THREAD

**Issue by Steamrollger** [Roeshambo/MonolithDKP#27]
Hi so i have been trying out Monolith for a bit. before our raid and the day i was going to actually run it, it stopped working and is giving me the following lua error(upon login). any idea how i can fix this ?

Message: Interface\AddOns\MonolithDKP\init.lua:293: attempt to compare nil with string
Time: Sun Sep 29 14:30:54 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\init.lua:293: attempt to compare nil with string
Interface\AddOns\MonolithDKP\init.lua:293: in function <Interface\AddOns\MonolithDKP\init.lua:292>
[C]: in function `sort'
Interface\AddOns\MonolithDKP\init.lua:292: in function `OnInitialize'
Interface\AddOns\MonolithDKP\init.lua:161: in function <Interface\AddOns\MonolithDKP\init.lua:143>

Locals: a = <table> {
 previous_dkp = 0
 lifetime_spent = 0
 lifetime_gained = 0
 dkp = 0
}
b = <table> {
 previous_dkp = 0
 player = "Dentrix"
 dkp = 0
 class = "PRIEST"
 lifetime_gained = 0
 lifetime_spent = 0
}
(*temporary) = nil
(*temporary) = "Dentrix"
(*temporary) = "attempt to compare nil with string"

**Comment by Roeshambo** [comment]
Looks like you have a corrupted table. Delete the saved variables file located at wtf\account\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua with the game closed then launch and have someone broadcast the information back to you.

the [a] comparator is missing both "player" and "class" 
Locals: a =
{
previous_dkp = 0
lifetime_spent = 0
lifetime_gained = 0
dkp = 0
}
