### ISSUE TITLE
Bid window using wrong item icon

### ISSUE THREAD

**Issue by TimCowan** [Roeshambo/MonolithDKP#276]
v2.1.2 in Classic.
The bid windows often show the wrong item icon, but the correct item name. Example here: https://i.imgur.com/g7rc7Tz.png.
Mousing over the icon would show the stats for the incorrect item, which would be some other item dropped by the same boss.
Our loot master is starting bids with /dkp bid [itemlink].

**Comment by Roeshambo** [comment]
Loot tables are automatically broadcasted by any officer that opens the loot window. All epics are broadcasted as part of the table. I'll have to look into why it might either not be broadcasting or perhaps if someone else is pushing incorrect data.
