### ISSUE TITLE
Out-of-sync

### ISSUE THREAD

**Issue by Jallis370** [Roeshambo/MonolithDKP#277]
I had problems with my data getting all jumbled up and hit the "wipe tables" button after updating the addon and now I only receive the latest changes without the rest of the context. I am unable to update the dkp tables as it says I am up-to-date and my guild master is unable to send an unpdate manually as it does so automatically. I am not the only one with a similar problem.

Why can't I receive all the data from my guild master, why can't I manually request an update and why can't my guild master send it manually?

**Comment by Roeshambo** [comment]
2.1 and higher is not compatible with 2.0. The sync system was abandoned due to several issues. Everyone must be either on 2.1 or 2.0

**Comment by Jallis370** [comment]
We are on 2.1 and not having a sync system is now causing problems..

**Comment by Roeshambo** [comment]
If everyone is on 2.1, an officer can run the repair option that is available to reconcile DKP table issues that may have been caused by 2.0. Then it's just a matter of broadcasting that corrected data to everyone else. It's treated the same way as it was in 1.6 and prior.
