### ISSUE TITLE
Chat option

### ISSUE THREAD

**Issue by jthom123** [Roeshambo/MonolithDKP#279]
When MonolithDKP is active-when typing in chat the arrow keys control the cursor in the message typing. Without Monolith DKP the arrow keys change the direction of your character. 

I can't find a way to change this in options.

**Comment by Roeshambo** [comment]
It'll be removed in the next version as it was residual addition for me. But you can remove it yourself in init.lua line 443:

```
for i = 1, NUM_CHAT_WINDOWS do
		_G["ChatFrame"..i.."EditBox"]:SetAltArrowKeyMode(false);
	end
```
You can just delete that section.

**Comment by jthom123** [comment]
Thank you!!
