### ISSUE TITLE
Issue adding guild members on classic client

### ISSUE THREAD

**Issue by drepguy** [Roeshambo/MonolithDKP#28]
We can only add paladins from our guild to this dkp tracker. We switched to english client but still same issue. We can add player by target to this addon, but only if they are not in our guild. Version 1.4.11

**Comment by drepguy** [comment]
They are visible in savevariables database, but not visible in the addon itself (MonolithDKP.lua).
We think maybe smth is wrong with the filter settings?

**Comment by Roeshambo** [comment]
Can you please turn on script errors with /console scriptErrors 1 then reload your UI and launch the addon with /dkp. If any errors are present, post them here please.

**Comment by drepguy** [comment]
Did that, no errors were listed. Now it works though. I guess there were some interferences with other addons. After deleting the whole content of the addon folder, we got all guild members in the main window. We deactivated all other addons before, but this was not enough. I dont know which addon caused this behaviour.
