### ISSUE TITLE
Change Rank for DKP Control

### ISSUE THREAD

**Issue by Leightoniuss** [Roeshambo/MonolithDKP#280]
Hello Roeshambo,

i introduced Monolith DKP to my guild around 3 months ago and can i just say i love this addon so much!

Is there a way i can change the rank for controlling DKP? during our last raid an officer Wiped the tables and then broadcasted a full broadcast to me and the guild, we lost everything, i had to get another officer to come online and push me his database. i now Backup the saved variables folder every raid to be safe but if there was a way i could take control away from officers and just give full control to me that would be great!

**Comment by DoomeD1982** [comment]
Guild Masters have the ability to whitelist officers, if it is used only officers in that list can do the dkp stuff.

**Comment by Leightoniuss** [comment]
Could you tell me how to do that please?

 ive looked through the features and cant see anything relevant

**Comment by DoomeD1982** [comment]
I am not in game, nor the guild master, but look in the Manage tab.

**Comment by Leightoniuss** [comment]
Thank you, im also not guild master but i'll ask him to look into whitlest

**Comment by DoomeD1982** [comment]
Then that is why you don't see it, it is only available to the guild master.

**Comment by DoomeD1982** [comment]
Here is what Guild Masters see

![snip](https://user-images.githubusercontent.com/58643765/72308881-3beeec80-3632-11ea-9510-5d52cbd21caf.PNG)
![snip2](https://user-images.githubusercontent.com/58643765/72308964-70fb3f00-3632-11ea-93c9-d7eb75b7f4e6.PNG)

**Comment by Roeshambo** [comment]
Permissions as an officer within the addon is determined by "Edit Officer Note" permissions within the guild manager. You can remove someone's permissions by putting them into a rank that does not have that permission checked. Alternatively you can use the whitelist, but it is semi dodgy as the data is kept locally in the savedvariables file. So anyone can easily alter it and grant themselves permission.

**Comment by Leightoniuss** [comment]
yeah completely understandable,
even with that vulnerability to permissions its still perfect for me,
just want to remove peoples rights so they dont accidentally fuck it up
rather than defense against malicious intent.

Thanks so much
