### ISSUE TITLE
Is there an easy way to change the /dkp command to something else?

### ISSUE THREAD

**Issue by hansendevdk** [Roeshambo/MonolithDKP#282]
Hey, I know this isn't an issue but I wanted to ask if you had a generic way to change the commands, or tell me where they're defined? 

Thanks in advance.

**Comment by DoomeD1982** [comment]
you could probably get away with editing the init.lua to change them, that would be on your side only though.

**Comment by Roeshambo** [comment]
The parameter commands are defined in init.lua in the table started on line 11: MonDKP.Commands
The actual /dkp command is registered on line 449
