### ISSUE TITLE
Everyone's tables are "out of date" and loot tracking is broken

### ISSUE THREAD

**Issue by cbk5** [Roeshambo/MonolithDKP#29]
Every officer in my guild's tables are "out of date." Whenever we try to broadcast, the addon tells everyone that someone is trying to broadcast tables that are out of date.

As we were running MC tonight, we found that each of us became unable to log loot awarded over the course of the night, passing master looter around until none of us were able to award loot through the addon anymore, ultimately resorting to logging everything manually. When trying to award loot, a warning message would appear informing us that we were trying to award loot against outdated tables or something similar.

The dkp status bubble in the bottom-left says out of date for everyone. I have tried deleting my saved variables and having my fellow officers re-broadcast to no avail - the very first time they broadcast, it already said they were out of date.

**Comment by Roeshambo** [comment]
That most commonly happens if someone broadcasts an out of date DKP table and everyone accepts it. You can reset what is considered "out-of-date" by removing the timestamp tag in the Guild Leaders public note. And make sure the guild leaders public note has room for the tag (preferably keep his note empty).

**Comment by Roeshambo** [comment]
Best practice to avoid that is make sure the updated DKP table is broadcasted to the entire raid at the beginning of the raid. Just to make sure no one there is able to broadcast one that is old. Also, make sure at least every officer is on an updated version. There was a change in how the seed is stored in the public note that could have caused the issue.

**Comment by Roeshambo** [comment]
No response. Assuming issue was resolved.
