### ISSUE TITLE
MonDKP_DKPTable does not sum up

### ISSUE THREAD

**Issue by luka-grabarevic** [Roeshambo/MonolithDKP#290]
Hi,

I'm currently writing a converter to be able to export MonDKP data to be imported into eqdkp-plus.
As for now I am reading out the **MonolithDKP.lua** file.
I'm not sure if my assumption is correct, but shouldn't the data in **MonDKP_DKPTable** be the same if I sum up the data from **MonDKP_DKPHistory** and **MonDKP_Loot**? We have a history going back to our first raid, so missing data should not be the issue.

For some players (mainly our first raid group) we have a difference. For example, a player has expected DKP of 645 (also shown in game),  but if I sum it up I get 670 DKP. This is a difference of 25 DKP and occurs for 36 players of our first raid group.

Is there a way to fix this? Can I edit the **MonDKP_DKPTable** manually and sync it with the other guild officers?

The file I used for testing, can be found here: [MonolithDKP.lua](https://github.com/pdluke/mon-dkp-converter/blob/implement-converter/src/DKP.Data/MonDKP/DKP.Data.MonDKP.Lib.Tests/SampleData/MonolithDKP.lua)

**Comment by Roeshambo** [comment]
When you right click on the table you'll see an option to "Validate Tables". This will go through both logs chronologically and refactor all values for each player. It is recommended you back up your SV file prior as the process is not reversible. Something else to note, if you use decays or dkp penalties, they are not reflected in the lifetime spent or gained. If you give someone 25 dkp, and then penalize them 25 DKP it will still show them as having gained 25 dkp lifetime.

**Comment by luka-grabarevic** [comment]
> If you give someone 25 dkp, and then penalize them 25 DKP it will still show them as having gained 25 dkp lifetime.

Yeah that I already figured out. But this only affects "lifetime_gained" in **MonDKP_DKPTable** and not "dkp". And "lifetime_spent" is only affected by **MonDKP_Loot** as far as I know.

I will try the "Validate Tables" in coordination with our Guild Leader to get a clean slate with our database.

Thanks for the reply.

PS: I'll close the issue if everything worked as expected.

**Comment by Roeshambo** [comment]
The table validation doesn't broadcast. It'll only change the values as needed for you. So no one else will be effected. If you back up the SV file and you don't like the results, you can simply close the game and load the backed up SV file and you're back to where you were.

**Comment by luka-grabarevic** [comment]
Thanks. This worked like a charm and everything is fine now.
