### ISSUE TITLE
How is sync working now for non officers?

### ISSUE THREAD

**Issue by c0mm0n** [Roeshambo/MonolithDKP#295]
Hi,

People used to be able to request a sync by clicking the bubble.
Seems this option is gone and they keep pinging me to push them data.

Is it the current sync system, am i missing something?

Thx

**Comment by DoomeD1982** [comment]
Officers have to sync to players now. there is no autosync in 2.1.x

**Comment by Roeshambo** [comment]
This is correct. There is no way to request data through the UI any longer. The sync system was causing catastrophic issues and had to be rolled back. Best practice is to simply have the officer with complete data broadcast at the beginning of a raid to ensure everyone has the correct data.
