### ISSUE TITLE
DKP List

### ISSUE THREAD

**Issue by Sekmoe** [Roeshambo/MonolithDKP#296]
Good evening,

does anyone know where the DKP list is stored in the WOW Classic folder?

I would like to try to keep several DKP lists in order to record several raid groups and multiple raid instances. If I know in which file the current DKP list is stored, I can always try to replace it with others.

**Comment by Roeshambo** [comment]
\WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua

**Comment by Sekmoe** [comment]
Thx for help :)
