### ISSUE TITLE
Performance issues/ Lag during raids and broadcasts

### ISSUE THREAD

**Issue by BColsey** [Roeshambo/MonolithDKP#297]
Hello, we have a guild of 500 unique users and 800 characters. we have 4 raid groups and 2 of them have overlapping schedules. When the dkp for boss kills goes out , it causes 1-3 second lag spikes for all players.

**Comment by Roeshambo** [comment]
What version are you using?

**Comment by BColsey** [comment]
2.1.2

**Comment by Roeshambo** [comment]
The packets sent during dkp distribution is pretty much as minimal as possible. Perhaps I can go about throttling the applying function. But it wouldn't change too much. We'll see what can be done. Large scale rosters tend to make it a bit rougher as it has to search through the entire table to apply values to each player.

**Comment by BColsey** [comment]
Could there be a way to apply the changes and update the tables of only the users in the raid group and then have an officer sync the changes globally after the fact?

**Comment by Roeshambo** [comment]
Not without manually editing the send script, no. I can look into possibly adding an option to limit the scope of those broadcasts.

**Comment by BColsey** [comment]
If you deem it worth while, that would be an excellent update.  If you are taking external contributions I can fork it and do the work myself.
