### ISSUE TITLE
Bidding issues.

### ISSUE THREAD

**Issue by Gombolface** [Roeshambo/MonolithDKP#3]
When creating a "Bid" for an item, most of the time said item won't show up in the bidding screen.

It'll say it's opening the bid window, but it opens, no item in it.

**Comment by Roeshambo** [comment]
How are you creating the bid window? /dkp bid item_link or shift+alt click item in loot window?

If you're opening with the /dkp bid command, make sure you link the item (shift+click) into the command and there are no trailing spaces. 
![image](https://user-images.githubusercontent.com/6285297/62826465-a67e9680-bb81-11e9-9298-c32a762fa3e1.png)

If it's still not showing the item information, please turn on LUA errors with "/console scriptErrors 1" and try again. Toss me the error if possible. It appears to be working on my end.

**Comment by Gombolface** [comment]
Message: Interface\AddOns\MonolithDKP\MonolithDKP.lua:10: attempt to call method 'IsShown' (a nil value)
Time: Sat Aug 10 23:29:26 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\MonolithDKP.lua:10: attempt to call method 'IsShown' (a nil value)
Interface\AddOns\MonolithDKP\MonolithDKP.lua:10: in function `config'
Interface\AddOns\MonolithDKP\init.lua:53: in function `?'
Interface\FrameXML\ChatFrame.lua:4606: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4267: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4303: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: self = nil
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "attempt to call method 'IsShown' (a nil value)"
core = <table> {
 BidInProgress = false
 TableNumRows = 27
 MonDKPUI = <table> {
 }
 MonDKP = <table> {
 }
 settings = <table> {
 }
 BossList = <table> {
 }
 ShowState = false
 WorkingTable = <table> {
 }
 MonVersion = "v1.0.2 (Release)"
 classFiltered = <table> {
 }
 NumLootItems = 0
 SelectedData = <table> {
 }
 SelectedRows = <table> {
 }
 classes = <table> {
 }
 TableRowHeight = 18
 currentSort = "class"
 faction = "Horde"
 IsOfficer = ""
 TableWidth = 500
 CColors = <table> {
 }
 ClassGraph = MonDKPClassIcons {
 }
}
MonDKP = <table> {
 SortDKPHistoryTable = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:23
 StartTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:304
 GetDKPSettings = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:223
 Table_Search = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:384
 StartBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:239
 SortDKPTable = <function> defined @Interface\AddOns\MonolithDKP\MonolithDKP.lua:57
 DKPTable_Set = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:462
 PurgeDKPHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:238
 Commands = <table> {
 }
 ConfigTab3 = <unnamed> {
 }
 PurgeLootHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:227
 CreateTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:339
 ConfigTab2 = <unnamed> {
 }
 GetGuildRankGroup = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:189
 GetGuildRankIndex = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:173
 ConfigTab4 = <unnamed> {
 }
 BroadcastTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:292
 ConfigMenuTabs = <function> defined @Interface\AddOns\MonolithDKP\ConfigMenuTabs.lua:110
 TableStrFind = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:423
 ConfigTab6 = <unnamed> {
 }
 SeedVerify_Update = <function> defined @Interface\AddOns\MonolithDKP\TableFunctions.lua:280
 ClassGraph = <function> defined @Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:6
 UIConfig = MonDKPConfig {
 }
 GetPlayerDKP = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:212
 BroadcastStopBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:220
 ToggleExportWindow = <function> defined @Interface\AddOns\MonolithDKP\Modules\exportDKP.lua:181
 DKPTable_Create = <function> defined @Interface\AddOns\MonolithDKP\TableFunctions.lua:239
 Options = <function> defined @Interface\AddOns\MonolithDKP\Modules\Options.lua:7
 GetGuildRank = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:142
 LootHistory_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\LootHistory.lua:232
 CreateBidWindow = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:477
 ClassGraph_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:116
 ManageEntries = <function> defined @Interface\AddOns\MonolithDKP\Modules\ManageEntries.lua:97
 OnInitialize = <function> defined @Interface\AddOns\MonolithDKP\init.lua:122
 Toggle = <function>

**Comment by Roeshambo** [comment]
This looks like an error stemming from another possible error as there is nothing wrong with that code. Are there any other errors when it occurs? (bottom of the Lua error report there is left and right arrows).

**Comment by Gombolface** [comment]
Deleting the files you suggested in other reports seems to of fixed it. I can't test it fully as none of my guild mates are online, but once they are I can provide a proper report.
