### ISSUE TITLE
Guild leaders note is always 0

### ISSUE THREAD

**Issue by funkekaiser** [Roeshambo/MonolithDKP#30]
The guild leaders note is always 0, therefore every table shows up-to-date, even if they aren't. Deleting the note and broadcasting changes it to 0 again. Manually setting it to a 10 digit number and broadcasting again sets it to 0.

**Comment by Roeshambo** [comment]
Do you have the most recent version? 1.4.12. Make sure to update as it would be posting the note in a {MonDKP=#############} format. Nothing in the new version should be setting the note to 0.

**Comment by funkekaiser** [comment]
I used the version 1.4.11. The new 1.4.12 still keeps just a "0" in the officers note. Replacing it with {MonDKP=1000000001} and broadcasting still results in a "0".

**Comment by funkekaiser** [comment]
The addon seems to not be able to write notes at all. 

I created a new guild and created a new dkp table and manually edited the guild masters note to {MonDKP=0000000000} and it showed up-to-date. Broadcasting did not change the note. When changing it to {MonDKP=0000000001} it showed out-of-date. 
Using the original dkp table, no matter what is in the GM note is, the addons always shows up-to-date.

I tried broadcasting the table, as officer and gm, when the note was empty, "0", "{MonDKP=0000000000}" and "{MonDKP=0000000001}". Non of them resulted in a changed note. The officers have the permission to edit notes.


Testing was done on the Classic Client.

**Comment by Roeshambo** [comment]
Broadcasting would not update the note. Only modifications to the table actually change the note (the seed is to keep track of the most recent changes made). I would delete your note entirely and then make a modification then undo it. Give yourself 1 DKP, for example, and then go to the DKP history tab and right click that entry and delete it. It should update the note with a valid seed.

**Comment by funkekaiser** [comment]
[Video](https://www.youtube.com/watch?v=RbxAsuUjGLg&) 

As seen here, the note is changed instant, but if edited manually stays. I will check if any other addon from my officers are interfering.

**Comment by funkekaiser** [comment]
Seems like it is some officers addon, because its workes on the empty test guild.
I will update as soon as I find the bad addon.

Thanks for helping me troubleshoot.

**Comment by Roeshambo** [comment]
Have all officers update their addon as it may be a conflict with how the addon used to handle the note.

**Comment by funkekaiser** [comment]
In fact it was an out of date version of your addon. The addon is not downward compatible.

**Comment by Roeshambo** [comment]
There was a change in how the addon stored the seed in the leaders note. It should only be a one time thing as it was to allow more flexibility with the note (leader can now keep a note with the seed appended to it rather than it encompassing his entire note).
