### ISSUE TITLE
DKP Sync showing strange values

### ISSUE THREAD

**Issue by SkillzMFG** [Roeshambo/MonolithDKP#304]
Hello,

I'm having this strange issue for quite some time now and nothing seems to fix it. Namely when I try and get my DKP tables synced by an officer in the guild, the values seem to be purely random.

Nothing adds up, the calculations are off and it seems like I'm stuck with these incorrect calculations no matter how many times I reinstall the addon. 

Since other guildmates seem to have the addon working just fine I've asked them for help and most of them recommended clearing the files from WTF folder associated with the addon, as well as reinstalling the addon itself. 

I've done all of it multiple times, did a clean reinstallation of the addon, got synced by an officer but the random numbers keep popping up. I'm at a loss here as I don't know what else to do to try and fix it. I haven't tried reinstalling the whole game, but I'll leave it as a last resort.

Here's an example of the incorrect calculations.

![example1](https://user-images.githubusercontent.com/60363772/73207933-e17f8100-4145-11ea-988b-d58deafb2ab8.png)

I have little experience with these errors so if there is something else I can attach to help you get rid of the problem, please point it out. 

Thanks in advance !

**Comment by Roeshambo** [comment]
Close your WoW client entirely and delete the SavedVariables file located at WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua (and lua.bak). The client MUST be closed entirely when you delete this. When you log back in, you should have completely empty data. Then have an officer do a full broadcast to you (not a 2 week merge broadcast). This should resolve your issues.

**Comment by SkillzMFG** [comment]
I've tried the suggested solution and the values are now in sync with everyone else in the guild. Thanks!
