### ISSUE TITLE
Bid frame/window not showing

### ISSUE THREAD

**Issue by Herrox** [Roeshambo/MonolithDKP#316]
Hi there,

We are a few in my guild to face an issue with the bid frame/window not showing (cf screenshot) with version 2.1.2
I tried:
- disabling all the addons -> not working
- disabling all the default UI features (actions bars, floating combat text...) -> not working
- deleting cache and wtf directories -> not working
- only monolithdkp enabled -> not working
- on my bank alt with the same addons -> bid frame is fully displayed

Is there any logs or thing I can do or have a loot to fix this issue?

Thanks a lot

![WoWScrnShot_020220_215033](https://user-images.githubusercontent.com/46708213/73615294-ee4d1a80-4606-11ea-8d0d-4cb8b5b05d9e.jpg)

**Comment by Roeshambo** [comment]
Are you referring to the portion of the window that shows who has bid what? If so, an officer must broadcast those modes settings to you. Then it'll show when an auction is active.

**Comment by Herrox** [comment]
Yes I was refering to this window. Appreciate the help, we finally managed to fix it with your help !
