### ISSUE TITLE
!dkp whisper does not work for 1 officer

### ISSUE THREAD

**Issue by lynxxyarly** [Roeshambo/MonolithDKP#317]
Good afternoon,

Currently using V2.1.2 and I am fully updated with the rest of the officers on dkp. I can modify and add/remove DKP, but when someone whispers me or in guild chat (!dkp) they dont get a response from me, but they do get one from any other officer.

My social status is green (online) so I'm not blocking any kind of messages. The feature was working previously, up till presumably recently. I don't know exactly when it stopped working.

I have manually deleted my .LUA from my saved variables folder, and manually deleted the monolith dkp folder from addons, then fresh reinstalled.

What is interesting, and it could just be the way the mod works now, but when I logged back in with just the add on, I had the guild data without anyone pushing it to me.

**Comment by Roeshambo** [comment]
In your /dkp modes window, make sure you have whispers selected as an open channel and reload your UI.

**Comment by lynxxyarly** [comment]
That did it. Somehow that option got changed, but didn't realize it. Thank you!
