### ISSUE TITLE
Separate tables/profiles per character.

### ISSUE THREAD

**Issue by porksandwich** [Roeshambo/MonolithDKP#324]
I recently joined a second guild on my alt that is also using monolith DKP and realized when I received broadcasts from the new guild, it simply merged the tables of both guilds into one.  

Is there a way to make the monolith addon have a per-character table?

**Comment by porksandwich** [comment]
Wiped my tables, when they repopulated it didn't mix this time.  Issue closed.

**Comment by dennyh** [comment]
Did you manage to maintain two separate tabs on your separate characters?
