### ISSUE TITLE
Recent Loot History Bug

### ISSUE THREAD

**Issue by Kilall** [Roeshambo/MonolithDKP#33]
The recent loot history when mousing over players in the dkp table contains the same bug which was fixed in the loot history. 

I think the issue is due to line 73 in TableFunctions.lua which matches with all of the content of the loot table. Entries with items containing the playername are returned as matches when the function should only check the .player part of the table.

**Comment by Roeshambo** [comment]
You're correct. MonDKP:TableStrFind should be MonDKP:Table_Search. TableStrFind searches for partial strings where Table_Search matches complete variables. Thank you.

**Comment by Roeshambo** [comment]
Fixed in update
