### ISSUE TITLE
Hourly DKP isn't applying

### ISSUE THREAD

**Issue by Fhrost0213** [Roeshambo/MonolithDKP#34]
We tried the addon last night and it worked great but the hourly bonus never applied. Not sure if I did something wrong, but after 3.5 hours it never applied at the one hour mark or at the end.

**Comment by Roeshambo** [comment]
That's unusual, I've not had any issues with it. Did you happen to have error reporting on to post? /console scriptErrors 1

**Comment by Roeshambo** [comment]
Also, were you the raid leader? And did the DKP actually not get distributed (see DKP History) or were you looking at the Bonus Awarded: section?

**Comment by Roeshambo** [comment]
I just identified the issue with that. Should be corrected in the next version push.

**Comment by Roeshambo** [comment]
Fixed in update
