### ISSUE TITLE
Communication issue when item has comma "," in name

### ISSUE THREAD

**Issue by lantisnt** [Roeshambo/MonolithDKP#340]
Communication issue occurs when item has comma "," in name, e.g:
https://classic.wowhead.com/item=19364/ashkandi-greatsword-of-the-brotherhood
https://classic.wowhead.com/item=19363/crulshorukh-edge-of-chaos

Issue occurs due to serialization of bid data with ",". Receivers of communication have the bid window filled in invalid way.
Will try to work on this soon.

**Comment by lantisnt** [comment]
Covered by https://github.com/Roeshambo/MonolithDKP/pull/341

**Comment by Roeshambo** [comment]
Committed.
