### ISSUE TITLE
dkp isnt added to notes

### ISSUE THREAD

**Issue by jataknejtakjo** [Roeshambo/MonolithDKP#35]
everything is working in the addon, except it being published to notes (either public or officer). People can see the dkp, if they have the addon. 
The officers with the addon can read/write in both public and officer note. Is there a hidden button somewhere?

**Comment by jataknejtakjo** [comment]
![image](https://user-images.githubusercontent.com/56225797/66270357-c618ff00-e852-11e9-8a2b-99c74f033991.png)

just a snippet of what it looks like. No names or anything.

**Comment by jataknejtakjo** [comment]
![image](https://user-images.githubusercontent.com/56225797/66270380-1728f300-e853-11e9-90f2-be0c53395b5e.png)
one of the guys who has received both dkp and items.

**Comment by Roeshambo** [comment]
The addon does not publish anything to anyone's notes aside from the guild leader. And that note is simply a time stamp to identify the most up to date tables. There is a command available for anyone that doesn't have the addon to whisper an officer to receive their current DKP. Use /dkp ? to see that.

**Comment by Roeshambo** [comment]
Not part of intended functionality.
