### ISSUE TITLE
Different UIs for bidding when versions are confirmed the same.

### ISSUE THREAD

**Issue by PearlmanRyan** [Roeshambo/MonolithDKP#357]
Having an issue where some raiders have a different UI pop-up when an item is bid (confirmed same version and rank)

Some have the +1/+5 bidding option while others dont.

**Comment by PearlmanRyan** [comment]
![](https://cdn.discordapp.com/attachments/633768710771048467/694743239793573908/unknown.png)

**Comment by EnsignRyan** [comment]
![](https://cdn.discordapp.com/attachments/633768710771048467/694743126257958983/unknown.png)

**Comment by EnsignRyan** [comment]
![](https://cdn.discordapp.com/attachments/633768710771048467/694742855046135859/unknown.png)
