### ISSUE TITLE
Feature suggestion: Filtering

### ISSUE THREAD

**Issue by olepg** [Roeshambo/MonolithDKP#38]
Hi.

When I'm bidding I'd like to see what the people I'm bidding against have. 
Could filters in the DKP lists based on class and whether or not that player is currently in my raid.

**Comment by Roeshambo** [comment]
There is a checkbox on the "Filters" tab that says "In Party/Raid". This filters it down to only display those that are within your raid or party. Will include it in the right click context menu on the next update.
