### ISSUE TITLE
Decimal places are overflowing view

### ISSUE THREAD

**Issue by lwatkins** [Roeshambo/MonolithDKP#39]
I have DKP Rounding set to 2 places, but while it shows only to 1 decimal place in the main "Total DKP" window, in the master looter bid window it shows an overflowing number of decimal places (502.2000000047). This was after adding DKP, applying decay %, etc.
https://i.imgur.com/QHmNd3I.png

**Comment by Roeshambo** [comment]
This will be corrected in the next version. That field should have been rounded.
