### ISSUE TITLE
Error when you enter the game

### ISSUE THREAD

**Issue by tornadoff** [Roeshambo/MonolithDKP#4]
This error all time show when i'm enter in game:

Message: Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:23: attempt to get length of local 'classSearch' (a boolean value)
Time: Sat Aug 10 19:40:30 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:23: attempt to get length of local 'classSearch' (a boolean value)
Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:23: in function `ClassGraph'
Interface\AddOns\MonolithDKP\ConfigMenuTabs.lua:212: in function `ConfigMenuTabs'
Interface\AddOns\MonolithDKP\MonolithDKP.lua:129: in function `CreateMenu'
Interface\AddOns\MonolithDKP\init.lua:173: in function `OnInitialize'
Interface\AddOns\MonolithDKP\init.lua:86: in function <Interface\AddOns\MonolithDKP\init.lua:84>

Locals: self = <table> {
 SortDKPHistoryTable = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:23
 StartTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:300
 GetDKPSettings = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:219
 Table_Search = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:380
 StartBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:237
 SortDKPTable = <function> defined @Interface\AddOns\MonolithDKP\MonolithDKP.lua:57
 DKPTable_Set = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:458
 PurgeDKPHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:234
 Commands = <table> {
 }
 ConfigTab3 = <unnamed> {
 }
 PurgeLootHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:223
 CreateTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:337
 ConfigTab2 = <unnamed> {
 }
 GetGuildRankGroup = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:185
 GetGuildRankIndex = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:169
 ConfigTab4 = <unnamed> {
 }
 BroadcastTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:288
 ConfigMenuTabs = <function> defined @Interface\AddOns\MonolithDKP\ConfigMenuTabs.lua:110
 TableStrFind = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:419
 ConfigTab6 = <unnamed> {
 }
 SeedVerify_Update = <function> defined @Interface\AddOns\MonolithDKP\TableFunctions.lua:280
 ClassGraph = <function> defined @Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:6
 UIConfig = MonDKPConfig {
 }
 GetPlayerDKP = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:208
 BroadcastStopBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:218
 ToggleExportWindow = <function> defined @Interface\AddOns\MonolithDKP\Modules\exportDKP.lua:181
 DKPTable_Create = <function> defined @Interface\AddOns\MonolithDKP\TableFunctions.lua:239
 Options = <function> defined @Interface\AddOns\MonolithDKP\Modules\Options.lua:7
 GetGuildRank = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:142
 LootHistory_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\LootHistory.lua:232
 CreateBidWindow = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:475
 ClassGraph_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:108
 ManageEntries = <function> defined @Interface\AddOns\MonolithDKP\Modules\ManageEntries.lua:97
 OnInitialize = <function> defined @Interface\AddOns\MonolithDKP\init.lua:122
 Toggle = <function> defined @Interface\AddOns\MonolithDKP\MonolithDKP.lua:8
 ConfigTab5 = <unnamed> {
 }
 DKPHistory_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:52
 CheckOfficer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:160
 DKPHistory_Reset = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:29
 SortLootTable = <function> defined @Interface\AddOns\MonolithDKP\Modules\LootHistory.lua:12
 GetCColors = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:117
 AdjustDKPTab_Create = <function> defined @Interface\AddOns\MonolithDKP\Modules\AdjustDKP.lua:117
 ConfigTab1 = <unnamed> {
 }
 ResetPosition = <

**Comment by Roeshambo** [comment]
Working on this now. It seems there was an oversight with regards to the Class Breakdown if there wasn't at least one of each class in the table.

**Comment by Roeshambo** [comment]
This issue should be resolved. Let me know if it's working for you.
