### ISSUE TITLE
No option to disable subzerobidding in ZeroSum

### ISSUE THREAD

**Issue by lwatkins** [Roeshambo/MonolithDKP#40]
It is possible to bid more DKP than you have when in ZeroSum mode, and no option to turn that off. So someone with 500 DKP can send in a bid of 600 or 6000 and it will be accepted.

**Comment by Roeshambo** [comment]
That is the nature of zero sum. By going that far into the negative, it will be a very long time before they'll be able to bid on anything in the near future (you can not submit a bid if you're currently in the negative). The alternative would be to use static item values. You can also manually deny a bid by right clicking on the bid and removing it.

**Comment by lwatkins** [comment]
Zero sum doesn't really have any bearing on allowing overbids. What you've
said about going into negative hampering their ability to bid in the future
is true, but is also true of standard DKP systems which have the option to
disable bidding beyond your means. In our group, someone with 50 DKP
shouldn't be able to outbid some with 250, regardless of if you're in a
zero sum or standard allocation system.

**Comment by Roeshambo** [comment]
For now you can simply deny their bid manually. I'll see about getting the check boxes available for zero sum.

**Comment by lwatkins** [comment]
That'd be great, thank you.

**Comment by Roeshambo** [comment]
Added in 1.5.0
