### ISSUE TITLE
Loot History Issue

### ISSUE THREAD

**Issue by carbohydrate** [Roeshambo/MonolithDKP#41]
Ran into an interesting issue with the loot history.  In the screenshot https://imgur.com/a/15gQgrZ you can see a Circlet of Prophecy awarded for the Garr kill.  This was correct, but then the same item also shows up in the Golemagg the Incinerator kill.  Circlet of Prophecy did not drop and no item was awarded to the player for that kill.  The weird thing is you can see it did not actually subtract the second item from the total, so the total amount of DKP is correct.  The lifetime earned is 29 and spent is 50, tho if you add the spent up in history it's 100.

If it matters, we have been using the manual /dkp award playername cost [link item] for all the items and not the /dkp bid window.  If you need anymore files please let me know and I can get them for you.

Love the addon, was our first week using it as a guild and nothing but good feedback from the guild.  Thanks for all your hard work!

**Comment by Roeshambo** [comment]
Does that entry appear in the Loot History tab as well?

**Comment by carbohydrate** [comment]
Yes it does.  Here is the screenshot of the loot history tab.
https://imgur.com/a/mwBoYgS

**Comment by Roeshambo** [comment]
I'm more curious as to how it was registering some of that loot as Azuregos... Someone would have had to have been manually selecting that as the last killed raid boss in the Adjust tab. As far as the loot from Golemagg, I can't explain it to be honest. I've tested that command extensively and it's always worked properly. For future reference, the boss that is used for loot is the boss that is selected in the dropdown on the Adjust DKP tab (Select Boss Kill Bonus in Reason for Adjustment dropdown, then a new dropdown appears to select the boss. This should be automatically selected when a boss is killed.)

**Comment by Roeshambo** [comment]
Actually now that I look at what the loot was, it appears to be BoE drops and whoever awarded it simply had Azuregos selected at the time. I'll have to see about getting a Trash option in there for that.

**Comment by carbohydrate** [comment]
Yeah I've noticed that sometimes the addon defaults to World Boss Azuregos while in between bosses in MC.  I've noticed it one time while doing trash in MC.  Usually I just manually change it to the last boss we killed.
I'm usually the one doing the awarding of DKP while in raid and another officer is usually doing the awarding of items.  I asked him and he did not think that he did anything different while awarding loot on Golemagg.
Do you think it's safe to manually remove that entry from the loot history?

**Comment by Roeshambo** [comment]
You can delete it in the Lua file. Don't right click and remove it within the UI as that will refund them the DKP that it think swas charged to them. I'm going to work on adding a script that will acknowledge trash mobs for the /dkp award command. If you update to 1.5.0 (pushed today, may not be approved yet by curse) the /dkp bid window now allows you to enter a mob/boss name manually if it's incorrect. Can use that for the time being.

**Comment by carbohydrate** [comment]
What is the process to deleting it form the LUA file?  I found it:
{
		["player"] = "Gulps",
		["loot"] = "|cffa335ee|Hitem:16813::::::::60:::::::|h[Circlet of Prophecy]|h|r",
		["zone"] = "Molten Core",
		["date"] = 1570593593,
		["cost"] = "50",
		["boss"] = "Golemagg the Incinerator",
	}, -- [8]
I delete this and try and rebroadcast the tables, but it does not get deleted.  Then we I reload my UI it comes back into the file.  I'm guessing I'm getting tables updated from someone else after I delete it?

I will check out the updated addon later today when I get it.  Thanks!

**Comment by Roeshambo** [comment]
Also what version of the addon did you have when this was occurring? And yes, that's the entry that must be deleted. However, you can ONLY edit the saved variables file when the game is closed. If you delete it with the game open, it will simply put it back when reloaded/relogging. So you'll close the game entirely, then delete that portion.

**Comment by carbohydrate** [comment]
Exiting the game fixed that.  Thank you did not know I had to be out of game to edit the LUA files.
I've been running version 1.4.14, downloaded from the twitch app.  Looks like version 1.5.0 is out now on the Twitch app.

**Comment by Roeshambo** [comment]
Ok. Then that's especially confusing. Considering the addon only auto selects a boss if the killed mob is explicitly found within the table. 1.5.0 reworks how that is done using encounter IDs so it should function a bit more predictably. I have just written an extension to identify trash mobs and select them but have to wait till Tuesday to test it.

**Comment by carbohydrate** [comment]
Yeah I have not noticed it defaulting the the Azuregos boss for awhile now tho.  I feel like I noticed it right when I installed the addon a week or two ago.  If it happens again and I can recreate I will update you.
Thanks for adding the ability to identify the trash mobs.  Will test as well for you on Tuesday.

**Comment by Roeshambo** [comment]
I have not pushed that part yet. Will push it after I'm able to test it. Don't like publishing something that should only work in theory 😜
