### ISSUE TITLE
Minor Whispering Issue

### ISSUE THREAD

**Issue by Krispxxy** [Roeshambo/MonolithDKP#42]
Hey! I have been using your addon for 4 weeks now and it works amazing. Thank you so much for doing this. I got a quick question. When people in the raid /raid !dkp, the raider gets a whisper from ALL of my officers (8) at once providing their DKP amount. I know this is a minor issue, but is there a way to not have all the officers replying with DKP amount in a whisper at once?

Great addon tho man!!

**Comment by Roeshambo** [comment]
Unfortunately, no. Their best bet is to whisper an officer (provided you have the 'whisper' channel open in DKP Modes window) with the command rather than sending it in raid chat. There's no reliable way to have the addon talk between the other officers to figure out who should respond.
