### ISSUE TITLE
Feature/Request - Condense logs, deleted history, edit loot history

### ISSUE THREAD

**Issue by Toomuchsugar** [Roeshambo/MonolithDKP#43]
An option to condense the loot and dkp history from a specified date. This would be useful for when the logs become large and information is no longer relevant.

Currently when something is deleted from the logs there is no record of anything happening and I could see it causing issues. I suggest any deleted log simply have a Strikethrough and/or note stating it was deleted.

Loot history has the option to reassign who the item went to, but not how much they paid for it. Or if there is a way to do it,  I couldn't figure it out. An option to perform this from right click on the entry in the loot history menu would seem more intuitive.

**Comment by Roeshambo** [comment]
Both history tabs only display the 50 most recent events. With a button appearing at the bottom when the total events goes over 50 to "Load 50 more...". So neither tab should ever show more than the last 1-2 months worth of data unless you invoke more with that button.

I can look into possibly adding an option for that with regards to deleting an entry. As far as reassigning, it assumes the cost is the same as the first person paid for it. If you wish for it to be a different value, you can simply delete it and use the /dkp award command. I may be able to add more versatility bin the future.
