### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by xedoz1** [Roeshambo/MonolithDKP#44]
We are gonna use this addon with our guild in classic, but we feel like some kind of bidding window is missing.
A frame like this addon would be nice to have, so every bidder can see in realtime who is highest and also put a bid to be on top.
https://www.wowace.com/projects/dkp-bidder

**Comment by fantomgr** [comment]
and one more thing if you add going to be the best addon specially for guild like ours!!! : the guild leader cant be attent to all raid into guild and he has 2-3 raid leaders but the raid leaders cant start raid time or add some new raid member into roster.....

**Comment by Roeshambo** [comment]
Bidding window will be added in the next version. @fantomgr anyone that is designated an officer can start raid times, award dkp or add players to the DKP roster. If you're not able to, you need "Edit Officer Notes" permissions in the guild manager. That or your guild leader made a whitelist and didn't include you.
