### ISSUE TITLE
History didn't save 

### ISSUE THREAD

**Issue by Fearkilll** [Roeshambo/MonolithDKP#47]
Good day.
We have a big problem.
We got Run 16.10 in MC + Onyxia , i work in addon. All was good.
I charge DKP to players in guild, after come back in game  next day.
And all information lose. Nothing about run 16.10 no loot or dkp.
Can u help me? Or what i must to do.
Thank u

**Comment by Roeshambo** [comment]
The add-on is prone to the same issues as all other add-ons. If you are disconnected or simply close the game, saved variables don't save. I'm guessing one of those two things happened. Best to do a reload after a raid just to make sure everything gets saved. Another officer in the guild should have them saved provided it didn't also happen to them. Simply have them broadcast to you.
