### ISSUE TITLE
Broadcasting DKP sets the GM note to 0

### ISSUE THREAD

**Issue by BajaResident** [Roeshambo/MonolithDKP#48]
Broadcasting is supposed to set the GM note to a timestamp, but it is setting it to 0.  Tried updating to the newest version and doing the same thing.

**Comment by Roeshambo** [comment]
There has not been anything within the addon that sets the note to 0 in some time. Also, if you're using the "Broadcast DKP Table" button within the Manage tab, it does not set the guild note. Only adding or removing an entry (awarding item, awarding DKP or deleting either of those two) into the DKP table changes the GMs note. Try giving yourself 1 DKP in the Adjust DKP tab and then delete it in the DKP history tab. Also, it's best to make sure other officers are on the same version as you if possible

**Comment by BajaResident** [comment]
Deleting the "0" GM note and then clicking "Broadcast DKP Table" did set
the note to 0 again.

However, I did notice that adding 1DKP  did update the GM note to " 0
{MonDKP=191018033300} ". Not sure why the 0 remains there.

Is it possible to make it so the ID is written to Officer Notes, rather
than Public notes? Since only Officers can broadcast it should be fine
right?

[image: image.png]

**Comment by Roeshambo** [comment]
Curious. There might be an officer in your guild with a severely outdated version writing that 0. Writing to officer notes is certainly possible, though not necessarily a "feature" within right now. It would disable the remaining guild members ability to see if their tables are up to date however.

**Comment by BajaResident** [comment]
When I did that broadcast only three of us were online and we had all updated. Do offline officers matter?

**Comment by Roeshambo** [comment]
Nope. If all online were updated then the only thing broadcasting the DKP table would have done is updated the actual table. The only functions that touch the leader note are those that adjust DKP or add entries to the history. So if you delete everything in the leaders note and it adds a 0 when broadcasted, that's certainly curious behavior. Unless you have given non officers permissions to edit public notes and one of them has a very old version perhaps?

**Comment by BajaResident** [comment]
I manually removed the 0, then added 1 DKP and it broadcast without
including a 0. Seems fine now. If I broadcast with a 0 in place, the 0 is
not removed. That may need fixed.

**Comment by Roeshambo** [comment]
Oh. No that's what was going on. The addon is designed to append the seed to the note. This allows the guild leader to still have a note (although it must be relatively short), while including the seed number.

**Comment by BajaResident** [comment]
What happens if the 0 remains and it has a timestamp? Will other officers be able to broadcast out of date due to the 0 prefix?

**Comment by Roeshambo** [comment]
Nope. Anything within the public note is ignored unless it falls between the {MonDKP=######} tag. So you could add a note like "Mine/Herbs {MonDKP=######}" and it will simply update the tag, leaving the rest of the note alone. As long as there's room for the tag. If there isn't enough room, it deletes the entire thing and enters the tag. Basically how it works is each of the 3 tables has a "seed" value. Which is that time stamp. If the seed is older than the timestamp in the note, it's considered out of date.
