### ISSUE TITLE
Enhancement: Standard Multiselection

### ISSUE THREAD

**Issue by vjay82** [Roeshambo/MonolithDKP#49]
Could you implement standard Windows/Mac/Linux multiselection, that is:

CTRL/CMD+click: Additionally select or unselect an entry.
SHIFT+click: Select the range between the last selected item and the clicked item.

Currently it is impossible to select a range, not via mouse only (drag motion) nor via keyboard+mouse.

**Comment by Roeshambo** [comment]
I can look into possibly doing that. With the way the API draws the rows it may be somewhat difficult to accomplish.

**Comment by vjay82** [comment]
Yeah I guessed you had to implement everything yourself, otherwise the behaviour would be the standard one. Thanks for your work btw.

**Comment by Roeshambo** [comment]
Yes, the way faux scrollframes work is they simply draw every row individually. And when you, lets say, scroll down, it literally has to be told to clear all rows and redraw each row one segment higher than it was prior. Just getting the ability to shift click multiple selects and keep those selections maintained when you scroll was a struggle. But I may be able to figure out a way to improve on it.

**Comment by Roeshambo** [comment]
This has been added. Will be in the next version. Can download from this Git to have both Search functionality and Multiselection prior.
