### ISSUE TITLE
Once installing additional addons, not working further.

### ISSUE THREAD

**Issue by Gombolface** [Roeshambo/MonolithDKP#5]
Once I installed other addons, MonolithDKP won't load the /dkp window anymore. /dkp bid works fine, as does /dkp export.

**Comment by Roeshambo** [comment]
Download the newest version and give it a shot. If you're still experiencing this problem turn on your LUA errors with /console scriptErrors 1 and try to open it. Post the error.

**Comment by Gombolface** [comment]
Message: Interface\AddOns\MonolithDKP\MonolithDKP.lua:10: attempt to call method 'IsShown' (a nil value)
Time: Sat Aug 10 23:29:26 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\MonolithDKP.lua:10: attempt to call method 'IsShown' (a nil value)
Interface\AddOns\MonolithDKP\MonolithDKP.lua:10: in function `config'
Interface\AddOns\MonolithDKP\init.lua:53: in function `?'
Interface\FrameXML\ChatFrame.lua:4606: in function `ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4267: in function `ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4303: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals: self = nil
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "attempt to call method 'IsShown' (a nil value)"
core = <table> {
 BidInProgress = false
 TableNumRows = 27
 MonDKPUI = <table> {
 }
 MonDKP = <table> {
 }
 settings = <table> {
 }
 BossList = <table> {
 }
 ShowState = false
 WorkingTable = <table> {
 }
 MonVersion = "v1.0.2 (Release)"
 classFiltered = <table> {
 }
 NumLootItems = 0
 SelectedData = <table> {
 }
 SelectedRows = <table> {
 }
 classes = <table> {
 }
 TableRowHeight = 18
 currentSort = "class"
 faction = "Horde"
 IsOfficer = ""
 TableWidth = 500
 CColors = <table> {
 }
 ClassGraph = MonDKPClassIcons {
 }
}
MonDKP = <table> {
 SortDKPHistoryTable = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:23
 StartTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:304
 GetDKPSettings = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:223
 Table_Search = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:384
 StartBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:239
 SortDKPTable = <function> defined @Interface\AddOns\MonolithDKP\MonolithDKP.lua:57
 DKPTable_Set = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:462
 PurgeDKPHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:238
 Commands = <table> {
 }
 ConfigTab3 = <unnamed> {
 }
 PurgeLootHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:227
 CreateTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:339
 ConfigTab2 = <unnamed> {
 }
 GetGuildRankGroup = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:189
 GetGuildRankIndex = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:173
 ConfigTab4 = <unnamed> {
 }
 BroadcastTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:292
 ConfigMenuTabs = <function> defined @Interface\AddOns\MonolithDKP\ConfigMenuTabs.lua:110
 TableStrFind = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:423
 ConfigTab6 = <unnamed> {
 }
 SeedVerify_Update = <function> defined @Interface\AddOns\MonolithDKP\TableFunctions.lua:280
 ClassGraph = <function> defined @Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:6
 UIConfig = MonDKPConfig {
 }
 GetPlayerDKP = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:212
 BroadcastStopBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:220
 ToggleExportWindow = <function> defined @Interface\AddOns\MonolithDKP\Modules\exportDKP.lua:181
 DKPTable_Create = <function> defined @Interface\AddOns\MonolithDKP\TableFunctions.lua:239
 Options = <function> defined @Interface\AddOns\MonolithDKP\Modules\Options.lua:7
 GetGuildRank = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:142
 LootHistory_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\LootHistory.lua:232
 CreateBidWindow = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:477
 ClassGraph_Update = <function> defined @Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:116
 ManageEntries = <function> defined @Interface\AddOns\MonolithDKP\Modules\ManageEntries.lua:97
 OnInitialize = <function> defined @Interface\AddOns\MonolithDKP\init.lua:122
 Toggle = <function>

**Comment by Gombolface** [comment]
From a guildie, after typing /dkp

Message: Interface\AddOns\MonolithDKP\MonolithDKP.lua:10: attempt to call method 'IsShown' (a nil value)
Time: Sat Aug 10 23:29:17 2019
Count: 2
Stack: Interface\AddOns\MonolithDKP\MonolithDKP.lua:10: attempt to call method 'IsShown' (a nil value)
Interface\AddOns\MonolithDKP\MonolithDKP.lua:10: in function config'
Interface\AddOns\MonolithDKP\init.lua:53: in function?'
Interface\FrameXML\ChatFrame.lua:4606: in function ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4267: in functionChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4303: in function `ChatEdit_OnEnterPressed'
[string ":OnEnterPressed"]:1: in function <[string ":OnEnterPressed"]:1>

Locals: self = nil
(temporary) = nil
(temporary) = <table> {
}
(temporary) = nil
(temporary) = <table> {
}
(*temporary) = "attempt to call method 'IsShown' (a nil value)"
core = <table> {
 BidInProgress = false
TableNumRows = 27
 MonDKPUI = <table> {
 }
 MonDKP = <table> {
 }
 settings = <table> {
 }
 BossList = <table> {
 }
 ShowState = false
 WorkingTable = <table> {
 }
 MonVersion = "v1.0.2 (Release)"
 classFiltered = <table> {
 }
 NumLootItems = 0
 SelectedData = <table> {
 }
 SelectedRows = <table> {
 }
 classes = <table> {
 }
 TableRowHeight = 18
 currentSort = "class"
 faction = "Horde"
 IsOfficer = ""
 TableWidth = 500
 CColors = <table> {
 }
 ClassGraph = MonDKPClassIcons {
 }
}
MonDKP = <table> {
 SortDKPHistoryTable = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:23
 StartTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:304
 GetDKPSettings = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:223
 Table_Search = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:384
 StartBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:239
 SortDKPTable = <function> defined @Interface\AddOns\MonolithDKP\MonolithDKP.lua:57
 DKPTable_Set = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:462
 PurgeDKPHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:238
 Commands = <table> {
 }
 ConfigTab3 = <unnamed> {
 }
 PurgeLootHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:227
 CreateTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:339
 ConfigTab2 = <unnamed> {
 }
 GetGuildRankGroup = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:189
 GetGuildRankIndex = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:173
 ConfigTab4 = <unnamed>
Message: Interface\AddOns\MonolithDKP\Modules\LootHistory.lua:431: attempt to concatenate field 'boss' (a nil value)
Time: Sat Aug 10 23:31:31 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\Modules\LootHistory.lua:431: attempt to concatenate field 'boss' (a nil value)
Interface\AddOns\MonolithDKP\Modules\LootHistory.lua:431: in function LootHistory_Update'
Interface\AddOns\MonolithDKP\ConfigMenuTabs.lua:263: in functionConfigMenuTabs'
Interface\AddOns\MonolithDKP\MonolithDKP.lua:129: in function CreateMenu'
Interface\AddOns\MonolithDKP\init.lua:173: in functionOnInitialize'
Interface\AddOns\MonolithDKP\init.lua:86: in function <Interface\AddOns\MonolithDKP\init.lua:84>

Locals: self = <table> {
 SortDKPHistoryTable = <function> defined @Interface\AddOns\MonolithDKP\Modules\DKPHistory.lua:23
 StartTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:304
 GetDKPSettings = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:223
 Table_Search = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:384
 StartBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:239
 SortDKPTable = <function> defined @Interface\AddOns\MonolithDKP\MonolithDKP.lua:57
 DKPTable_Set = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:462
 PurgeDKPHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:238
 Commands = <table> {
 }
 ConfigTab3 = <unnamed> {
 }
 PurgeLootHistory = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:227
 CreateTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:339
 ConfigTab2 = <unnamed> {
 }
 GetGuildRankGroup = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:189
 GetGuildRankIndex = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:173
 ConfigTab4 = <unnamed> {
 }
 BroadcastTimer = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:292
 ConfigMenuTabs = <function> defined @Interface\AddOns\MonolithDKP\ConfigMenuTabs.lua:110
 TableStrFind = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:423
 ConfigTab6 = <unnamed> {
 }
 SeedVerify_Update = <function> defined @Interface\AddOns\MonolithDKP\TableFunctions.lua:280
 ClassGraph = <function> defined @Interface\AddOns\MonolithDKP\Modules\ClassGraph.lua:6
 UIConfig = MonDKPConfig {
 }
 GetPlayerDKP = <function> defined @Interface\AddOns\MonolithDKP\Core.lua:212
 BroadcastStopBidTimer = <function> defined @Interface\AddOns\MonolithDKP\Modules\Bidding.lua:220
 ToggleExp

**Comment by Roeshambo** [comment]
This looks like an error stemming from another possible error as there is nothing wrong with that code. Are there any other errors when it occurs? (bottom of the Lua error report there is left and right arrows). 
Please also delete your SavedVariables file (WTF\Account\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua (and lua.bak) to make sure there isn't tainted values in there. Make sure your wow client is closed completely before deleting.

**Comment by Gombolface** [comment]
After deleting those, It comes up. :)

**Comment by Roeshambo** [comment]
Great. I was plugging around with what I know of your scenario as best as I could and I identified a few other minor bugs. That's been uploaded. Make sure to update and let me know if any other issues arise :)
