### ISSUE TITLE
Enhancement: Clean Button

### ISSUE THREAD

**Issue by vjay82** [Roeshambo/MonolithDKP#50]
We would really need a clean button to remove all raiders with 0 DKP and no history entries.

Background: We are 600 people in our guild (having more than one raid). We have standby lists for players which get DKP too. Each raid has a core group of raiders and "randoms" from the guild. To manage standby lists, it was necessary to add the whole guild into the tool. (The version before 1.5.3 had really trouble displaying them). People are joining and leaving and currently it is impossible to effectively clean up the data as you can't sort and select a range of players (but the better solution would be the proposed one as I'd prefer to only remove people, who have no history as you could have 0 DKP by coincidence).

**Comment by Roeshambo** [comment]
This now available on the "Manage" tab if downloaded from here. Not available on the published version on curse yet. Removes all entries that have zero DKP and do not appear anywhere in the DKP history.
