### ISSUE TITLE
Enhancement: Filter by name

### ISSUE THREAD

**Issue by vjay82** [Roeshambo/MonolithDKP#51]
As already written in another ticket we currently have 600 people in our list. It would be really nice having a quick filter function using the name or partly the name of members. I think simplest would be having edit fields between each column and its header where you can type freely. For example having the users

Example
Sample
500others

If I type "amp" it should only display the first two. I think this should not reset selection. This way you could easily add/remove sb. to the selection for whatever you are doing.

**Comment by Roeshambo** [comment]
This can be done relatively easily. Wanted to do it but the amount of requests that I've been trying to implement have been a tad overwhelming :p

**Comment by vjay82** [comment]
Yes I understand. If I were you I would implement small things like this over big ones (Data Pull) as more quality of life features are probably leading to more users (and possibly contributors) faster.

**Comment by custodian** [comment]
@Roeshambo i can push a simple solution, I've implemented eairlier https://github.com/custodian/MonolithDKP/commit/c2bc470ec23ec0002ac02aa95d2ed29788164fbb

**Comment by Roeshambo** [comment]
![image](https://user-images.githubusercontent.com/6285297/67157222-eafb8080-f2ee-11e9-8a8e-4659e91bf8db.png)
I just wrote a quick one up. Will be in the next update
