### ISSUE TITLE
Broadcasts are posted to all chat frames

### ISSUE THREAD

**Issue by Kiingy** [Roeshambo/MonolithDKP#53]
Heya.

After updating to 15.x the notifications are printed to all chat frames. 
Not sure which version changed it but at least in 14.x notifications were only printed in the default chat frame.

**Comment by Roeshambo** [comment]
This was intentional behavior per several requests. Messages can be turned off in the options tab. Hope to add an option to select which frame(s) they are printed to in the near future.

**Comment by Kiingy** [comment]
I want the message just not to every chat frame. Please let us toggle it somewhere, it's really annoying =/
