### ISSUE TITLE
Bug: UI freezes

### ISSUE THREAD

**Issue by vjay82** [Roeshambo/MonolithDKP#54]
Hi, me again, we have another problem. When broadcasting DKP changes (broadcast via button or making single changes) the UI of guild members freezes for some time. This is problematic as we have a few hundred people and somebody is asking for an update often (as the addon queries for doing so). The problem is still present in version 1.5.3.  The members describe it as lag spikes or frozen UI.

**Comment by vjay82** [comment]
To clarify, we have just begun using it, Monolith reports on login: 581 player records (as mention earlier today, there is no good way to get rid of them as of now), 57 loot history records and 25 dkp history records.

**Comment by Roeshambo** [comment]
I'm aware of this and have been trying to pin down exactly what action is causing it. Last i noticed it was only occurring when adjustments were made and not when a manual broadcast is done. Is it happening when a full broadcast is done as well?

**Comment by vjay82** [comment]
Yes. Do you like me to send you my saved variables or sth.? Experienced it now myself and my client blocked for 2-3 seconds.

**Comment by Roeshambo** [comment]
Nope it's fine. I'm trying to work out a way to send the data in smaller packets while maintaining integrity. As it functions now, it processes the entire table all at once.

**Comment by Roeshambo** [comment]
Just updated with optimization that will dramatically reduce/eliminate the lag when receiving a broadcast. When you adjust the entire raids DKP, you'll still receive a mild lag spike yourself, but no one else will. This is mostly unavoidable as it has to recursively search through the table and run math operations on their DKP.
