### ISSUE TITLE
Request of features

### ISSUE THREAD

**Issue by Warchas** [Roeshambo/MonolithDKP#57]
A function I'd love to request is "highlight all raid members" cause as an example right now for some reason the raid doesnt get credited for boss kills so I have to highlight every raid member to manually give them boss kill dkp. This is takes some time if you have i.e 70 members in the DKP list and 40 in the raid so you need to go over the whole raid and then mark and then adjust.

A feature that would allow only 1 bid per person. You bid once and then you cannot change it.

Thanks again for an amazing AddOn

**Comment by Roeshambo** [comment]
The addon doesn't automatically apply DKP except while the raid timer is running (applies at the interval set). There is already a means to select all in a raid. Right click the table > table views > view raid. Then right click again and Select All. There will be additional selection features in the next version

**Comment by Warchas** [comment]
I doesnt apply DKP for boss kills even if raid timer is running. I need to apply it manually after each boss kill.

**Comment by Roeshambo** [comment]
It's not supposed to apply DKP automatically. I may include an option in the DKP Modes window in the future to have it apply the DKP on a successful kill at some point. But as of right now, it must be done manually. The timer only applies DKP automatically for time interval bonuses.
