### ISSUE TITLE
Addon is visually too large to function.

### ISSUE THREAD

**Issue by BWhitemore1** [Roeshambo/MonolithDKP#58]
When tying /DKP recently the addon would take up too much of the screen for me to be able to use it. I can't change tabs within the addon, so I am limited to only the first two pages. The window that opens with handling loot works fine, but the main window for the addon is too large for me to do much else. I have /DKP reset, reset settings via Twitch, and reinstalled the addon. 
![1](https://user-images.githubusercontent.com/56938728/67432636-6f722b80-f59b-11e9-9194-e98aa7a6fcf7.jpg)

**Comment by Roeshambo** [comment]
Your UI scaling must be obscene. Go into the wow settings and reduce your UI scaling, then open the addon and go to the options tab and drop the scale of the GUI to a low setting. Then you can restore your UI scaling in the wow settings to where it was before and should be able to change the scale of the addon to what you want from there.

**Comment by BWhitemore1** [comment]
This worked perfectly, thank you! And thank you for the great addon.
