### ISSUE TITLE
Update loot table on wrong assignment

### ISSUE THREAD

**Issue by NicolaiLolansen** [Roeshambo/MonolithDKP#59]
Sorry if this has already been answered, or if it is already a feature in the current version. 

I would like to know if you can reassign loot so it shows up in the loot table correctly, if you have made a mistake on item assignment. Currently we have to adjust the DKP manually for the parties involved, and it will not reflect in the loot table (Also the lifetime earned and spent values will be out of sync).

If this is already possible, how do you do it? We like to keep the loot tables to see the gear assigned at every raid.

**Comment by Roeshambo** [comment]
You can right click a loot assignment in the loot history tab, select who to reassign it to on the table and then select reassign loot. It will refund the first person and charge the new one. It will charge the new player the same dkp the first one payed. If you want to reassign it for a different amount, simply right click and delete it, and then award it to the new person with the new value using the /dkp award command. Parameters for that are in the /dkp ? Command

**Comment by NicolaiLolansen** [comment]
Perfect, solves my issue!
