### ISSUE TITLE
minimal fixed prices on items

### ISSUE THREAD

**Issue by tornadoff** [Roeshambo/MonolithDKP#6]
Hi. 
can you make a separate window where you can set the minimum prices on items? Example: I open windows in addon and in loot drop from the first boss Molten Core put down the minimum prices. When a thing falls to me in raid it will only be necessary to start the drawing (without manually setting the minimum price in the drawing window - it will already be standing).
It's mast be looking like here: https://webdkp.com/dkp/Ysondre/Higurashi/LootTable

**Comment by Roeshambo** [comment]
That's an option that was just added today in the newest update. If you're an officer in your guild, the "Options" tab will allow you to set minimum bid prices on a per item type basis:
![image](https://user-images.githubusercontent.com/6285297/62848989-6b748400-bca3-11e9-8b39-ddb036271fcb.png)

Just download the newest version (1.1.0) or pull from this Git. I may reevaluate the minimum bid memory on a per item basis.

**Comment by Roeshambo** [comment]
I've expanded on the functionality in the next version (will be 1.2.0, not uploaded yet). If you change the minimum bid value in the "/dkp bid" window, it will store that custom value for that specific item. After that, it will use that new custom value for that item any time it's opened in the bid window.

![image](https://user-images.githubusercontent.com/6285297/62992573-908b0300-be19-11e9-881f-b2131c2d9056.png)

**Comment by tornadoff** [comment]
As I understand it: fixed prices will be on the slot where this item is located, and not on the item itself? "head", "neck", not a specific item? 
i means: if in loot drop will be https://classic.wowhead.com/item=17076/bonereavers-edge   and https://classic.wowhead.com/item=17104/spinal-reaper   
Both items will be in same minimal price? But if i need that Bonreavers in fixed price mast be 100 DKP and Spinal Reaper 70. 
i means: is that real to creat list whitch will be display all items from chosen raid dungeons and selected boss and i can set fixed prict on them.

Fro example: in list i seletc Molten Core -> on next step i seleting Ragnaros and after this i see list with all item witch can drop from this boss and near each item i see small windows in witch i can set minimal fixed price specifically on this item.

**Comment by Roeshambo** [comment]
In the new version, there won't be a window to manually edit every piece. However, if you open the bid window for a specific item and change the Minimum Bid value to something other than what is set in the options category and start a bid with that changed value, it'll store that price and always display that new minimum bid just for that item any time it's placed in the bid window again. 

If you'd like to change values for a large number of items you can simply use the "/dkp bid [item_link] command and use an addon like atlas loot to provide the item link. change the value then click "Start Bidding" and immediately click "Stop Bidding" to store the new value. The command is only available in a raid so you'd have to make a small 2 man raid with another player to do that. 

So to break down the steps. Create small raid, find link to item you'd like to change. Type "/dkp bid [link]" which will open the bid window with that items details. Change "Minimum Bid:" to the value you'd like to use. Start bidding > stop bidding. It'll then store that information. I may be able to expand on the functionality in the future to allow setting in options. But I've got a lot of stuff going on with it at the moment so may not get to it for a bit.
