### ISSUE TITLE
Addon doesn't broadcast any more.

### ISSUE THREAD

**Issue by Voley** [Roeshambo/MonolithDKP#64]
After updating suddenly the broadcasting feature doesnt work at all.
It says "Starting broadcast, broadcasting table, history, loot history" but other people do not receive anything whatsoever.

Yesterday it worked fine and people received updates, but not any more. They are not seeing the updates in chat either, that someone started broadcasting.
I have tried removing GM note, or setting it to 0, doesn't change anything. Tried to change to previous version, still the same.

1.5.4

**Comment by Roeshambo** [comment]
Where did you update from? Still works fine for me. Turn on Lua errors with /console scriptErrors 1 and broadcast. If anything pops up let me know

**Comment by Voley** [comment]
No errors at all.
Here is the backup file if it is of any help:

[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3769756/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
It looks like you have a whitelist set with just one name on it; Девоу. Is that you?

**Comment by Voley** [comment]
Yes.

**Comment by Voley** [comment]
I have cleaned whitelist to no avail. Maybe I got banned by some blizzard tool for spamming too much in those channels?
Chat works fine tho.

**Comment by Voley** [comment]
Have tried removing table alltogether, broadcasting empty table, or table with 1 entry - still nothing.

**Comment by Roeshambo** [comment]
It worked in the previous version just fine, and you rolled back to that and it still doesn't work, correct? Have you gotten any new addons or updated any others recently? Try running only Monolith with other addons turned off. There may be a conflict I'm unaware of.

**Comment by Roeshambo** [comment]
You wouldn't have gotten locked out for any kind of spam as there are addons that broadcast FAR more information consistently (like dps meters for example).

**Comment by Voley** [comment]
Disabling addons did not help.

But I have found a workaround, if a guy in guild deleted monolithdkp.lua and bak in saved variables, they started to be able to receive transmittions again.

It would be nice to have an option for Guild Master to force his database on everyone without this. I belive what broken was that at some point by mistake GM was removed from white list, changing white list didn't help and it got stuck this way on regular players clients,
Changing white list did not help.

**Comment by Roeshambo** [comment]
It shouldn't be possible to remove the GM from the list unless done so manually in the Lua file. It always adds the GM to the list no matter what. The whitelist is very alpha and I haven't been able to revisit it as more pressing issues have come up (namely, broadcast integrity). The fact that it requires the whitelist be broadcasted to every player to work makes it sketchy at best. Hence the warning to avoid using it if possible.
