### ISSUE TITLE
[Feature request] Add a way to see all person's dkp gains like you can see all spendings in item history.

### ISSUE THREAD

**Issue by Voley** [Roeshambo/MonolithDKP#65]
Topic. We have faced issues with correctness of DKP calculations and it would be nice to see all lifetime gains by a person.

**Comment by Roeshambo** [comment]
![image](https://user-images.githubusercontent.com/6285297/67615483-b9713200-f792-11e9-958f-874475c5cd9e.png)

**Comment by Voley** [comment]
I don't have this in current version, when will it appear?

![no1](https://user-images.githubusercontent.com/705508/67618299-2bc72e00-f7f6-11e9-8f16-7104a37849fb.png)

@Roeshambo

**Comment by Roeshambo** [comment]
Was just indicating that I had made it and it'll be with the next version. As soon as broadcasting is revamped.

**Comment by Voley** [comment]
Thanks

**Comment by Roeshambo** [comment]
Has been added in 1.6.0 on curse. Have not uploaded to this repository yet.
