### ISSUE TITLE
Incorrect calculations.

### ISSUE THREAD

**Issue by Voley** [Roeshambo/MonolithDKP#66]
We have faced an issue that spendings from a raid are not getting used in calcualtions, but they are shown in history.
As you can see he has more spending on the list than 215. Not having full dkp gains history doesn't help, addded that as feature request.

The feature to show gains/losses near the name of a character (little arrow) was reset before the raid where he looted two items. As you can see it also shows incorrect +15, where it should be negative.

![dkp_gains](https://user-images.githubusercontent.com/705508/67560117-e38b0b80-f722-11e9-960b-24d562d235f1.png)
![dkp_history](https://user-images.githubusercontent.com/705508/67560118-e423a200-f722-11e9-84dd-a12b99f70435.png)

**Comment by Roeshambo** [comment]
There was an issue identified when either multiple people were adding entries or when a single person was adding entries in quick succession. As the DKP table gets bigger (more people) it takes longer to broadcast. Sometimes up to 10-15 seconds for some reason. If an entry is pushed before the first completes, it causes tables to be overwritten with incorrect data. I'm hoping the new system for broadcasting will eliminate that entirely.
