### ISSUE TITLE
[Feature Request] Update Loot without bid UI

### ISSUE THREAD

**Issue by kcianch** [Roeshambo/MonolithDKP#68]
It would be really nice to award items without the bid system, for example if I want to go back and correct something and have it show up as an item history instead of a dkp adjust history. 

I understand the award item method requires current zone / boss and an itemlink so this might be tricky to refactor.

**Comment by Roeshambo** [comment]
You can select the boss and zone in the with the /dkp award command.

**Comment by kcianch** [comment]
I was more talking about if I'm not in a raid, or the player isn't online, I'm looking for a way to award them an item, not a dkp adjust, without them messaging !bid. That could be there already I just can't see it

**Comment by Roeshambo** [comment]
That's what the /dkp award command is for. You don't need to be in a raid and the player doesn't need to be online. All commands are displayed using "/dkp ?". Syntax is "/dkp award Player cost [item link]". It'll then prompt you with a confirmation box to change the zone/mob.

**Comment by kcianch** [comment]
Ah you're so right, /dkp ? wasn't working tho.  But the award command is awesome! Thanks a ton!
