### ISSUE TITLE
Error finding players, randomly.

### ISSUE THREAD

**Issue by Gombolface** [Roeshambo/MonolithDKP#69]
Happened during our raid. One of our tanks tried to bid, addon said he was not found.

Date: 2019-10-25 20:31:14
ID: 2
Error occured in: AddOn: MonolithDKP
Count: 462
Message: Note: AddOn MonolithDKP attempted to call a protected function (CompactRaidFrame9:Hide()) during combat lockdown.
Debug:
   [C]: Hide()
   ..\FrameXML\CompactUnitFrame.lua:355: CompactUnitFrame_UpdateVisible()
   ..\FrameXML\CompactUnitFrame.lua:286: CompactUnitFrame_UpdateAll()
   ..\FrameXML\CompactUnitFrame.lua:185:
      ..\FrameXML\CompactUnitFrame.lua:185
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  AtlasLootClassic, vv1.3.2
  AtlasLootClassicData, vv1.3.2
  AtlasLootClassicDungeonsAndRaids, vv1.3.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BetterVendorPrice, vv1.10.00
  CallbackHandler10, v
  ClassicCastbars, vv1.1.2
  ClassicCastbarsOptions, v
  ClassicGuildBank, v1.2
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.17
  DBMCountPackOverwatch, v1.4.7
  DBMDefaultSkin, v
  DBMMC, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Dominos, v8.2.30
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  FieldGuide, vv1.5-release
  FishingBuddy, v0.6 Beta 1
  Informant, v8.2.6374 (SwimmingSeadragon)
  LibStub, v
  MonolithDKP, v1.5.4
  Necrosis, v5.2
  RecipeRadarClassic, v1.0.0.22
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WeakAuras, v2.15.4
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=583)

**Comment by Roeshambo** [comment]
That error is an arbitrary one thrown by many different addons and it's been a recurring issue for years. It's just due to bad programming on Blizzards part because they have a commonly called public function that references a protected function. At no point does the addon attemp to call to CompactRaidFrames. Were there any additional errors? There should be a left and right button to view other errors that may have occurred in conjunction with that one.

**Comment by Gombolface** [comment]
Date: 2019-10-25 20:31:14
ID: -24
Error occured in: AddOn: MonolithDKP
Count: ∞
Message: Note: AddOn MonolithDKP attempted to call a protected function (CompactRaidFrame9:Hide()) during combat lockdown.
Debug:
   [C]: Hide()
   ..\FrameXML\CompactUnitFrame.lua:355: CompactUnitFrame_UpdateVisible()
   ..\FrameXML\CompactUnitFrame.lua:286: CompactUnitFrame_UpdateAll()
   ..\FrameXML\CompactUnitFrame.lua:185:
      ..\FrameXML\CompactUnitFrame.lua:185
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  AtlasLootClassic, vv1.3.2
  AtlasLootClassicData, vv1.3.2
  AtlasLootClassicDungeonsAndRaids, vv1.3.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BetterVendorPrice, vv1.10.00
  CallbackHandler10, v
  ClassicCastbars, vv1.1.2
  ClassicCastbarsOptions, v
  ClassicGuildBank, v1.2
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.17
  DBMCountPackOverwatch, v1.4.7
  DBMDefaultSkin, v
  DBMMC, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Dominos, v8.2.30
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  FieldGuide, vv1.5-release
  FishingBuddy, v0.6 Beta 1
  Informant, v8.2.6374 (SwimmingSeadragon)
  LibStub, v
  MonolithDKP, v1.5.4
  Necrosis, v5.2
  RecipeRadarClassic, v1.0.0.22
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WeakAuras, v2.15.4
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=583)

_________________________________________

Date: 2019-10-25 20:31:14
ID: -23
Error occured in: AddOn: MonolithDKP
Count: ∞
Message: Note: AddOn MonolithDKP attempted to call a protected function (CompactRaidFrame8:Show()) during combat lockdown.
Debug:
   [C]: Show()
   ..\FrameXML\CompactUnitFrame.lua:353: CompactUnitFrame_UpdateVisible()
   ..\FrameXML\CompactUnitFrame.lua:286: CompactUnitFrame_UpdateAll()
   ..\FrameXML\CompactUnitFrame.lua:185:
      ..\FrameXML\CompactUnitFrame.lua:185
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  AtlasLootClassic, vv1.3.2
  AtlasLootClassicData, vv1.3.2
  AtlasLootClassicDungeonsAndRaids, vv1.3.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BetterVendorPrice, vv1.10.00
  CallbackHandler10, v
  ClassicCastbars, vv1.1.2
  ClassicCastbarsOptions, v
  ClassicGuildBank, v1.2
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.17
  DBMCountPackOverwatch, v1.4.7
  DBMDefaultSkin, v
  DBMMC, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Dominos, v8.2.30
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  FieldGuide, vv1.5-release
  FishingBuddy, v0.6 Beta 1
  Informant, v8.2.6374 (SwimmingSeadragon)
  LibStub, v
  MonolithDKP, v1.5.4
  Necrosis, v5.2
  RecipeRadarClassic, v1.0.0.22
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WeakAuras, v2.15.4
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=583)

_______________________________________________

Date: 2019-10-25 20:35:19
ID: -11
Error occured in: Global
Count: 8
Message: ..\AddOns\MonolithDKP\Modules\Bidding.lua line 150:
   attempt to index local 'cmd' (a number value)
Debug:
   MonolithDKP\Modules\Bidding.lua:150: MonDKP_CHAT_MSG_WHISPER()
   MonolithDKP\init.lua:199:
      MonolithDKP\init.lua:145
Locals:
text = "!dkp 17"
name = "Middy"
cmd = 17
dkp = nil
response = "Error processing command"
(*temporary) = 6
(*temporary) = 17
(*temporary) = "Middy-MirageRaceway"
(*temporary) = 1
(*temporary) = 5
(*temporary) = "Middy"
(*temporary) = 17
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'cmd' (a number value)"
L = <table> {
 CONFIRMWHITELIST = "Are you sure you'd like to add the selected players to the whitelist?"
 CLOSE = "Close"
 TOBIDUSE = "To bid use"
 OFFHANDITEMS = "Off-Hand Items"
 NOTINRAIDPARTY = "You are not in a raid party."
 PERCENT = "Percent"
 SHOULDERS = "Shoulders"
 PERCENTCOST = "Percentage cost"
 MELEEDPS = "Melee DPS"
 TIMEINTERVALBONUS = "Time Interval Bonus"
 INCLUDESTANDBY = "Include Standby"
 OODLOOTTABLEITEM = "has attempted to update an item from an out of date Loot Table. This can cause irreversable damage to your DKP table. Would you like to accept?"
 APPDECAYTTWARN = "Warning: Can not be undone."
 AWARDINTERVALTTWARN = "eg. Entering 60 will award the raid (and standby, if checked below) the DKP amount in the "Bonus" field above every hour."
 ONLYPARTYRAID = "Only Party or Raid"
 CLEARBIDWINDOW = "Clear Window"
 DKPTOFOLLOWING = "DKP to the following players"
 NOPLAYERINSTANDBY = "There are no players in the standby group."
 ENTRIESSHOWN = "Entries Shown"
 TOSEND = "to send"
 INCSTANDBYLISTTTDESC = "Includes players in the standby list in distribution."
 REASONTTWARN = "When a boss is killed, the appropriate zone and boss will be auto-selected for you."
 RECENTHISTORYFOR = "Recent History for"
 BCASTLOOTHISTBTN = "Broadcast Loot History"
 ITEMCOSTTTDESC = "DKP to charge player for item."
 INFLATION = "Inflation"
 DKPHISTRECORDS = "dkp history records"
 DKP = "DKP"
 CUSTOMMINBID = "Custom Minimum Bid"
 BIDDENIEDNEGATIVE = "Bid Denied! Your DKP is in the negative"
 BCASTDKPHISTCONF = "Are you sure you'd like to broadcast your DKP History table?"
 ENABLED = "Enabled"
 DKPEXPORTHELP = "Opens window to export all DKP information to HTML, CSV or XML. (More export implementations to come)"
 ADJUSTDESC = "Select individual players from the left (Shift+Click for multiple players) or click "Select All Visible" below and enter amount to adjust.

Scope can be adjusted with "Show Raid Only" below or on the "Filters" tab."
 DKPHISTORY = "DKP History"
 RAIDPAUSE = "Raid has been paused at"
 CONTINUERAID = "Continue Raid"
 WEEKLYDECAYTTDESC = "Amount of DKP you wish to reduce DKP entries by as a weekly decay. This should be a positive number. If "Selected Players Only" is not selected below, it will apply to all entries."
 CURRNOTINGUILD = "You are not currently in a guild. DKP status can not be queried."
 DKPPRICE = "DKP price"
 COMMANDCHANNELSTTDESC = "Select the channels you wish to open to receive !bid and !dkp commands. You can select any combination of the three to open. All received commands, regardless of the channel, will be responded to with a whisper."
 CONFIRMWHITELISTCLEAR = "Are you sure you'd like to clear the whitelist?"
 INVALIDITEMLINK = "Can not award item. Invalid item link"
 SELPLAYERSONLY = "Selected Players Only"
 ALLCLASSES = "All Classes"
 USEPERCROLLSTTWARN = "If this is checked, please only use numbers between 0 and 100."
 NONE = "None"
 LEGS = "Legs"
 HANDS = "Hands"
 MANAGECORELIST = "Manage Core Raider List"
 ADDTARGETTTDESC = "Adds your current target, if a player, to the DKP table. This, unlike all other options, does not require the target to be in your guild."
 ZONE = "Zone"
 BIDCANCELLED = "Your bid has been canceled."
 TIMERSIZE = "Timer Size"
 RETRIBUTION = "Retribution"
 INVALIDROLLPARAM = "You have set an invalid roll parameter. Please revise your settings."
 CHANGELOG9 = ""
 DECAYPERCENTAGE = "Decay Percentage"
 MINBIDTTEXT = "If you enter a value other than what is set in Options, that custom value will be stored for that specific item."
 ONLINE = "Online"
 MANAGELISTS = "Manage Lists"
 NECK = "
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  AtlasLootClassic, vv1.3.2
  AtlasLootClassicData, vv1.3.2
  AtlasLootClassicDungeonsAndRaids, vv1.3.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BetterVendorPrice, vv1.10.00
  CallbackHandler10, v
  ClassicCastbars, vv1.1.2
  ClassicCastbarsOptions, v
  ClassicGuildBank, v1.2
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.17
  DBMCountPackOverwatch, v1.4.7
  DBMDefaultSkin, v
  DBMMC, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Dominos, v8.2.30
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  FieldGuide, vv1.5-release
  FishingBuddy, v0.6 Beta 1
  Informant, v8.2.6374 (SwimmingSeadragon)
  LibStub, v
  MonolithDKP, v1.5.4
  Necrosis, v5.2
  RecipeRadarClassic, v1.0.0.22
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WeakAuras, v2.15.4
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=5b0)

___________________________________________________________________________________

Date: 2019-10-25 20:39:46
ID: -5
Error occured in: Global
Count: 1
Message: ..\FrameXML\EasyMenu.lua line 26:
   attempt to get length of local 'menuList' (a nil value)
Debug:
   ..\FrameXML\EasyMenu.lua:26: initFunction()
   ..\FrameXML\UIDropDownMenu.lua:79: UIDropDownMenu_Initialize()
   ..\FrameXML\UIDropDownMenu.lua:1108: ToggleDropDownMenu()
   MonolithDKP\TableFunctions.lua:30:
      MonolithDKP\TableFunctions.lua:24
Locals:
frame = MonDKPDKPTableMenuFrame {
 0 = <userdata>
 Right = MonDKPDKPTableMenuFrameRight {
 }
 Left = MonDKPDKPTableMenuFrameLeft {
 }
 displayMode = "MENU"
 initialize = <function> defined @Interface\FrameXML\EasyMenu.lua:25
 Button = MonDKPDKPTableMenuFrameButton {
 }
 Text = MonDKPDKPTableMenuFrameText {
 }
 Middle = MonDKPDKPTableMenuFrameMiddle {
 }
 Icon = MonDKPDKPTableMenuFrameIcon {
 }
}
level = 1
menuList = nil
(*temporary) = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to get length of local 'menuList' (a nil value)"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  WowheadLooter, v11302
  AtlasLootClassic, vv1.3.2
  AtlasLootClassicData, vv1.3.2
  AtlasLootClassicDungeonsAndRaids, vv1.3.2
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BetterVendorPrice, vv1.10.00
  CallbackHandler10, v
  ClassicCastbars, vv1.1.2
  ClassicCastbarsOptions, v
  ClassicGuildBank, v1.2
  ClassicThreatMeter, v1.10
  DBMCore, v1.13.17
  DBMCountPackOverwatch, v1.4.7
  DBMDefaultSkin, v
  DBMMC, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Dominos, v8.2.30
  DominosCast, v
  DominosProgress, v
  DominosRoll, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  ExtendedCharacterStats, v1.5
  FieldGuide, vv1.5-release
  FishingBuddy, v0.6 Beta 1
  Informant, v8.2.6374 (SwimmingSeadragon)
  LibStub, v
  MonolithDKP, v1.5.4
  Necrosis, v5.2
  RecipeRadarClassic, v1.0.0.22
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  WeakAuras, v2.15.4
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=5b0)

_________________________________________________________________________


Errors that I can locate.

**Comment by Roeshambo** [comment]
Ah I see where it went wrong:

Locals:
text = "!dkp 17"
name = "Middy"
cmd = 17
dkp = nil

He attempted to bid with the !dkp command, instead of !bid, which only accepts a string (it's the command to request your current DKP). So he mixed up his commands. I'll get it fixed to catch it if it's not a string. But for now it can mostly be ignored as it doesn't impact functionality.
