### ISSUE TITLE
Bidding / Useability

### ISSUE THREAD

**Issue by JGit85** [Roeshambo/MonolithDKP#7]
Is there additional documentation around the bid process and how non-officer users utilize this?  Is the add-on required to be installed by all users or are all bids handled via PM and picked up by officers utilizing the add-on?  What is the process to bid on an item? Does the add-on simply grant non-officer users the ability to view history? etc

**Comment by Roeshambo** [comment]
Releasing the addon was sort of an on-the-spot decision so I was intending to make a video demonstrating the how-to. But I'll try to include a rudimentary walk through for all of the functions. But to answer your questions directly. The addon is not required for anyone but the person starting the bidding (it's all handled via whispers on the receiving end). Process includes Shift+Alt clicking an item in the loot window, or using the "/dkp bid [item_link]" command. The default minimum bid and bid duration (both set in options tab) will be auto filled. Changing the Minimum bid will create a custom min bid for that specific item and store it. Clicking start bidding will broadcast a timer to everyone and announce what item is being bid on as well as it's min dkp. Users will whisper "!bid value" replacing value with the number they wish to bid. If they have enough DKP and it's above the minimum bid, it'll be added to the bid list. Or else it's rejected and they're notified. If you have "Sub Zero Bidding" checked, it'll allow bids that will put them into the negative if you so choose. After bidding is completed, you select the name in the list that won and click "Award item" (you can modify the item cost at the bottom if you like). The item cost is auto updated to either the # 2 bidders bid or the minimum bid if only one person submitted a bid.

As far as the permissions, all users can view everything except the "Adjust DKP" and "Manage" tabs. Non officers also have a limited "Options" tab where they can only set local settings. They are not able to view the Award or min bid values. Filters, Loot History, and DKP History are all viewable by everyone. (DKP History and Loot History right click context menus to edit them are only available to officers).

At the moment, officers are determined by those who have the permission to write to officer notes. However, I'm currently adding a "Whitelist" feature that will allow you to manually select those who have "officer" permissions. Anyone not on the whitelist would not get officer permissions, even if they are an officer.

**Comment by JGit85** [comment]
Hey, no worries, thanks for the detailed info I greatly appreciate it.  Great project by the way, very well executed.
