### ISSUE TITLE
Announce Current Bid in Raid Chat

### ISSUE THREAD

**Issue by wheetcracker** [Roeshambo/MonolithDKP#71]
Could the addon announce the current bid for an item in raid chat whenever it is raised? Our guild prefers DKP bidding to not be a silent auction. 

I realize that the same effect can be achieved by allowing bids to be given in raid chat, but we prefer to not have people know who they are bidding against.

We currently do this by having the raid leader do their best auctioneer impression in voice chat. This works somewhat, but it is a burden on the voice comms. and makes pulling trash during loot distribution difficult.

**Comment by Roeshambo** [comment]
Next version. Will be a bit of time though.
