### ISSUE TITLE
Request QoL feature

### ISSUE THREAD

**Issue by Warchas** [Roeshambo/MonolithDKP#72]
This is a very minor request but it's a QoL (Quality of Life) request.

I myself in general tend to forget to /combatlog at the start of the raids.

Would it be possible to have at the initial raid button add so that I can enable /combatlog when I press initialize? 
I mean this is 100% not needed but like I said it would be a real QoL feature which I would love.

**Comment by Roeshambo** [comment]
I could probably tuck an option in there to turn on logging when in a raid and an encounter begins if it's not already on. Would that resolve your concern?

**Comment by Warchas** [comment]
Yes that would be amazing

**Comment by Roeshambo** [comment]
Added in the next version
