### ISSUE TITLE
Possible Issue but maybe not?

### ISSUE THREAD

**Issue by Vivi9935** [Roeshambo/MonolithDKP#75]
Hello!

So we've been using the Monolith DKP addon since Classic's launch and we've been loving it. We're encountering this issue, though, and I'm not sure if there's a way I myself can do something in the addon to prevent it from happening - or maybe it's not an option and it could possibly be added. Let me paint the picture.

An item drops, using the Minimum Bid Values mode the starting bid is 10 dkp.
People start sending in their DKP and two people both bid say... 30dkp to an item and Monolith would accept both bids.

Is there a way I could make it so it could accept whichever one comes first, then automatically raise the required amount of DKP to bid in order to bid again? So if two people want to bid 30 dkp, the first person to submit gets accepted, and the second one is denied and has to send in another bid thats higher.

Just curious for thoughts, I suppose. Maybe this is already a thing and its just something I'm missing.

Thanks!
Vivi

**Comment by Roeshambo** [comment]
All bids are accepted as long as they meet the parameters set within the modes window. Even if it's lower than the highest bid. There are no stipulations to block those bids. I am, however, adding a feature where the person hosting the bid will automatically announce the highest current bid as they come in (can be toggled on and off of course). So the raid will always know the current highest bid if you choose to turn that on. And can submit another bid accordingly.

**Comment by Vivi9935** [comment]
Alright, sweet! When will that be out?

**Comment by Roeshambo** [comment]
Might be a little bit. There's a bunch of changes I'm making that will require everyone be on the same version or higher. And I'd rather do it all at once rather than expect everyone to make sure their entire guild is on the same version multiple times.

**Comment by Vivi9935** [comment]
No worries! Appreciate the great work you're doing. Might I make the suggestion of adding something like that though? Where it automatically denies lower bids than the current one?

**Comment by Roeshambo** [comment]
Can put it on the list.

**Comment by Vivi9935** [comment]
Appreciate you! Keep up the amazing work!

**Comment by Roeshambo** [comment]
Option added for next version
