### ISSUE TITLE
Starting 2nd raid team but dont have GM title

### ISSUE THREAD

**Issue by Krispxxy** [Roeshambo/MonolithDKP#76]
Hey!
So I am the GM of my guild and run the DKP addon. My guild has leveled alts to start a 2nd raid team. I will be leading the 2nd raid team on my alt level 60. Is there a way to give my alt character full access to the DKP addon without having a GM title or Officer title??

Amazing Addon btw!

Thanks

**Comment by Roeshambo** [comment]
The one thing that flags someone as an officer within the addon is "Edit Officer Note" permissions. If your alt had a rank that held that permission, they would be able to operate it.

**Comment by Krispxxy** [comment]
Ok, and then I have to "whiteflag" that specific alt's name so they can navigate the addon, correct?

**Comment by Roeshambo** [comment]
Nope. Whitelist is only used if you want to restrict access further for officers. I would avoid using it all together if you don't need to do that.
