### ISSUE TITLE
Reset Bid Timer to 0:15 When a New Bid Comes in

### ISSUE THREAD

**Issue by wheetcracker** [Roeshambo/MonolithDKP#77]
Hello!

Would it be possible to have the bid timer reset itself some low value (15 seconds perhaps) when a bid is put in while the timer is below that amount of time? Our guild has had the situation come up many times now where a major bidding war is taking place on an item. We've had to restart the bidding on certain items multiple times until the final price is reached and the item is sold. 

It would be a great improvement for us to have the timer simply reset itself to 15 seconds when a bid is put in with less than 15 seconds on the clock.

Thanks!

**Comment by Roeshambo** [comment]
This will be in the next version. If a bid is submitted when the timer is below 10 seconds, it will increase by the value you give it automatically.

**Comment by manu69** [comment]
Was this added? our guild is having issues with this.. ppl basically only bidding at the 1 second timer and its become a gamble instead of a bidding system.

**Comment by Roeshambo** [comment]
Yes it's in the 2.0.2 beta. Should be released later this week pending no additional issues.
