### ISSUE TITLE
Unable to add users

### ISSUE THREAD

**Issue by curtman7** [Roeshambo/MonolithDKP#8]
Hello, I am trying to test this out in the retail client before using it in classic. I created a raid group with 3 people and when I click the button to add users to the table, nothing happens. This is the only addon I have installed. Any suggestions?

**Comment by Roeshambo** [comment]
Were those raid members in your guild? The addon only adds the raid members if they are. I'm adding other "add player" functionality in the next version that will be out tomorrow including an "add guild members by rank" and "add target" which will be regardless of guild standing.

**Comment by curtman7** [comment]
Ah okay, no they weren't. I noticed in one of your screenshots a lot of the
members said "not in guild" or something like that so didn't think they
needed to be. Since i was just testing. However, why didn't it add myself,
I'm definitely in the guild lol, the GM.

**Comment by Roeshambo** [comment]
Ya that was because i generated that savedvariables file outside of the game manually for testing purposes. Those weren't real players. As far as not adding you, it should have. If you get a chance to try it again, turn on LUA errors with /console scriptErrors 1 and then use the button and let me know if an error is thrown. I haven't seen any issues with adding myself with non-guildies in the group while testing.

**Comment by curtman7** [comment]
I see what's happening, I was grabbing the error and noticed the class
name. I've was using my DK... which didn't exist in classic lol So i'm sure
that's why the error is coming up. I'll have to try it again when I can
create a guild on a classic class. Anyway, thanks for leading me in the
right direction, looking forward to being able to use this!! great work man

**Comment by Roeshambo** [comment]
Ah ya, i had it supporting those races/classes when I was testing it in retail but completely forgot I had removed them for testing in the beta. I just tested it using only vanilla classes and it worked fine so you shouldn't have any problems in 2 weeks :)

**Comment by Roeshambo** [comment]
I'll throw that code back in tonight and push the update out tomorrow so you can get at least a week if fiddling with it in. More people that try to break it the more reliable it'll be for the first raids :)

**Comment by curtman7** [comment]
Hi Roe,

I was playing with the HTML of the export because I wanted to host it on my
website for members to access it out of game, and wanted to show it to you
in case you wanted to update the look of the current export. I changed the
format from using the divs to using tables, I was able to get it more
responsive that way (for mobile screens). I've attached the code with some
sample data I was using if you want to check it out. You can also see my
slightly more modified version here:  http://cynwow.us/auxiliumdkp
I totally get it if you don't want to change anything, just wanted to try
to help out if I could. Really liking the addon :D

**Comment by Roeshambo** [comment]
Thank you, i'll definitely take a look. The HTML export was quickly thrown together and was simply rudimentary. I'm working with two other individuals regarding export. One that is hosting a website that will allow the data to be uploaded directly via the savedvariables file, the other is going to use a CSV output (which will be in the next version) to import data into a Discord bot.

**Comment by curtman7** [comment]
Awesome, those both sound awesome! Looking forward to it.
