### ISSUE TITLE
Feature request: Auctioneer style

### ISSUE THREAD

**Issue by johnpittman** [Roeshambo/MonolithDKP#81]
First off, thank you for your time to make a very useful add-on to save time/confusion. I am about to fork this project and dig through it to add an auctioneer feature but maybe you can save me a lot of code parsing by implementing it. 

# The Problem
### Bid sniping
The current issue in our guild has been everyone waits for the final countdown to hit 2, 1, then someone bid snipes right at the end which cause a bid of unfairness and outrage.

# Solution
### Auntioneer style
Ability to set an interval ex. 10 seconds, then each time someone bids, the interval resets to 10 second countdown until people exhaust the bidding. This alleviates all the concern with sniping and also allows for dynamic bid times for dkp systems.

Thoughts?

**Comment by Roeshambo** [comment]
Already written and implemented. Will be in the next version under "Anti Snipe" in the dkp modes window. The dev version on this Git does include all of the updated features. But will require everyone in the raid be updated to this version to use it properly. Go [here](https://github.com/Roeshambo/MonolithDKP/commit/08d53eca5986f9c83b12a399d120cbf21bf4940c) to see the newest additions.
