### ISSUE TITLE
Suggestion: Bid Log

### ISSUE THREAD

**Issue by Vivi9935** [Roeshambo/MonolithDKP#82]
Hey Roeshambo!

I was wondering if there was a way we could get a log that can be viewed by either officers or guild members (preferably an option to do both, either, or neither) that displays previous bids on items that have already been rolled out.

Also, how much do people normally donate to you for stuff like this? We really appreciate the great work you're doing, and we would love to show our support!

Thanks!
Venari-Whitemane
Majorpain Gaming GM

**Comment by Roeshambo** [comment]
Are you referring to a log of all bids submitted on a specific item in the past? Like the last time it dropped? Or are you referring to simply wanting to see all of the bids submitted in the current bid session? As far as donations, I haven't really gotten many thus far. Handful of small ($1-2) ones here and there.

**Comment by Vivi9935** [comment]
We'd like a log of all the bids submitted on a specific item in the past, yes. So if we look in like... Loot History. For example, if Shazzrah drops an item - we could look at it and see who bid and what they bid.

How many hours would it take for you to add something like that?

**Comment by Roeshambo** [comment]
Could take quite a bit of time but I think it could be manageable without overburdening the SavedVariables. I'll put it on the list.

**Comment by Vivi9935** [comment]
Awesome! 

If someone makes a suggestion, how long does it normally take you to make the addition? Like... hours of work put in, I should say.

**Comment by Roeshambo** [comment]
Depends on the request really. I just built the Bidding Interface for raiders to use on multiple requests and that took probably 12 hours of writing plus another 12 or so of testing/rewrites for optimization and bug fixes. Some are longer, and some requests are nothing more than a few lines of code. A lot of the features spider into dozens of other features so they all have to be retested to make sure different variations of the options being turned on or off don't cause problems.

**Comment by Vivi9935** [comment]
Very interesting! How many hours would it take you approximately to do something like add the bid log list we've been talking about? Just a ball park, if you could guess.

**Comment by Roeshambo** [comment]
Don't think that would take much more than 2-3 hours. My current focus is on the broadcast rewrite to ensure lossless data transfers between players. Once that is done (hopefully by the weekend) I can start adding more features.

**Comment by Vivi9935** [comment]
Awesome! We look forward to it! We just sent a donation your way from Majorpain Gaming over on Whitemane! Take the kiddos out or something, will ya? :D

**Comment by Roeshambo** [comment]
Tremendously appreciated. I'll try to make sure it comes out with the next release!

**Comment by Roeshambo** [comment]
Seriously though. Can't even begin to thank you.

**Comment by Vivi9935** [comment]
Don't even worry about it man! My officers were skeptical of the add-on at first, but after I convinced them and started using it for awhile and figuring it all out - we absolutely adore it. We just wanted to show our support, and we hope to see this grow into something amazing!

**Comment by Roeshambo** [comment]
Took a bit longer than expected given all the possible mode combinations. Still some testing to do to make sure nothing throws any unexpected errors but:

![image](https://user-images.githubusercontent.com/6285297/68193128-25644f00-ff78-11e9-8852-d65e5a754dfa.png)

Will be part of the next massive update once indexed broadcasting is finished.

**Comment by Vivi9935** [comment]
Looks great! Fantastic work, man!

**Comment by Vivi9935** [comment]
Hey Roe! Would it be possible for me to add you RealID or on Discord? I'd love to be able to chat with ya bout the new update.

**Comment by Roeshambo** [comment]
Sure, you can message me on https://discord.gg/uRwSnbw
