### ISSUE TITLE
previousDKP always 0?

### ISSUE THREAD

**Issue by matthew7j** [Roeshambo/MonolithDKP#83]
This is probably something I am doing wrong, but what is the purpose of the previousDKP field when exporting and why is ours always 0 for everyone?

**Comment by Roeshambo** [comment]
It doesn't serve any functional purpose. It can just be used as a baseline that I reset every month to see who is hording and who is spending etc. It shouldn't be zero for everyone. Unless it's frequently being reset to zero by an officer in the Manage tab
