### ISSUE TITLE
Rebuild DKP Table based on DKP History

### ISSUE THREAD

**Issue by DanSheps** [Roeshambo/MonolithDKP#84]
Currently noticing a sync issue between the DKP history and the DKP table.  It appears DKP is showing in the history and not being properly updated to the dkp table itself.

A simple button under management to rebuild the dkp table from history would be great (I may look into this myself and submit a PR for it)

**Comment by Roeshambo** [comment]
The entire broadcast system is currently being completely rebuilt from the ground up to utilize an indexing system. Everything will be built entirely off the loot and dkp histories

**Comment by DanSheps** [comment]
That definitely sounds much more robust.  Let me know if you need a beta tester.

**Comment by Sorterx** [comment]
Hello,

i have the exact same issue. 

Please update me on this. 

@Roeshambo is it possible to add you on skype or another messenger?

Greets,
Patrick

**Comment by Roeshambo** [comment]
I don't do 1 on 1s anymore as that has proven to be considerably overwhelming. But I can guarantee that it's at the forefront of development right now. Nothing else is getting addressed until data retention is where I'd like it to be. The new broadcast system will be able to ensure lossless transfer of data as well as recovering lost entries if needed. I don't have a ton of free time but whenever I do I'm working on this.

**Comment by DanSheps** [comment]
@Roeshambo Is there anything you need help with?

**Comment by Roeshambo** [comment]
Nope. Just a LOT of code. Half the add-on is being rewritten to accommodate the new record keeping and make it all as seemless as possible.

**Comment by Roeshambo** [comment]
System is pretty much done. Tweaks and testing for bugs and it should be all set. Hopefully by the end of the weekend or early in the week.

**Comment by Sorterx** [comment]
The issue is closed. I don't want to stress you -> I just want to get infos. Is the new version soon ready?

If you need a tester -> I am ready :dancer: 

Greets,
Patrick

**Comment by Roeshambo** [comment]
It's almost ready. The system itself is pretty much good to go. The obstacle I just have to finish up on is the actual deployment. It's going to require migrating tables to the new system. Which will also be required to only be run by ONE person in the guild (or else entries will overlap and cause hell). So I'm writing a sort of migration setup that will only allow one officer to run it as many people don't like to follow instructions. Once that's completed, it will be out. I'm really hoping by the end of this weekend, but it comes down to free time.
