### ISSUE TITLE
Unable to Add DKP

### ISSUE THREAD

**Issue by Seanieshotgunz** [Roeshambo/MonolithDKP#85]
Been loving this add on for about a month now, no complaints I understand the hard work you are putting in. Our guild ran into the problem this Tuesday where mid way through the raid it would no longer let us add DKP to people, we could subtract using the bidding system but beyond that, we aren't able. Any ideas on a workaround or fix?

**Comment by Roeshambo** [comment]
Did you have any Lua errors by chance? They wouldn't show up unless you manually turn them on with "/console scriptErrors 1". I have not experienced that so I'm not certain what could have caused it.

**Comment by Roeshambo** [comment]
Has this been resolved?
