### ISSUE TITLE
Cant use MDKP anymore

### ISSUE THREAD

**Issue by amaterasulol** [Roeshambo/MonolithDKP#86]
hey guys, i used monolithdkp for some time. i switched to an alt and had it still enabled. i played around and checked for "history". now i cant use it anymore on my main or my alt.
as soon as i log in it comes up with this error:

Date: 2019-11-08 18:03:19
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\MonolithDKP\Modules\DKPHistory.lua line 30:
   attempt to compare number with nil
Debug:
   [C]: ?
   MonolithDKP\Modules\DKPHistory.lua:30:
      MonolithDKP\Modules\DKPHistory.lua:29
   [C]: sort()
   MonolithDKP\Modules\DKPHistory.lua:29: SortDKPHistoryTable()
   MonolithDKP\Modules\DKPHistory.lua:250: DKPHistory_Update()
   MonolithDKP\ConfigMenuTabs.lua:312: ConfigMenuTabs()
   MonolithDKP\MonolithDKP.lua:220: CreateMenu()
   MonolithDKP\init.lua:433: OnInitialize()
   MonolithDKP\init.lua:163:
      MonolithDKP\init.lua:145
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.3.3
  AtlasLootClassicData, vv1.3.3
  AtlasLootClassicDungeonsAndRaids, vv1.3.3
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicAuraDurations, v
  DBMCore, v1.13.18
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherMate2, v1.45.5
  Grid2, vr939
  Grid2LDB, vr939
  Grid2RaidDebuffs, vr939
  LootAppraiserClassic, vv1.1
  MapCoords, v0.32c
  MonolithDKP, v1.6.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TradeSkillMaster, vv4.8.20
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=44a)

**Comment by Roeshambo** [comment]
It looks like you might have a DKPHistory entry that doesn't have a timestamp for whatever reason. Are there any other errors that pop up (if there are, there's usually a left and right button at the bottom and says 1/3 or 1/2)?

**Comment by Roeshambo** [comment]
Has this been resolved?
