### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by qq56403509** [Roeshambo/MonolithDKP#87]
Hello Roeshambo:
    I have suggestion for this addon. we have 2 raid in the guild .but we can't use monolithDKP for both raid group because those groups have different DKP system。 The first one no decrease. but the second one has decrease. is that possible add a list or new tab for the guild have 2 raid system?

  
   is that possbile to add manual master loot with a dkp option? because we may not bid the item and we just send reward item to someone and deduct the dkp point

**Comment by qq56403509** [comment]
we have 2 raid groups 1st one .the system is independent MC and independent BWL。 the second one is one system for MC AND bwl AND WITH DECREASE PER WEEK.

So i suggest that add a tab option for the raid group .one tab for one raid group list

**Comment by Roeshambo** [comment]
Adding a second "group" might be a bit of an overhaul for the addon. The same effect can be reached by giving each group their own rank within the guild "Core Raider 1" and "Core Raider 2" depending on their team. Then simply set those to your personal core raid team within the addon. You can use the weekly decay on only selected players if you check the box below it. So you'd filter the list to only show your core team, select all, decay selected. 

Also, there is a manual loot command (/dkp award). You can use that to manually assign loot to someone and charge them DKP. The syntax is shown in the "/dkp ?" command. It's /dkp award PLAYERNAME COST [ITEM_LINK]

**Comment by qq56403509** [comment]
is that possible to make a manually assign loot window instead of input a long command?

**Comment by Roeshambo** [comment]
Possible, sure. But creating a GUI for it would be considerably time consuming, despite being "easy". At the moment there are some considerably more pressing things that need to be addressed so it may be a bit of time.

**Comment by Roeshambo** [comment]
The command has been changed to /dkp award [item link] for ease of use. You'll be prompted with the Award window where you can select the additional required options.
