### ISSUE TITLE
Failure DKP assigning

### ISSUE THREAD

**Issue by Belaros** [Roeshambo/MonolithDKP#88]
Hi,

always when we want to assign DKP during a raid for any reason, there is a failure and we can't assign the DKP. We are playing on a german Server. The failure which pops up is:

Message: Interface\AddOns\MonolithDKP\Modules\AdjustDKP.lua:45: attempt to index upvalue 'c' (a nil value)
Time: Sun Nov 10 17:22:03 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\Modules\AdjustDKP.lua:45: attempt to index upvalue 'c' (a nil value)

Locals:

**Comment by Roeshambo** [comment]
I'm not at home but I think I see the problem. Delete the mondkp tag in the guild leaders note and try again.

**Comment by Belaros** [comment]
Great it worked! Thanks a lot
