### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by bas-noorlander** [Roeshambo/MonolithDKP#9]
Trying to install this on retail produces the following error

Adding a `end` on init.lua:132 fixes the issue.

```
Message: Interface\AddOns\MonolithDKP\init.lua:216: 'end' expected (to close 'function' at line 85) near '<eof>'
Time: Fri Aug 16 21:46:18 2019
Count: 1
Stack: Interface\AddOns\MonolithDKP\init.lua:216: 'end' expected (to close 'function' at line 85) near '<eof>'

Locals: 
```

**Comment by Roeshambo** [comment]
Did you download that from here? If so, redownload and give it another go. Forgot to uncomment a line from testing. The end on line 127 should have the -- removed.
