### ISSUE TITLE
Refreshing DKP Player List Requires UI Reload

### ISSUE THREAD

**Issue by wheetcracker** [Roeshambo/MonolithDKP#90]
Hello!

I've been using Monolith DKP as a tool to invite our guild members to the raid. When it comes to raid time a lot of people tend to be logging on at the same time. When this is happening the DKP list when sorted by "Online" and "Not in Raid" does not update unless a UI reload is performed.

**Comment by Roeshambo** [comment]
That shouldn't be the case at all. Unchecking and rechecking filters should be sufficient

**Comment by wheetcracker** [comment]
It seems to be an issue when your table view is set to the standby list.

Edit: Just tested, here were the steps used to reproduce:

Created a standby list with some players.
Set table view to standby list.
Asked one of them to log off then checked and unchecked online filter. Everything seems fine.
Ask them to log back on then check and unchecked online filter. They don't show up on the list.

**Comment by Roeshambo** [comment]
I'll take a look at that and see if it's removing players from the table instead of simply hiding them.

**Comment by Roeshambo** [comment]
Was not able to successfully replicate this. But added a few redundancies to make sure if a table has no entries it defaults back to the "View All" view.
