### ISSUE TITLE
"Invite Selected Players" Does Not Do What it Says

### ISSUE THREAD

**Issue by wheetcracker** [Roeshambo/MonolithDKP#91]
When highlighting many players from the DKP list to invite to the raid not all of them are invited. It seems that only a few (3-5) are invited.

**Comment by Roeshambo** [comment]
It invites enough to fill your party, then converts to a raid and invites the rest. If you're already in a raid or full party, it won't do it at the moment. It is fixed in the next version. But that's not out yet.
