### ISSUE TITLE
Incorrect dkp zero sum calculation

### ISSUE THREAD

**Issue by TOKocsis** [Roeshambo/MonolithDKP#92]
We had a raid with 30 raid members, with empty standby list. The looted item was awarded for 60, therefore after Distribute DKP everyone should have get 2 dkp.
But the distributed cost is 1.88, and the message also wrote that distributed between 32 players. This seems to be an obvious bug adding 2 non existing players.

In the attached image it is also visible that in the dkp history 30 names are visible, not 32.
Also uploaded an image showing the item cost being 60.

![32member](https://user-images.githubusercontent.com/43139780/68708519-30306c80-0594-11ea-9e0b-77c77c09df49.png)
![addonwindow](https://user-images.githubusercontent.com/43139780/68708571-4807f080-0594-11ea-807c-7176baadf8bf.PNG)
![Capture](https://user-images.githubusercontent.com/43139780/68708685-81d8f700-0594-11ea-8086-4da96d025fbc.PNG)

**Comment by Roeshambo** [comment]
I'm curious as to what it read as the other 2. Did you happen to have anyone on your standby list? Or did you have Include Standby checked in the distribution? I'll look in to that.

**Comment by TOKocsis** [comment]
I may have had it checked it to include stand by list yes, but Im sure there was no one on the list. 
The history should show the standby names I guess, and if you manually count the names its 30.

Also since we are a new guild, the whole list is 31 members, not 32.
![list](https://user-images.githubusercontent.com/43139780/68711300-a4214380-0599-11ea-8131-69efae325792.PNG)

**Comment by Roeshambo** [comment]
Ok. The Zero Sum system is one of the least looked at portions of the addon as I wrote it all in one night and have literally never heard any feedback on it. So I kind of expected something to fall through the cracks at some point. I'll look through it and see if it somehow may have caught a duplicate. What version are you using and where did you download it from?

**Comment by Roeshambo** [comment]
And was it only the one that incorrectly distributed the DKP? Or did they all do the same?

**Comment by TOKocsis** [comment]
Every time the same error, calculating the dkp with 32, instead of 30. 
60/30 should be 2, was 1.88.
50/30 should be 1.66, was 1.56 as you see on the sniplet.
I installed it with the twitch desktop app.
In game I see v1.6.2 
(I updated it today before the raid)

**Comment by Roeshambo** [comment]
It's worth noting that standby lists are persistent until you manually remove anyone from it. Even if the players that were on it were deleted from the DKP list as a whole (something I should probably fix now that I realize this). Can you look in your \WTF\Accounts\ACCOUNT_NAME\SavedVariables\MonolithDKP.lua file, at the bottom, you'll see the MonDKP_Standby table. Are there any names in it? Or is there anything in it at all? If nothing is in it, it should simply say MonDKP_Standby = {}

**Comment by TOKocsis** [comment]
You were right, I found two person in the mentioned file. I guess i just deleted my whole list, without emptying the standby. And now i cannot see them anymore but they are still there.
Should I just delete them from my file and the issue will be solved at least for me?

**Comment by Roeshambo** [comment]
You can delete the entire MonDKP_Standby table and it will be resolved. Make sure the game is CLOSED entirely before deleting it. Don't use "exit game". Log out and then close the client. I'll add a stipulation to delete players from the standby list if their entry is deleted from the DKP table.

**Comment by TOKocsis** [comment]
Thank you for your super quick reply, and for your work to make the addon work! I will mention the possibility to donate to my guild!
