### ISSUE TITLE
Dkp on full screen

### ISSUE THREAD

**Issue by Fearkilll** [Roeshambo/MonolithDKP#96]
Good day.
I have a problem, today i open dkp and see it
https://dropmefiles.com/pKWAM
I try to use /dkp reset but it didn't work.  I can use a addons.
Need help pls

**Comment by Roeshambo** [comment]
Change your UI scaling. Then change the add-on scaling in the options tab to really small. Then you can put your UI scaling back to where it was and correct the addons scale as needed
