### ISSUE TITLE
Bugsack error

### ISSUE THREAD

**Issue by chaluo** [Roeshambo/MonolithDKP#97]
1x MonolithDKP\Modules\RaidTimer.lua:69: attempt to index field '?' (a nil value)
MonolithDKP\Modules\RaidTimer.lua:69: in function <MonolithDKP\Modules\RaidTimer.lua:45>
MonolithDKP\Modules\RaidTimer.lua:237: in function <MonolithDKP\Modules\RaidTimer.lua:211>

Locals:
amount = 20
reason = "Time Interval Bonus"
tempName = nil
tempList = "Moz,Daybreak,Anavar,Darkwinduck,Mippzy,Thânos,Naix,Zu,Meztulo,Ogleon,Perilous,Dabejoo,Wagieragie,Bisonfury,Kaisercarni,Rostafirad,Brandstof,Tyx,Shalora,Machoman,Aekainal,Hakkertie,Bunjo,Jovaras,Juicyfruit,Notthehair,Seika,Savras,Kynen,Tamalyn,Dherogs,Iamnotreal,Glemtnavn,Tusks,Flare,Mouse,Sharpeyez,Oxie,Daneth,Tuksu,Angrboda,Magnanimous,Rilous,"
curTime = 1573677213
(for index) = 5
(for limit) = 5
(for step) = 1
i = 5
(*temporary) = <function> defined =[C]:-1
(*temporary) = "Moz,Daybreak,Anavar,Darkwinduck,Mippzy,Thânos,Naix,Zu,Meztulo,Ogleon,Perilous,Dabejoo,Wagieragie,Bisonfury,Kaisercarni,Rostafirad,Brandstof,Tyx,Shalora,Machoman,Aekainal,Hakkertie,Bunjo,Jovaras,Juicyfruit,Notthehair,Seika,Savras,Kynen,Tamalyn,Dherogs,Iamnotreal,Glemtnavn,Tusks,Flare,Mouse,Sharpeyez,Oxie,Daneth,Tuksu,Angrboda,Magnanimous,Rilous,"
(*temporary) = nil
(*temporary) = 20
(*temporary) = <table> {
 1 = <table> {
 }
}
(*temporary) = <table> {
 previous_dkp = 0
 dkp = 1950
 lifetime_spent = -18
 lifetime_gained = 1970
 role = "No Role Detected"
 spec = "No Spec Reported"
 class = "DRUID"
 player = "Rilous"
 rankName = "Core Raider"
 rank = 4
}
(*temporary) = 1970
(*temporary) = 42
(*temporary) = "attempt to index field '?' (a nil value)"
AwardRaid = <function> defined @MonolithDKP\Modules\RaidTimer.lua:45
MonDKP = <table> {
 DKPHistory_Update = <function> defined @MonolithDKP\Modules\DKPHistory.lua:228
 RosterSeedUpdate = <function> defined @MonolithDKP\Core.lua:278
 GetDKPSettings = <function> defined @MonolithDKP\Core.lua:336
 StartBidTimer = <function> defined @MonolithDKP\Modules\Bidding.lua:743
 PurgeDKPHistory = <function> defined @MonolithDKP\Core.lua:355
 RaidTimerPopout = MonDKP_RaidTimerPopout {
 }
 SortLootTable = <function> defined @MonolithDKP\Modules\LootHistory.lua:13
 ConfigTab3 = <unnamed> {
 }
 UIConfig = MonDKPConfig {
 }
 GetGuildRankGroup = <function> defined @MonolithDKP\Core.lua:249
 BroadcastTimer = <function> defined @MonolithDKP\Core.lua:401
 ConfigTab6 = <unnamed> {
 }
 ClassGraph = <function> defined @MonolithDKP\Modules\ClassGraph.lua:7
 RaidTimer = <unnamed> {
 }
 BroadcastStopBidTimer = <function> defined @MonolithDKP\Modules\Bidding.lua:707
 ValidateSender = <function> defined @MonolithDKP\Modules\comm.lua:16
 CreateBidWindow = <function> defined @MonolithDKP\Modules\Bidding.lua:1063
 UpdateQuery = <function> defined @MonolithDKP\Core.lua:529
 CheckOfficer = <function> defined @MonolithDKP\Core.lua:222
 DKPHistory_Reset = <function> defined @MonolithDKP\Modules\DKPHistory.lua:48
 AdjustDKP = <function> defined @MonolithDKP\Modules\AdjustDKP.lua:8
 Options = <function> defined @MonolithDKP\Modules\Options.lua:58
 AdjustDKPTab_Create = <function> defined @MonolithDKP\Modules\AdjustDKP.lua:309
 ConfigTab1 = <unnamed> {
 }
 AutoAward = <function> defined @MonolithDKP\Modules\Standby.lua:46
 ConfigMenuTabs = <function> defined @MonolithDKP\ConfigMenuTabs.lua:116
 LootHistory_Reset = <function> defined @MonolithDKP\Modules\LootHistory.lua:351
 FilterDKPTable = <function> defined @MonolithDKP\MonolithDKP.lua:68
 StartRaidTimer = <function> defined @MonolithDKP\Modules\RaidTimer.lua:139
 OnInitialize = <function> defined @MonolithDKP\init.lua:340
 GetThemeColor = <function> defined @MonolithDKP\Core.lua:268
 Table_Search = <function> defined @MonolithDKP\Core.lua:672
 SortDKPTable = <function> defined @MonolithDKP\MonolithDKP.lua:143
 CreateButton = <function> defined @MonolithDKP\Core.lua:390
 ToggleDKPModesWindow = <function> defined @MonolithDKP

**Comment by Roeshambo** [comment]
Ah, amateur error. Using a table.remove in a for loop that is the length of the same table. I'll get that fixed. It basically meant someone on the standby list was also in the raid so the table ended up being shorter than the loop expected it to be.

**Comment by chaluo** [comment]
Excellent. Thanks! Love your addon btw. Could you add a paypal link or something to the readme.md?

**Comment by Roeshambo** [comment]
There's one up on curse @ https://www.curseforge.com/wow/addons/monolith-dkp
This'll be fixed in the next version.
