### ISSUE TITLE
MDKP not loading at login

### ISSUE THREAD

**Issue by Shockhaus** [Roeshambo/MonolithDKP#98]
Hi,

MDKP doesnt seem to load when i log into my main at all. It is enabled on the addons list, but won't load and none of the commands work. I can use it on my alts for some reason, but there are no differences in the addons that are enabled between any of my characters.

Any ideas what could be causing the issue?

**Comment by Roeshambo** [comment]
Turn on script errors "/console scriptErrors 1" and relog. Post any errors received. Make sure to click the left or right arrows of there are more than one

**Comment by Shockhaus** [comment]
I may be too much of a novice here. I typed in the command exactly as above (in game) but nothing happened immediately to let me know the command has worked, and noting happened after relog. I had swatter enabled, but there were no errors listed there.

Could there be something in the settings folder for that specific character not working properly? I have tried reinstalling the addon so really no idea what is going on here.

**Comment by Roeshambo** [comment]
On your character selection screen, in the addons list, make sure the addon is active for your character. It's possible to only have it active for certain characters and it looks like it's on (kinda). Click it off and back on to make sure. If there are no errors, then the addon isn't being loaded at all. Which isn't something I can control.

**Comment by Shockhaus** [comment]
The box was ticked on the character addon list, but I went into the WTF>account>server>character>addons text file, and MDKP was listed as "disabled" there. I manually amended to "enabled" and it worked on the next login. Must have been a Blizzard interface error after all that.

Thanks for your time in trying to help!
