### ISSUE TITLE
Request/Suggestion/Help

### ISSUE THREAD

**Issue by chadahelmsley** [Roeshambo/MonolithDKP#99]
First thing I want to say is that the add-on is a great help for DKP guilds and we just started using it for classic.

If I may make a request Id like to ask for some kind of command that allows us to add people to the standby list.  Not sure what the command would be but something like:
"/dkpstanbylistadd [character name]" or something idk

The reason I ask for this is because of granting people "Bonus DKP" for certain things and wanting to just add them all to the list and then add the dkp all at once rather than either Individually adding the DKP or having to go through the roster and right click add to standby for each member then adding the dkp.  With the above I could make a macro that adds a list of people essentially.

If not making a command maybe making the search function or adding a way to add a list of people rather than having to use the method stated above.

The same could be done for the Core Raider table as well (assuming that you can have names on each table individually not sure I haven't tried this function yet) so that if we have multiple "Incentives" to get extra DKP we could have 2 separate lists for 2 separate bonuses essentially.

Thank you in advance for reading this and for the assistance.

**Comment by Roeshambo** [comment]
You can ctrl+click names on the list to select several people and then right click one of them and add them all to standby at the same time. You can make this easier by using the "Not In Raid" filter on the Filters tab which will only list players that are not in your current raid. The core raider list is selected by rank.

**Comment by Roeshambo** [comment]
Please reopen if you have additional questions/concerns
